### ISSUE TITLE
Tests are horribly out-of-date

### ISSUE THREAD

**Issue by goldfirere** [goldfirere/singletons#103]
The testsuite just failed 36 out of 40 tests. I don't think it's been updated since allowing singletonization of overlapping patterns.

**Comment by jstolarek** [comment]
I remember trying to fix broken singletonization of Nat (see #97). I think that for some reason I found this non-trivial but can't remember why exactly :-/ Anyway, I'm totally busy with teaching until the end of month. After that I can try and help with this.

Aside: I found updating testsuite results a pain. Mostly because copying the test results to be new golden files was tedious. That's why I was thinking about creating a script that would take all the results from the testsuite run and use them to create new golden files. Never got to actually writing it though. Perhaps now is a good moment for this.

**Comment by goldfirere** [comment]
Not a terrible idea, but it would require care to use. As annoying as updating the golden files is, I've found real bugs by reading diffs, even when I thought about just copying over. Doing it by hand forces me to think about each file, and that may be a good thing.

**Comment by jstolarek** [comment]
Obviously yes, you have to examine the diffs carefully. The script would just simplify updating the results.

**Comment by jstolarek** [comment]
Richard, I'm afraid this one is mostly on you as after th-desugar changes I understand little of generated code - see my comment in #97.

Now that we support two versions of GHC - 7.8 and 7.10 - we can have different code generated by each of these versions. Luckily the testsuite supports that. My proposal is this: if you fix the tests on GHC **7.8** I'll do all the boring work of adding support for GHC 7.10. Does that sound good?

**Comment by goldfirere** [comment]
This is effectively blocked by #113. There's not much point in fixing tests until we decide if match flattening is effective.

**Comment by jstolarek** [comment]
I strongly disagree. This "temporary" test breakage lasts for months now. Tests are meant to ensure that changes that we make to the library don't introduce any unexpected behaviour. If I make changes and they break something I won't even realize. Sure that the current implementation of flattening might not be our final word but I don't think this is the reason to have broken tests. If we change flattening in the future we'll update the tests again.

**Comment by goldfirere** [comment]
I agree with your sentiment but not your conclusion: I think the current state of affairs calls for rolling back match flattening. Perhaps we should revert fabe02a31130e1c46410b97f070f5aef42349ff4 and 4610fc5f0990447e6b20fe4efa82e3866fc2b578, and then proceed. I can then reapply these commits on a branch, sort out the problems, fix the tests, and merge. In the meantime, with match flattening reverted, we can make forward progress.

Thoughts?

**Comment by jstolarek** [comment]
> I think the current state of affairs calls for rolling back match flattening.

Perhaps. I don't have a strong opinion here. If it is meant to be an experimental feature and the price for having it in the master branch is a broken testsuite then it should most likely go into its own separate branch.

**Comment by goldfirere** [comment]
I have removed match flattening. The tests work with 7.8. Can you update for 7.10, which I recall was your offer? Thanks!

**Comment by jstolarek** [comment]
I updated the tests. Turns out that some things don't work under GHC 7.10. See #116, #117 and #118.
