### ISSUE TITLE
Fix 7.10 compilation issues

### ISSUE THREAD

**Issue by goldfirere** [goldfirere/singletons#104]
Right now, it dies because TH no longer accepts the name `:[]$` for an entity. There may be more problems behind this one.

**Comment by jstolarek** [comment]
Sounds like result of fixing [#7484](https://ghc.haskell.org/trac/ghc/ticket/7484). If so there will most likely be more errors like this.

**Comment by goldfirere** [comment]
Fixed on 1.0 branch.
