### ISSUE TITLE
Documentation error

### ISSUE THREAD

**Issue by crockeea** [goldfirere/singletons#105]
There's a link that doesn't work for singletons on Haddock, so I filed an [issue there](https://github.com/haskell/hackage-server/issues/268). Someone indicated that you generated the docs manually, and that there might be a minor problem there. Hopefully you can help determine if this is a singletons issue or a Haddock issue.

**Comment by goldfirere** [comment]
As posted on haskell/hackage-server#268, I believe this is squarely Hackage's bug. If there's a workaround I can do, please let me know and I'll do it.
