### ISSUE TITLE
Support for th-desugar 1.5?

### ISSUE THREAD

**Issue by peti** [goldfirere/singletons#107]
Hi, we would like to update to `th-desugar` version 1.5 in NixOS, but unfortunately that update would break the singletons library. We've tried lifting the restrictions from the Cabal file, but the build won't succeed:

    src/Data/Singletons/Util.hs:85:25:
        Ambiguous occurrence ‘tupleDegree_maybe’
        It could refer to either ‘Data.Singletons.Util.tupleDegree_maybe’,
                                 defined at src/Data/Singletons/Util.hs:75:1
                              or ‘Language.Haskell.TH.Desugar.tupleDegree_maybe’,
                                 imported from ‘Language.Haskell.TH.Desugar’ at src/Data/Singletons/Util.hs:20:1-34
                                 (and originally defined in ‘th-desugar-1.5:Language.Haskell.TH.Desugar.Util’)

    src/Data/Singletons/Util.hs:99:32:
        Ambiguous occurrence ‘unboxedTupleDegree_maybe’
        It could refer to either ‘Data.Singletons.Util.unboxedTupleDegree_maybe’,
                                 defined at src/Data/Singletons/Util.hs:89:1
                              or ‘Language.Haskell.TH.Desugar.unboxedTupleDegree_maybe’,
                                 imported from ‘Language.Haskell.TH.Desugar’ at src/Data/Singletons/Util.hs:20:1-34
                                 (and originally defined in ‘th-desugar-1.5:Language.Haskell.TH.Desugar.Util’)

Would it be possible to get a new release of `singletons` that supports [the latest version of its dependencies](http://packdeps.haskellers.com/feed?needle=singletons)?

**Comment by goldfirere** [comment]
Fixed, and released in singletons-1.1. Thanks for reporting (and for including `singletons` in NixOS)!
