### ISSUE TITLE
Update th-desugar submodule

### ISSUE THREAD

**Issue by jstolarek** [goldfirere/singletons#111]
It looks like `th-desugar` submodule is woefully out of date. Current development version of singletons requires `th-desugar >= 1.5.2` but the submodule is at version `1.5`. I'm not sure whether the submodule should point to the development or stable version of `th-desugar` so I'm not updating it myself.

**Comment by goldfirere** [comment]
On the master branch, it should point to the development version. (But I believe dev and stable versions of th-desugar are roughly the same these days.)
