### ISSUE TITLE
Implement promotion of fixity declarations

### ISSUE THREAD

**Issue by jstolarek** [goldfirere/singletons#117]
Currently we drop fixity declarations due to [#9066](https://ghc.haskell.org/trac/ghc/ticket/9066). But in GHC 7.10 this bug is fixed. Should we try to promote fixity declarations with GHC 7.10?

**Comment by goldfirere** [comment]
Yes, we should. Leaving the ticket open as a feature request.

**Comment by jstolarek** [comment]
I believe that we generate an annotation during promotion of fixity declarations. What was the reason for doing this?

**Comment by peti** [comment]
Is this issue solved in GHC 7.10.2?

**Comment by cstrahan** [comment]
@goldfirere Is this resolved?

**Comment by goldfirere** [comment]
GHC 7.10 supports what we need for this feature, but the singletons end is not yet done. I'm planning on doing a bunch of work on singletons in the next two weeks sometime, and I'll scoop this up then.

**Comment by peti** [comment]
Will there be a new Hackage release that contains this fix soon? I'd like to re-enable this library in the NixOS distribution ASAP.

**Comment by goldfirere** [comment]
Why is this bug holding up inclusion in NixOS? The latest version of the library should work in 7.10.2, with this bug, admittedly, but I wouldn't imagine this particular bug would be a deal-breaker.

I'm in the midst of (finally) fixing #25, and would love to wait until that's done and then publish singletons-2.0. If this bug is a deal-breaker, I can cherry-pick the fix over to the v1.x branch and cut a new version.

**Comment by peti** [comment]
@goldfirere, well singletons-1.1.2.1 fails its test suite when compiled with GHC 7.10.2. That's a little disconcerting, no? Personally, I am unaware of the intricacies of this library, so if you say that version is fine to use with GHC 7.10.2, then I'll re-enable it in NixOS -- I'll trust your judgement. Still, I'm a little uncomfortable distributing software that doesn't pass its own regression test suite.

**Comment by goldfirere** [comment]
Sorry for being so slow here. Got back from a conference last week and am digging out. As commented on #122, the testsuite is not supported for GHC 7.10/singletons-1.x combinations. (Note that the .cabal file says that it's not tested with GHC 7.10. I am working on a vast update to `singletons`, due out in the next two weeks. `singletons-2.0` will work with GHC 7.10!

Thanks!
