### ISSUE TITLE
Haddock fails with singletons-2.0

### ISSUE THREAD

**Issue by k0001** [goldfirere/singletons#126]
It seems #120 is happening again with `singletons-2.0`.

When building the haddocks, I get:

```
src/Data/Singletons/Prelude/Num.hs:43:3:
    Haddock documentation not (yet) handled by Template Haskell
```

**Comment by goldfirere** [comment]
How embarrassing. Thanks for the report. Should release 2.0.0.1 later today.

**Comment by k0001** [comment]
Thanks!
