### ISSUE TITLE
No singletonized filter (sFilter)

### ISSUE THREAD

**Issue by int-index** [goldfirere/singletons#130]
For some reason `sFilter` is not defined in `Data.Singletons.Prelude.List`.

**Comment by int-index** [comment]
Nevermind, I should've read the README.

**Comment by int-index** [comment]
Wait, actually `filter` can be defined like so:

```haskell
  filter :: (a -> Bool) -> [a] -> [a]
  filter _pred []    = []
  filter pred (x:xs) = case pred x of
    True -> x : filter pred xs
    False -> filter pred xs
```

Then it can be singletonized.

**Comment by goldfirere** [comment]
Thanks for pointing this out. Expect a new release later today.
