### ISSUE TITLE
Lookup fails to reduce

### ISSUE THREAD

**Issue by AndrasKovacs** [goldfirere/singletons#132]
With singletons-2.0.1, `Lookup` fails to reduce:

```haskell
> import Data.Singletons.Prelude
> import Data.Promotion.Prelude
> :kind! Lookup Int '[ '(Int, Int) ]
Lookup Int '[ '(Int, Int) ] :: Maybe *
= Data.Singletons.Prelude.List.Case_1627850491
    Int Int Int '[] (Apply (Apply (:==$) Int) Int)
```

**Comment by int-index** [comment]
Actually it's because `:==$` doesn't work on kind `*`. I don't know if it's the intended behavior, but it's been that way for a long time now.

**Comment by AndrasKovacs** [comment]
I sense something rather fishy here, because if I start up GHCi, `Lookup` doesn't work with any kinds on the first `:kind!` query, but then it works afterwards (for non-`*` kinds). Example session:

```haskell
> import Data.Promotion.Prelude
> :kind! Lookup True '[ '(True, True) ]
Lookup True '[ '(True, True) ] :: Maybe Bool
= Data.Singletons.Prelude.List.Case_1627850491
    'True
    'True
    'True
    '[]
    (Data.Singletons.Apply (Data.Singletons.Apply (:==$) 'True) 'True)
> :kind! Lookup True '[ '(True, True) ]
Lookup True '[ '(True, True) ] :: Maybe Bool
= JustSym1 'True
```

I'm currenty on Windows, with GHC 7.10.2.

**Comment by int-index** [comment]
I can reproduce this behavior, GHC 7.10.2 on Ubuntu Linux.

**Comment by goldfirere** [comment]
There is no instance for `:==` over `*` because there is no one sensible definition for it. See #106. I'm happy to take a suggestion for how better to document this fact, which tends to surprise people.

As for the lack of reduction issue, that's terrible, but a bug in GHC. Posted as GHC's #11084, https://ghc.haskell.org/trac/ghc/ticket/11084.
