### ISSUE TITLE
Promoting types containing a string

### ISSUE THREAD

**Issue by andrewthad** [goldfirere/singletons#134]
I have a data type that represents a piece of a url. It looks like this:

    data Piece = Static String | Capture

Meaning that we can either have a static string (which should match the given string) or we should capture the result. If I write:

    $(singletons [d|                                                            
      data Piece = Static String | Capture                                 
      |])

I get this error:

    Data constructor ‘Capture’ comes from an un-promotable type ‘Piece’

But if I try using Symbol instead:

    $(singletons [d|
      data Piece = Static Symbol | Capture
      |])

I get this error:

    /home/andrew/Development/serpentine/src/Main2.hs:26:3:
        Couldn't match type ‘[Char]’ with ‘Symbol’
        Expected type: DemoteRep 'KProxy
          Actual type: Symbol
        In the first argument of ‘toSing’, namely ‘b_aC9d’
        In the expression:
            toSing b_aC9d :: SomeSing (KProxy :: KProxy Symbol)

    /home/andrew/Development/serpentine/src/Main2.hs:26:3:
        Couldn't match type ‘[Char]’ with ‘Symbol’
        Expected type: Symbol
          Actual type: DemoteRep 'KProxy
        In the first argument of ‘Static’, namely ‘fromSing b_aC9c’
        In the expression: Static (fromSing b_aC9c)

So, is it possible to promote a string? If not, what is the recommended workaround?

**Comment by vagarenko** [comment]
@andrewthad see https://github.com/goldfirere/singletons/issues/76#issuecomment-44220892

**Comment by andrewthad** [comment]
Gotcha.
