### ISSUE TITLE
Deriving Enum only works in simple cases

### ISSUE THREAD

**Issue by andrewthad** [goldfirere/singletons#135]
In a routing/dispatch implementation I'm using singletons for, I have the following:

    $(singletons [d|
      data CrudRoute = AddR | EditR | DeleteR | ViewR
        deriving (Eq,Ord,Enum,Bounded,Show)
      data MyRoute = UsersR | ProfileR | RenameR | DogR CrudRoute
        deriving (Eq,Ord,Enum,Bounded,Show)
      |])

This fails with the following:

    Can't derive Enum instance for MyRoute_0.

I assume that deriving the `Bounded` instance likely doesn't work either. Can the template haskell generator be amended to support deriving these for types that consist of other `Enum`/`Bounded` types?

**Comment by goldfirere** [comment]
This is easy enough to do, but it goes against the specification of deriving `Enum` instances. Your code doesn't compile even without the `singletons` stuff. At this point, I'm afraid I don't have the time to invest in this sort of extension beyond Haskell98/2010. I'm happy to take a pull request, though!

**Comment by andrewthad** [comment]
Oh my, I did not realize that vanilla haskell wouldn't derive `Enum` in these cases. I'll think about this more and try to bring my TH knowledge up to the level required to do this.

Also, since the normal `deriving` mechanism doesn't work for this case, I assume that the best way to write this would be as a separate TH function. Like this:

    $(singletons [d|
      data CrudRoute = AddR | EditR | DeleteR | ViewR
        deriving (Eq,Ord,Enum,Bounded,Show)
      data MyRoute = UsersR | ProfileR | RenameR | DogR CrudRoute
        deriving (Eq,Ord,Show)
      |])
    
    deriveEnumFancy ''MyRoute
    deriveBoundedFancy ''MyRoute

**Comment by goldfirere** [comment]
I believe this could be even a separate package, that just does vanilla (non-singletonized) derivations. Then, you could say

```
$(singletons [d|
  data CrudRoute = ...
    deriving (Enum, ...)
  data MyRoute = ...
  $( deriveEnum 'MyRoute )
|])

The normal instance spit out by `deriveEnum` would then be singletonized just like any other instance declaration.

**Comment by andrewthad** [comment]
What? You can put [TH inside TH](http://vignette3.wikia.nocookie.net/glee/images/6/6f/We-need-to-go-deeper_inception.jpg/revision/latest?cb=20130123200723)?!

That seems like an excellent solution. And one that I'm much more likely to be able to figure out how to write. I'll consult reddit first to check if anyone has already written this.

**Comment by goldfirere** [comment]
Sure. In my example, the `deriveEnum` will get executed when building the declaration quote. You can actually layer TH as deeply inside TH as you want, as long as you always alternate quoting with splicing. (I conjecture that we could lift the "alternating" restriction, but no one's asked for that yet.)

**Comment by andrewthad** [comment]
I just tried this:

    $(singletons [d|
      data CrudRoute = AddR | EditR | DeleteR | ViewR
        deriving (Eq,Ord,Enum,Bounded,Show)
      data MyRoute = UsersR | ProfileR | RenameR | DogR CrudRoute
        deriving (Eq,Ord,Show)
      $( derive makeEnum ''MyRoute )
      |])

Using the `derive` package for `derive` and `makeEnum`, and I get this error:

    Splices within declaration brackets not (yet) handled by Template Haskell

I'm using GHC 7.10.

**Comment by goldfirere** [comment]
Bah. I was hoping that, if I didn't mention this possibility, it wouldn't really happen. (I had a nagging suspicion you might hit this.) You *can* use TH within TH, but I guess not in declarations. This is odd, though -- it should be easy enough. Care to post a GHC feature request on this front?

Sadly, punting to GHC isn't really a punt, as far as I'm concerned, as I'm the TH maintainer. No promises for 8.0, I'm afraid. In any case, fixing it in GHC seems like the Right Fix. Thanks!

**Comment by andrewthad** [comment]
Thanks for suggesting the possibility though. It felt good to try. I'll open a feature request on GHC. I'm sure I'll come across a workaround that will do the job for now.

**Comment by andrewthad** [comment]
Ticket opened: https://ghc.haskell.org/trac/ghc/ticket/11129#ticket

**Comment by jstolarek** [comment]
[#6089](https://ghc.haskell.org/trac/ghc/ticket/6089)
