### ISSUE TITLE
Equality on singleton constructors that require another singleton

### ISSUE THREAD

**Issue by taksuyu** [goldfirere/singletons#137]
With the classic Nat example
```haskell
$(singletons [d|
  data Nat
    = S Nat
    | Z
    deriving (Eq)
    |])

-- fromSing $ SZ %:== SZ is True
-- fromSing $ SS SZ %:== SS SZ is True
-- fromSing $ SS %:== SS (doesn't compile because it's applied to too few arguments)
```
I can't think of any reason for `Sing n -> Sing ('S n)` to not be sufficiently typed to solve this. Even if we were to add another constructor that took a Nat as a value then it'd produce a different singleton type like `Sing n -> Sing ('Val n)`. Is there some way to get this equality?

Edit: I noticed I'm also on 1.1.2.1 as it's what's packaged with stackage, so I apologize if this is already a thing that works.

**Comment by vladfi1** [comment]
Comparing functions for equality generally isn't possible in Haskell. The reason for your error is that ```%:==``` can only compare Sing values, not functions:

```haskell
(%:==) :: SEq 'KProxy => Sing a -> Sing b -> Sing (a :== b)
```

The type of ```SS``` is, as you note, a function, which can never be of type ```Sing t```.

**Comment by goldfirere** [comment]
@vladfi1 is right. You may also find `singFun1` useful if you want to consider functions as singletons. Closing the ticket, but if there is a concrete improvement you can see here (including in documentation) please do reopen. Thanks!
