### ISSUE TITLE
Question: What will change with GHC 8?

### ISSUE THREAD

**Issue by tel** [goldfirere/singletons#138]
Given that GHC 8 offers some significant new functionality with regard to Haskell's dependently typed programming story, I'm curious if there are resources to understand better how `singletons` will be able to take advantage of these features and potentially expand functionality or smooth out some sharp edges. Is there any resource which documents plans for GHC 8?

**Comment by goldfirere** [comment]
I actually think that not much in `singletons` will change with GHC 8. We can avoid using kind proxies, which is nice. Some experiments say that we might be able to significantly simplify the treatment of functions. But maybe not.

There is no document describing expected changes to `singletons`. There will be, in the next week or so, a better description of what's in GHC 8 with these features. Right now, your best resource is https://ghc.haskell.org/trac/ghc/wiki/DependentHaskell/Phase1

**Comment by tel** [comment]
Great, thanks!

**Comment by goldfirere** [comment]
Seems this issue is handled, then.
