### ISSUE TITLE
Working with type literals

### ISSUE THREAD

**Issue by tel** [goldfirere/singletons#139]
Right now the best solution I know for working type literals involves some significant and strange overhead. In particular, in [`Serv`](https://github.com/tel/serv) I'm using singletons heavily to create types to form API descriptions, but since these use all of type level naturals, type level symbols, and the star type these data descriptions get pretty... ugly.

The core example is the [`Api` type](https://github.com/tel/serv/blob/feat-status-codes/src/Serv/Internal/Api.hs). 

```haskell
singletons
  [d|
    data Api nat symbol star where
      Endpoint :: star -> [Handler nat symbol star] -> Api nat symbol star
      OneOf :: [Api nat symbol star] -> Api nat symbol star
      Raw :: Api nat symbol star
      (:>) :: Path symbol star -> Api nat symbol star -> Api nat symbol star
  |]
```

Is this the recommended way to use type literals? Is there another way of constructing types of this form?

**Comment by goldfirere** [comment]
Do you need to use the unrefined type at all? That is, do you ever have values of type `Api`? Or only values of type `SApi` and types of kind `Api`? I assume you don't need to unrefined type. Then, you can just use `Nat` and `Symbol` instead of parameterizing over them. There's no easy solution for `*`, though.

**Comment by tel** [comment]
I do actually refer to the unrefined type from time to time. [Here's an example.](https://github.com/tel/serv/blob/feat-status-codes/src/Serv/Internal/StatusCode.hs#L166) The idea here is that I need to get the actual code number out of the type, so I can capture it with something like `codeNum (fromSing (sing :: Sing status))` but perhaps that's an inefficient way to achieve this end?

**Comment by goldfirere** [comment]
I'm a bit lost in your example, as the link doesn't seem to point to a use of `Api`. In any case, there isn't a great story around singletons and TypeLits stored in data structures. In my opinion, GHC's whole treatment of TypeLits needs an overhaul. In the meantime, a solution to #82 would make your use case better, but I have no plans to implement that in the near future.

**Comment by tel** [comment]
Ah, sorry, yeah. It's a type used by Api which is why the Api type needs to pass the `nat` type variable down. It's probably possible to write a version of this which doesn't require going through the unrefined type, but it'd require some typeclass trickery instead of nicer, simpler functions and calls to `fromSing`.

**Comment by tel** [comment]
If I go the route of never working with the unrefined type, do I need to use something other than `singletons` to derive the singletons? I seem to be running into relatively inscrutable errors in first passes.

**Comment by goldfirere** [comment]
You can't ever truly avoid the unrefined type, for two reasons:
1. The singletons definitions needs the promoted unrefined type. And there's no way to have a promoted type without the regular one.
2. Template Haskell runs after renaming. So for the names to be in scope when GHC is reading in quotes, you need to have the unrefined definitions in scope.

I've lost track of this one. (Sorry, I'm very squeezed for time right now!) Is there a task remaining to be done here? Thanks.

**Comment by tel** [comment]
I think it is resolved as the issue stands. 

I have one outstanding question which I can try to phrase as "if one does not with to use the unrefined types at all and wishes to use `Symbol` and `Nat` in their promoted types, how can one best generate these types?"

In an example, if I wish to have a kind like

    data Status = Custom Nat | Ok | NoContent | NotFound

and I'm never going to use values of type `Status`, how can I generate the singletons?

    singletons [d| data Status = Custom Nat | Ok | NoContent | NotFound |]

seems like it should work, but it does not with the following errors

```
/Users/tel/Dropbox/proj/serv/src/Test.hs:62:1: Warning:
    Couldn't match type ‘Integer’ with ‘Nat’
    Expected type: DemoteRep 'KProxy
      Actual type: Nat
    In the first argument of ‘toSing’, namely ‘b_aALK’
    In the expression: toSing b_aALK :: SomeSing (KProxy :: KProxy Nat)

/Users/tel/Dropbox/proj/serv/src/Test.hs:62:1: Warning:
    Couldn't match type ‘Integer’ with ‘Nat’
    Expected type: Nat
      Actual type: DemoteRep 'KProxy
    In the first argument of ‘Custom’, namely ‘fromSing b_aALJ’
    In the expression: Custom (fromSing b_aALJ)
```

But perhaps this is documented somewhere or better left to another question issue.

**Comment by goldfirere** [comment]
Just seeing this now -- sorry, I guess I missed your last question.

The bottom line is that you can't do this, currently. Your best way forward is to have

```
singletons [d| data Status' n = Custom n | Ok | ... |]
type Status = Status' Nat   -- will also work in kinds in GHC 8
type SStatus = Sing Status
```

It's a bit annoying, but there's no cleaner workaround I'm aware of. Of course, this could be done by the library; it's just not implemented.

Given that you've described the issue as handled. I'm closing. But do please reopen if I've missed something!
