### ISSUE TITLE
Can't build with GHC 8.0

### ISSUE THREAD

**Issue by int-index** [goldfirere/singletons#140]
relocated from https://github.com/goldfirere/ghc/issues/54

**Comment by christiaanb** [comment]
See also `singletons` #142, and `th-desugar` [#38](https://github.com/goldfirere/th-desugar/pull/38)

**Comment by deepfire** [comment]
See `th-desugar` https://github.com/goldfirere/th-desugar/issues/39

**Comment by goldfirere** [comment]
Fixed now.
