### ISSUE TITLE
Planned fundamental changes pending new GHC-8.0 features?

### ISSUE THREAD

**Issue by mstksg** [goldfirere/singletons#141]
Hi, just wanted to first say thanks for maintaining such an awesome library :)

I'm going to be writing a series of posts that will involve `singletons`, and I was wondering if there were any planned major changes to the API etc. pending new GHC 8.0 features like TypeApplications and extensions like TypeInType, promotable GADTs's, etc.

Will the normal "day-to-day" usage of the library be mostly the same, or will 8.0's new things allow for some nice simplifications/cleaning up in the current API?  Are there any major *possibilities* of potential cleaner things based on the new features?

Thanks again!

**Comment by int-index** [comment]
https://github.com/goldfirere/singletons/issues/138

**Comment by goldfirere** [comment]
Yes, #138 tells the story. There are opportunities for simplification (such as the end of kind-proxies), but my time constraints mean that these won't make it in for 8.0. So the next version should have the same API as previously. However, because GHC is more powerful now, GADTs, etc., should, hopefully, Just Work with singletons.

Thanks for blogging about it! That's such a useful resource for aspiring dependently typed Haskell programmers.

**Comment by mstksg** [comment]
thanks for the prompt response! 

Regarding these opportunities (in particular, eliminating kind proxies) , do you have a description of a general plan of how you would want that to look? I might have the time to go through and implement some of the grunt/busy work if you want :)

**Comment by goldfirere** [comment]
I see two main opportunities for improvement:
* Eliminate kind proxies. For example, `SingKind` takes a kind proxy, which is obsolete in 8.0, as you can define a kind class directly. This would require changing both the definition of `SingKind` and the TH that generates instances.
* Make `Sing` an injective type family instead of a data family. In some cases (`*`, `->`), it would be much better to have a singleton be some already-existing type, rather than something new. The reason it's a data family today is to get injectivity, but we don't need that workaround anymore.

I'd be very happy to accept pull requests around these!

**Comment by mstksg** [comment]
Hm, regarding the second point -- the TH should now generate new data types in the normal case, when special behavior isn't desired, right?

I always sort of felt that an advantage of making it a data family was not polluting the namespace with `SingBool` when you could use `Sing Bool`.

But, looking at how the library is already defined, `SBool` etc. are already defined type synonyms anyways, so, I'm guessing the intended behavior for TH singletons/convention-comforming singletons would be:

~~~
data Bool = False | True

-- generates:
data SBool = SFalse | STrue
type instance Sing Bool = SBool
-- etc.
~~~
 
?

**Comment by goldfirere** [comment]
Yes. That's right.

Except that it's `type instance Sing = SBool`. The `Bool` parameter is invisible, but its existence will prevent that instance from overlapping with others. To be clear, I was thinking of defining `Sing` like

```
type family Sing = (r :: k -> *) | r -> k
```

I've experimented with this definition, and it works nicely.

**Comment by mstksg** [comment]
I guess I'm not yet familiar enough with the new injective type families, but for:

    type instance Sing = SBool
    type instance Sing = SOrdering

would this be used as:

    Sing True :: SBool   -- ?

But, what part of that definition would prevent:

    Sing EQ :: SBool

?  How are `SBool` and the promoted `Bool` supposed to be associated?

**Comment by int-index** [comment]
@mstksg `Sing 'True` doesn't make any sense (neither with the old definition of `Sing` nor the proposed one).

You'lle have something like this instead:

```
data Bool = True | False

data SBool :: Bool -> Type where
  STrue :: SBool 'True
  SFalse :: SBool 'False

type instance Sing = SBool
```

When you write `Sing = SBool`, you're instantiating `k` with `Bool` and `r` with `SBool`.

Similarly for `Ordering`:

```
data Ordering = LT | EQ | GT

data SOrdering :: Ordering -> Type where
  SLT :: SOrdering 'LT
  SEQ :: SOrdering 'EQ
  SGT :: SOrdering 'GT

type instance Sing = SOrdering
```

Now we can have `STrue :: Sing` and `SEQ :: Sing`. Notice how the types *seem* identical, but aren't! In the first case `k = Bool`, in the second case `k = Ordering`, so it's different instances of `Sing`.

**Comment by mstksg** [comment]
hm, I'm under the impression that `Sing 'True` is the type of `STrue`, the singleton for `'True :: Bool`, in the old definition of `Sing`:

~~~
> :kind! Sing 'True
Sing 'True :: *
> case sing :: Sing' True of STrue -> putStrLn "hello"
hello
~~~

Isn't this how `Sing` currently works?

But, I do see the difference for the new system.  I'll start playing around with it, thanks for explaining!

**Comment by mstksg** [comment]
Playing around with this on ghci and I'm getting some behavior that I'm having some problems reconciling:

~~~
> type family Sing = (r :: k -> *) | r -> k
> data SBool :: Bool -> Type where
~~~

**Comment by int-index** [comment]
> hm, I'm under the impression that `Sing 'True` is the type of `STrue`

Right, I was a little confused myself. Sorry for confusing you too. `Sing 'True :: STrue` makes perfect sense.

> Which seems to be slightly different than what you're describing?

Well, I played around with it in GHCi as well and can confirm that my description does not fit what is actually happening. The `k` parameter is implicit, but `r` is obviously not, so we need to pass it, thus `STrue :: Sing 'True` and `SEQ :: Sing 'EQ`.

**Comment by int-index** [comment]
Here's an ASCII drawing to make it more clear:

```
kinds | Type       | Type
--------------------------------
types | Sing 'True | Sing 'False
--------------------------------
terms | STrue      | SFalse
```

Where `types ~ kinds`, of course, since we have `TypeInType`.

**Comment by mstksg** [comment]
Right, makes sense...I think before, I had forgotten that even in the original version, `SBool` is declared GADT-style, so the association is made explicit just by the kind of `SBool` in the first place.

Thanks for your help.  Hope it's okay if I use this issue to discuss other things I run into along the way?

**Comment by goldfirere** [comment]
Yes, please do! It looks like this confusion has resolved itself, but please continue to ask questions as they come up.

**Comment by goldfirere** [comment]
It doesn't look like this Issue is pulling its weight at the moment, though I'm happy to answer more questions.
