### ISSUE TITLE
SSym not exported

### ISSUE THREAD

**Issue by andrewthad** [goldfirere/singletons#143]
I could be mistaken, but I think that `SSym` (the data constructor for the `Symbol` singleton), is not exported.

**Comment by andrewthad** [comment]
I have a branch (of `singleton-2.0.1` since I don't have GHC-8) with the extra exports here: https://github.com/andrewthad/singletons/tree/export_ssym_ghc_710

**Comment by goldfirere** [comment]
This non-export is intentional, as the `SSym` constructor is unsafe. It would allow you to build `SSym "foo" :: Sing "bar"`. I could see exporting it from a `Data.Singletons.Unsafe` module, though.

What are you trying to do that wants the `SSym` constructor?

**Comment by andrewthad** [comment]
The example of an unsafe construction you provided does not typecheck. The `SSym` data constructor doesn't take a `String` argument. Rather, the `String` is given implicitly by the `KnownSymbol` constraint, so to my understanding, it is not unsafe.

As for what I'm doing, I'm playing around with using `singletons` to do routing/dispatch for websites. The relevant file is [here](https://github.com/andrewthad/serpentine/blob/eb25f6742e2d2873e6e090b5c2462fd5644a87b3/src/Serpentine/Playground.hs). I have a type representing a route piece (unusable at the value level):

    data Piece x = Static Symbol | Capture x

Using the `$(singletons [...])` splice on this will fail because of the `Symbol <-> String` issue when it tries to build the `DemoteRep` instance, but I can just [manually define what the TH would have produced](https://github.com/andrewthad/serpentine/blob/eb25f6742e2d2873e6e090b5c2462fd5644a87b3/src/Serpentine/Playground.hs#L25-L32):

    type StaticSym1 s = 'Static s
    type CaptureSym1 x = 'Capture x
    
    data StaticSym0 :: (TyFun Symbol (Piece k) -> *)
    type instance Apply StaticSym0 s = StaticSym1 s
    
    data CaptureSym0 :: (TyFun k (Piece k) -> *)
    type instance Apply CaptureSym0 s = CaptureSym1 s

And then I can just write singletonized functions that work on this type in the usual way.

I need to pattern match on `SSym` for route rendering. I need to get the `KnownSymbol` constraint in scope so that I can get the `String` that goes in the rendered url path.

**Comment by goldfirere** [comment]
Yes, you're right. That's what I get for not checking the code before posting!

I agree this is safe. Fix on the way.
