### ISSUE TITLE
Question about definition of Sing

### ISSUE THREAD

**Issue by mitchellwrosen** [goldfirere/singletons#153]
Hi, `Sing` is described as a "kind-idexed" data family, and I'm wondering why it's defined as

```haskell
data family Sing (a :: k) :: Type

data instance Sing (a :: Maybe k) where
  SNothing :: Sing Nothing
  SJust    :: Sing k -> Sing (Just k)
```

rather than

```haskell
data family Sing k :: k -> Type

data instance Sing (Maybe k) x where
  SNothing :: Sing (Maybe k) Nothing
  SJust    :: Sing k a -> Sing (Maybe k) (Just a)
```

Are these effectively the same type?

**Comment by goldfirere** [comment]
Yes, these are effectively the same. The difference is that in my version, the kind parameter `k` is invisible and inferred automatically. In your version, that kind parameter must be supplied by the user at every use site. In many cases, though, the kind parameter is easily inferrable from the type argument.

Another reason for the current design is that your approach was impossible before GHC 8, and most of this library has not been updated to take advantage of new, GHC 8 features.

If this answer satisfies you, please close the ticket. Thanks!

**Comment by mitchellwrosen** [comment]
Ah, makes sense!

Just for fun, I decided to replace some of the simple machinery in `Data.Singletons` with this alternate version of `Sing` and friends, and I did come across an odd case where type inference differs:

```haskell
foo :: Int
foo = withSomeSing (Just True) $ \s ->
  case s of
    SJust STrue  -> 0
    SJust SFalse -> 1
    SNothing     -> 2
```

This fails with a big horrendous type error about untouchable variables, but I _thought_ the gist of it was that `k` is ambiguous because `DemoteRep` is not injective, so passing `Just Bool` does not tell GHC that I want `k ~ Maybe Bool`. 

Yet, calling 

```haskell
withSomeSing @(Maybe Bool) (Just True) $ \s -> ...
``` 

does not fix the untouchable error! I had to explicitly say what the kind of the tag of `s` is, even though GHC _should_ know this, I think, because in the callback function, `k` is a free variable (`forall (a::k). Sing a -> r`).

```haskell
withSomeSing (Just True) $ \(s :: Sing (a :: Maybe Bool)) -> ... -- works
```

However, with the `Sing` given above, my original solution type checked:

```haskell
-- using: data family Sing k (a :: k)
withSomeSing @(Maybe Bool) (Just True) $ \s -> ... -- works
```

Odd. Anyways, thanks!

**Comment by int-index** [comment]
While trying to debug the issue I've discovered another gruesome error:

```
Prelude> import Data.Singletons
Prelude Data.Singletons> :t withSomeSing

<interactive>:1:1: error:
    No instance for (SingKind *) arising from a use of ‘it’
```

That's `GHCi, version 8.0.1` with `singletons-2.2`.

**Comment by mitchellwrosen** [comment]
You've got to set TypeInType :)

**Comment by int-index** [comment]
That fixed it but the error message is misleading. Thanks!

**Comment by int-index** [comment]
Ok I've fixed it, wait for a PR.

**Comment by goldfirere** [comment]
Thanks all!
