### ISSUE TITLE
Defunctionalised Constraint symbols

### ISSUE THREAD

**Issue by christiaanb** [goldfirere/singletons#155]
I was in need of:

```
import GHC.Exts (Constraint)
import GHC.TypeLits (KnownNat, Nat)

data KnownNatSym0 (f :: TyFun Nat Constraint) :: *
type instance Apply KnownNatSym0 n = KnownNat n
```

Would it be possible to add this symbol, and perhaps other symbols for defunctionalised constraints, in a next version of Singletons?
I could write a patch myself, but I wouldn't know in what particular module you would like them.

**Comment by goldfirere** [comment]
You can always do this by
```
$(genDefunSymbols [''KnownNat, ''KnownSymbol])
```
but I agree these should be in the library, in `Data.Singletons.TypeLits`. If you write a PR, I'll take it, but I'm happy to do this myself in a little while, too.
