### ISSUE TITLE
Question about TyFun

### ISSUE THREAD

**Issue by sheyll** [goldfirere/singletons#156]
Why is `TyFun` defined as:

    data TyFun :: * -> * -> *

instead of 

    type TyFun' a b = a -> b

It Seems that:

    type family IsTheSame (a :: t) (b :: t') :: Bool where
        IsTheSame a a = 'True
        IsTheSame a b = 'False

    xxx :: IsTheSame (TyFun a b) (TyFun' a b) ~ 'True => ()
    xxx = ()

so why is TyFun defined using `data ...` ?

**Comment by goldfirere** [comment]
We need functions created using `TyFun` to be distinct from functions created just from `->`, as they are applied differently and have different type inference characteristics.

But I'm confused a bit by your example toward the bottom: `TyFun a b` and `TyFun' a b` are different, as `IsTheSame` should verify. Your `xxx` is just a value that makes an inconsistent assumption. GHC can't quite figure out that the assumption is inconsistent, but the fact that it accepts `xxx = ()` does not mean that `IsTheSame` is returning `True`.

**Comment by sheyll** [comment]
Thanks for the clarification!

This might not be the best place to ask, but regarding my example, how could I force GHC to test the assumption? 

Also I did not want to post an _issue_, I just could not set the `is-question` label.

**Comment by goldfirere** [comment]
You can use GHCi's `:kind!` command. Try this:

```
> :kind! forall a b. IsTheSame (TyFun a b) (TyFun' a b)
```

**Comment by sheyll** [comment]
Wow, cool thanks, I didn't know that. 

Sorry to keep bugging you :) 
If I really actually wanted the compiler to  type check this, could I force GHC to have a closer look?

**Comment by goldfirere** [comment]
I think this should do it (building on your example above):

```
yyy :: ()
yyy = xxx
```

There are no assumptions in `yyy` so GHC will have to satisfy all assumptions to `xxx`. It won't be able to, in your case, and issue an error. The one problem here is that you may be required to specify concrete `a` and `b`.

Happy to help. :)

**Comment by sheyll** [comment]
Oh greate, thanks alot! 
That saves the day.. (actually the night I hope)
