### ISSUE TITLE
A path for proper fixity for SCons and a (%:)?

### ISSUE THREAD

**Issue by mstksg** [goldfirere/singletons#157]
Currently, working with `Sing [a]` is a bit un-ideal because the fixity of `SCons` is the default `infixl 9`, which gives awkward association for typical usage of `(:)` (which requires `infixr`).  In fact, the [example in the documentation][1] doesn't compile -- it needs to be

    STrue `SCons` (SFalse `SCons` SNil)

And the parentheses are required.

I've tried playing around with declarations and TH in *Data.Singletons.Name* and *Data.Singletons.Prelude.Instances*, but I couldn't get it to work because GHC won't let me declare a fixity declaration for a name not declared in the file...but I thought the TH declared it?  A part of it is my own unfamiliarity with Template Haskell :)  If it's possible, I'd be willing to look into it if I knew where to start :)

It also wouldn't be too awful to have an equivalent non-constructor Cons, `%:`, something like

    (%:) :: Sing a -> Sing as -> Sing (a ': as)
    (%:) = SCons

but I think there are some other type families that usually would get generated with functions like these...and I can't seem to find a way to declare it using `singletonsOnly`, because `(:)` can't be used as a function name.  Is this possible to do while leveraging the TH for uniformity, or these need to all be declared manually?

Thanks for your time!

[1]: http://hackage.haskell.org/package/singletons-2.2/docs/Data-Singletons.html#v:singFun1

**Comment by goldfirere** [comment]
Template Haskell has some interesting rules around top-level splices and other declarations, meaning that the fixity needs to go *between* the two top-level splices in `Data.Singletons.Prelude.Instances`.

Thanks for this suggestion -- it's a definite oversight.

**Comment by int-index** [comment]
Are you sure that your fix works! I tried doing the same and the fixity is ignored, it seems.

**Comment by int-index** [comment]
I tried a more automated approach:

```
From e83e485b3047fc60b932b8fd127e57a68ef53273 Mon Sep 17 00:00:00 2001
From: Index Int <vlad.z.4096@gmail.com>
Date: Tue, 30 Aug 2016 20:09:24 +0300
Subject: [PATCH] Auto-generate infix declarations

---
 src/Data/Singletons/Prelude/Instances.hs |  3 +--
 src/Data/Singletons/Single.hs            | 10 ++++++++++
 2 files changed, 11 insertions(+), 2 deletions(-)

diff --git a/src/Data/Singletons/Prelude/Instances.hs b/src/Data/Singletons/Prelude/Instances.hs
index edd23e6..94d9afd 100644
--- a/src/Data/Singletons/Prelude/Instances.hs
+++ b/src/Data/Singletons/Prelude/Instances.hs
@@ -20,8 +20,7 @@ import Data.Singletons.Util
 
 -- some useful singletons
 $(genSingletons basicTypes)
-infixr 5 `SCons`
-
+$(singFixityDeclarations basicTypes)
 $(singDecideInstances basicTypes)
 
 -- basic definitions we need right away
diff --git a/src/Data/Singletons/Single.hs b/src/Data/Singletons/Single.hs
index 97c7324..1a38b2d 100644
--- a/src/Data/Singletons/Single.hs
+++ b/src/Data/Singletons/Single.hs
@@ -362,6 +362,16 @@ singInfixDecl fixity name
     DInfixD fixity (singDataConName name)
   | otherwise = DInfixD fixity (singValName name)
 
+singFixityDeclaration :: DsMonad q => Name -> q [Dec]
+singFixityDeclaration name = do
+  mFixity <- qReifyFixity name
+  return $ case mFixity of
+    Nothing     -> []
+    Just fixity -> decToTH . DLetDec $ singInfixDecl fixity name
+
+singFixityDeclarations :: DsMonad q => [Name] -> q [Dec]
+singFixityDeclarations = concatMapM singFixityDeclaration
+
 singTySig :: Map Name ALetDecRHS  -- definitions
           -> Map Name DType       -- type signatures
           -> Name -> DType   -- the type is the promoted type, not the type sig!
-- 
2.5.0
```

`-ddump-splices` shows that the same `infixr 5 SCons` is generated in the same place, and yet it doesn't work. What might be the reason?

**Comment by int-index** [comment]
or maybe it doesn't get generated:

```
src/Data/Singletons/Prelude/Instances.hs:23:3-35: Splicing declarations
    singFixityDeclarations basicTypes ======>
```

and I'm really confused now, because I was sure it did.

**Comment by int-index** [comment]
Probably not worth wasting the time, since the issue is fixed now.

**Comment by goldfirere** [comment]
A generated fixity declaration would have to be in the same top-level splice as the other bits, so this would have to be a change to the `genSingletons` machinery. It probably is a worthwhile improvement...

**Comment by int-index** [comment]
I'll take a closer look then.
