### ISSUE TITLE
type abbreviations in template haskell

### ISSUE THREAD

**Issue by sweirich** [goldfirere/singletons#178]
I would like to say:

```
$(singletons [d|
    
  -- Note: Ord automatically defines "max"
  data Occ = Str | Opt | Many deriving (Eq, Ord, Show)

   type U = [(Symbol,Occ)]

  empty :: U
  empty = []
  |])
```

Instead of breaking up the TH into two separate calls, with the type abbreviation between them.

```
$(singletons [d|
    
  -- Note: Ord automatically defines "max"
  data Occ = Str | Opt | Many deriving (Eq, Ord, Show)

  |])

type U = [(Symbol,Occ)]

$(singletons [d|

  empty :: U
  empty = []
  |])
```

**Comment by goldfirere** [comment]
Does this mean you should also get

```
type SU = forall (a :: [(Symbol, Occ)]). Sing a
```

?

That seems like it doesn't compose the right way with other definitions though. Or are you proposing just to ignore the type synonym instead of erroring?

**Comment by sweirich** [comment]
Just ignore the type synonym. 

Or define 

type SU (u :: U) = Sing(u :: [(Symbol,Occ)])

(which is not the same as what you wrote... right?)

**Comment by goldfirere** [comment]
Of course. Yes, your definition is right; mine is just plain wrong.

Yes, that's a fine idea.
