### ISSUE TITLE
Error with promotion fields for sum types

### ISSUE THREAD

**Issue by odr** [goldfirere/singletons#180]
When I write
```
promote [d|
  data X = X1 {y :: Symbol} | X2 {y :: Symbol}
  z (X1 x) = x
  z (X2 x) = x
  |]
```
I expect that Y and Z are similar. But now definition for Y is wrong:

```
:i Y
type family Y (a0 :: X) :: Symbol
  where [(field0 :: Symbol)] Y ('X2 field0) = field0
:i Z
type family Z (a0 :: X) :: Symbol
  where
    [(x0 :: Symbol)] Z ('X1 x0) = x0
    [(x0 :: Symbol)] Z ('X2 x0) = x0
```
 That is on [stack lts-8.0](https://www.stackage.org/lts-8.0/package/singletons-2.2)

**Comment by goldfirere** [comment]
Well-spotted. Yes, it seems that `singletons` doesn't consider the possibility that a record selector is used in multiple different constructors. I'm happy to review a PR before then, but I'm afraid you can't expect a fix before summertime. During this semester, time is extraordinarily precious!
