### ISSUE TITLE
Singletonize pattern signatures

### ISSUE THREAD

**Issue by goldfirere** [goldfirere/singletons#183]
It would be nice if we could single

```
f (x :: Maybe Bool) = ...
```

or even

```
f (x :: Maybe a) = ...
```

where the latter binds a scoped type variable. Alas, this is not so easy, because of two features of GHC:

1. A scoped type variable must be just that, a variable. For example, consider this:

    ```
    g x = case Just x of
      (Just y :: Maybe Bool) -> y
    ```

    The natural singletonization is

    ```
    sG :: Sing x -> Sing (G x)
    sG sx = case SJust sx of
      (SJust sy :: Sing (blah :: Maybe Bool)) -> sy
    ```

    The problem is that GHC complains that `blah` should really be `Just xyz`. It won't *bind* `blah` to be `Just xyz` as a different design would do.

2. The alternative is to write the promoted version of the pattern instead of `blah`. But this doesn't work because GHC checks a pattern signature *before* checking the pattern itself. Consider

    ```
    f (Just a :: Maybe Bool) = "hi"
    ```

    If we singletonize to

    ```
    sF :: Sing x -> Sing (F x)
    sF (SJust sa :: Sing (Just a :: Maybe Bool)) = (sing :: Sing "hi")
    ```

    GHC complains that we don't yet know that the type `x` is `Just a`. We would need to do a pattern match without a signature and then do a `case` with a signature, to get the ordering right.

One escape hatch here is to use a `_` in place of `blah`. Of course, this requires `-XPartialTypeSignatures`, and even then, it emits a warning. We could ask users to disable this warning, but that just seems wrong. And no one is asking for this, anyway. So I give up for now. But if I ever return to this problem, I think the way forward is to do something like

```
sF x@(SJust sa) = case x of
  (_ :: Sing (Just a :: Maybe Bool)) -> sing :: Sing "hi"
```

as the singletonization of `f`, above. Yuck. But doable. And no yuckier than lots of other yuck in `singletons`.

**Comment by RyanGlScott** [comment]
That last option:

```haskell
sF x@(SJust sa) = case x of
  (_ :: Sing (Just a :: Maybe Bool)) -> sing :: Sing "hi"
```

Sounds like the way forward, as gross as it may be. I'm finding myself having to perform [similar pattern acrobatics](https://github.com/RyanGlScott/eliminators/blob/4bffc594037252a5010096a93c893feffe69f7ce/tests/GADTSpec.hs#L46-L58) in my `eliminators` library in order to bring existentially quantified type variables from GADT return types into scope.
