### ISSUE TITLE
Offer at least one induction principle for Nat

### ISSUE THREAD

**Issue by treeowl** [goldfirere/singletons#193]
It's certainly possible to cobble together an induction principle for `Nat` based on what's offered here (and either a type checker plugin or `unsafeCoerce`), but I think it would be convenient to offer one or two directly. Something generally like

```haskell
induction1 :: forall p n. p 0 -> (forall k. Sing k -> p k -> p (k :+ 1)) -> Sing n -> p n
induction2 :: forall p n. (forall k. (forall j. j < k => Sing j -> p j) -> Sing k -> p k) -> Sing n -> p n
```

**Comment by goldfirere** [comment]
My first reaction is that this feels outside the purview of singletons. Others can argue against me on this, but I'd rather see this in a library built on top of singletons.

**Comment by RyanGlScott** [comment]
I agree with @goldfirere. As you mentioned, it's quite simple to define these functions in one's own library, and there's too many questions about the color of the bikeshed (e.g., should we use `induction1` or `induction2`, should `p` be of kind `Nat -> Type` or `Nat ~> Type`, etc) to make me want to put this in `singletons`.

**Comment by RyanGlScott** [comment]
FWIW, I have something [akin to `induction1`](http://hackage.haskell.org/package/eliminators-0.1/docs/Data-Eliminator.html#v:elimNat) in my [`eliminators`](hackage.haskell.org/package/eliminators) package. I'll close this ticket, since it's out of the scope of `singletons` itself.
