### ISSUE TITLE
Add Div, Mod, DivMod to Singletons.Prelude

### ISSUE THREAD

**Issue by vagarenko** [goldfirere/singletons#195]
Could you add Div, Mod, DivMod type families to Singletons.Prelude for a time being until https://ghc.haskell.org/trac/ghc/ticket/13652 is resolved?
You already use them internally.

**Comment by goldfirere** [comment]
These seem like they would belong in `Data.Singletons.TypeLits`, but, yes, I'm fine with that. Care to submit a PR?

**Comment by vagarenko** [comment]
> Care to submit a PR?
I will

**Comment by LeanderK** [comment]
a quick question: what is the performance of these types and is there a way (maybe even a hack by abusing template-haskell?) to improve it? I would guess the performance is not good, but how bad exactly? I am thinking about creating a library that would probably depend a lot on Div and has to deal with larger integers (i expect 1024 or greater to be common, i expect Div to scale linearly with the size of the integers), will it still be usable?

**Comment by RyanGlScott** [comment]
> what is the performance of these types

Certainly not great. As a quick data point, I tried compiling this file:

```haskell
{-# LANGUAGE DataKinds #-}
{-# LANGUAGE TypeApplications #-}
{-# LANGUAGE TypeOperators #-}
module Main (main) where

import Data.Proxy (Proxy(..))
import Data.Singletons.TypeLits (Div)
import GHC.TypeNats (natVal)

main :: IO ()
main = print $ natVal $ Proxy @(4096 `Div` 2)
```

```
$ time ghc -fforce-recomp -O2 Foo.hs -freduction-depth=0
[1 of 1] Compiling Main             ( Foo.hs, Foo.o )
Linking Foo ...

real    0m1.617s
user    0m1.388s
sys     0m0.064s
```

I think the most surefire way to make it faster is to implement [Trac #13652](https://ghc.haskell.org/trac/ghc/ticket/13652)—that is, put `Div` and friends into `base`, and make them use machine operations when reducing. If you're interested in implementing this, one of us would be happy to advise you.

**Comment by LeanderK** [comment]
ok, well this is worse than i thought. I might actually be interested in implementing this, but it all depends whether i get the funding to start the project that would be depending on fast type-level Div, Mod, DivMod etc. Thank you, I will shoot you an email if that's the case, but it can take a while for things to sort out.

**Comment by goldfirere** [comment]
Just to clarify: are you worried about compile times or run times? Compile times may be hard to fix, but a little sprinkling of `unsafeCoerce` may provide a way to improve the run times.

**Comment by LeanderK** [comment]
i am unfortunately worried about the compile-times

**Comment by LeanderK** [comment]
I had unfortunately never the chance to really delve into ghc, so I may be wrong, but would it be possible to speed this up via a clever use of a type-checker plugin?

**Comment by goldfirere** [comment]
Yes, a plugin might help... but I think using a plugin here would mean that every client of these functions needs to use the plugin. If I'm right here, then I wouldn't want the dependency on a plugin within singletons. However, you can duplicate the `Div`, etc., design in your own modules and then write the plugin to speed it up...

**Comment by LeanderK** [comment]
Of course, this is the worst solution usability-wise. It's more about coding a prototype and quickly experimenting with code that heavily depends on type-level arithmetic (including div) without having to implement (Trac #13652)[https://ghc.haskell.org/trac/ghc/ticket/13652] first. If everything goes well it's possible that I can take a shot at solving it (if there is an agreement how it should look like), but working on GHC (for the first time!) seems like a task I would not underestimate.

**Comment by RyanGlScott** [comment]
In case you haven't heard of it yet, I'll throw in a plug for [`ghc-typelits-extra`](http://hackage.haskell.org/package/ghc-typelits-extra), a GHC typechecker plugin which provides a (different) type-level [`Div`](http://hackage.haskell.org/package/ghc-typelits-extra-0.2.3/docs/GHC-TypeLits-Extra.html#t:Div) and [`Mod`](http://hackage.haskell.org/package/ghc-typelits-extra-0.2.3/docs/GHC-TypeLits-Extra.html#t:Mod) that reduces via machine instructions under the hood.

**Comment by LeanderK** [comment]
well, this is fantastic and seems to solve the problem for the time being! Thank you, I will have a closer look into tomorrow 🙂
