### ISSUE TITLE
How to deal with associated type families

### ISSUE THREAD

**Issue by RyanGlScott** [goldfirere/singletons#198]
Let's say I have a class with an associated type family:

```haskell
class IsList l where
  type Item l
  fromList :: [Item l] -> l
  toList   :: l -> [Item l]
```

Trying to feed this to `singletons` fails pretty early:

```
Bug.hs:13:3: error:
    Only method declarations can be promoted within a class.
   |
13 | $(singletons [d|
   |   ^^^^^^^^^^^^^^...
```

But need it fail? There appears to be a sensible way to promote and single `IsList`:

```haskell
{-# LANGUAGE ScopedTypeVariables #-}
{-# LANGUAGE TypeFamilies #-}
{-# LANGUAGE TypeInType #-}
{-# LANGUAGE TypeOperators #-}
{-# LANGUAGE UndecidableInstances #-}
module IsList where

import Data.Kind
import Data.List.NonEmpty (NonEmpty(..))
import Data.Singletons.Prelude.List.NonEmpty (Sing(..))
import Data.Singletons.Prelude

-----
-- Original class
-----

class IsList l where
  type Item l
  fromList :: [Item l] -> l
  toList   :: l -> [Item l]

-----
-- Promoted/singled version
-----

class PIsList (l :: Type) where
  type FromList (a :: [Item l]) :: l
  type ToList   (a :: l)        :: [Item l]

class SIsList l where
  sFromList :: forall (a :: [Item l]). Sing a -> Sing (FromList a :: l)
  sToList   :: forall (a :: l).        Sing a -> Sing (ToList a)

-----
-- Example instance
-----

instance IsList (NonEmpty a) where
  type Item (NonEmpty a) = a
  fromList (x:xs)   = x :| xs
  fromList []       = error "empty list"
  toList ~(x :| xs) = x:xs

instance PIsList (NonEmpty a) where
  type FromList (x:xs)  = x :| xs
  type FromList '[]     = Error "empty list"
  type ToList (x :| xs) = x:xs

instance SIsList (NonEmpty a) where
  sFromList (SCons x xs) = x :%| xs
  sFromList SNil         = sError (sing :: Sing "empty list")
  sToList (x :%| xs)     = SCons x xs
```

That is, promoting and singling leaves `Item` unaffected. This should work similarly for top-level type families as well.

**Comment by goldfirere** [comment]
Looks plausible. Go for it. :)

**Comment by RyanGlScott** [comment]
Darn, I knew it wouldn't be that easy. If you try to promote this, you'll run into problems with type families pretty quickly. Here's a subset of generated code which illustrates the issue:

```haskell
{-# LANGUAGE ExistentialQuantification #-}                                                
{-# LANGUAGE ScopedTypeVariables #-}                                                      
{-# LANGUAGE TypeApplications #-}                                                         
{-# LANGUAGE TypeFamilies #-}                                                             
{-# LANGUAGE TypeInType #-}                                                               
{-# LANGUAGE UndecidableInstances #-}                                                     
module Bug where                                                                          
                                                                                          
import Data.Kind                                                                          
import Data.Singletons                                                                    
                                                                                          
class IsList (l :: Type) where                                                            
  type Item l                                                                             
  toList :: l -> [Item l]                                                                 
                                                                                          
type ToListSym1 (x :: l) = ToList x                                                       
                                                                                          
data ToListSym0 (x :: TyFun l [Item l])                                                   
  = forall arg. SameKind (Apply ToListSym0 arg) (ToListSym1 arg) =>
    ToListSym0KindInference

type instance Apply ToListSym0 x = ToList x

class PIsList (l :: Type) where
  type ToList (arg :: l) :: [Item l]
```
```
GHCi, version 8.2.0.20170523: http://www.haskell.org/ghc/  :? for help
Loaded GHCi configuration from /home/rgscott/.ghci
[1 of 1] Compiling Bug              ( Bug.hs, interpreted )

Bug.hs:22:15: error:
    • Illegal type synonym family application in instance: [Item l]
    • In the type instance declaration for ‘Apply’
   |
22 | type instance Apply ToListSym0 x = ToList x
   |               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

If you squint past that vague error message, you'll come to the horrifying realization that matching on `ToListSym0` also implicitly matches on its kind, which mentions `[Item l]`. Matching on other type families within a type family equation is strictly forbidden, alas.

**Comment by goldfirere** [comment]
This is a GHC infelicity, one which I hope to remedy this summer. I don't know if there's a specific ticket for it, though.

**Comment by int-index** [comment]
Is this the same issue as https://ghc.haskell.org/trac/ghc/ticket/12564 or not?

**Comment by RyanGlScott** [comment]
That looks like just the ticket.

It appears that we're blocked here, so I'll let this sit for now.

**Comment by goldfirere** [comment]
Yes about GHC#12564.

**Comment by RyanGlScott** [comment]
While we cannot promote any function types that mention type families due to [Trac #12564](https://ghc.haskell.org/trac/ghc/ticket/12564), we could at the very least allow promotion of type families in general. After all, there is a use case for doing so: it would be convenient to have TH [generate defunctionalization symbols for type families in `$(singletons [d| ... |])` blocks](https://github.com/goldfirere/singletons/issues/313), without having to go through the extra step of calling `genDefunSymbols`.

Of course, allowing for type families to be promoted does present the opportunity to shoot oneself in the foot by trying to use in a function type, such as in [`toList` above](https://github.com/goldfirere/singletons/issues/198#issuecomment-308626145). But this is certainly not the only infelicity that's present in `singletons`—they're documented in the [Known bugs section of the `README`](https://github.com/goldfirere/singletons/tree/21777c5755e10d539a1ea884454c6654993d38e2#known-bugs), after all—so I'd argue that this is an acceptable price to pay.

Plus, if we did allow this, that would effectively "fix" this bug. We'd still be blocked on Trac #12564 itself being fixed, but once that happened, then one would be able to promote classes like `IsList` without any additional changes on `singletons`' side.
