### ISSUE TITLE
No Haddocks for singletons-2.3 on Hackage

### ISSUE THREAD

**Issue by RyanGlScott** [goldfirere/singletons#201]
See http://hackage.haskell.org/package/singletons-2.3.

Obviously, Hackage can't build the Haddocks on its own yet, since it's still using GHC 8.0. But it's quite possible to manually upload the documentation oneself using:

```
cabal haddock --for-hackage
cabal upload dist/<...>.tar.gz --documentation
```

I'd do this myself, but I don't have Hackage permissions for `singletons`.

**Comment by goldfirere** [comment]
I'm happy to let you do this. :)

What's your Hackage username?

**Comment by RyanGlScott** [comment]
ryanglscott

**Comment by goldfirere** [comment]
OK -- done.

**Comment by RyanGlScott** [comment]
I've uploaded the documentation for `singletons-2.3` manually.
