### ISSUE TITLE
Generate Show instances for every Sing instance

### ISSUE THREAD

**Issue by RyanGlScott** [goldfirere/singletons#208]
#179 added custom `Show` instances for `SNat` and `SSym` (as well as `SomeSing Nat` and `SomeSing Symbol`). These are incredibly helpful for debugging purposes. I only wish there were more `Show` instances for other `Sing` instances!

Let's make this happen. I propose generating two additional declarations for each `Sing` instance ('ll use `[]` as an example):

1. Generate a `Show` instance for the `Sing` type. For instance:

   ```haskell
   instance (Show (Demote a), SingKind a, Typeable a) => Show (Sing (x :: [a])) where
     showsPrec p SNil
       = showParen (p > 10)
         ( showString "SNil"
           . showString " @"
           . showsPrec 11 (typeOf (undefined :: a))
         )
     showsPrec p (SCons x xs)
       = showParen (p > 10)
         ( showString "SCons"
           . showString " @"
           . showsPrec 11 (typeOf (undefined :: a))
           . showString " @"
           . showsPrec 11 (fromSing x)
           . showString " @"
           . showsPrec 11 (fromSing xs)
         )
   ```

   Note that coming up with the instance context would be very similar to that of `SingKind` instances, except we must also use additional `Show (Demote a)` and `Typeable a` constraints.

   Example usages (assuming we live in a post-#206 world):

   ```
   λ> SCons @Nat @0 @'[] sing sing
   SCons @Nat @0 @[]
   λ> SCons @[Nat] @'[0] @'[] sing sing
   SCons @[Nat] @[0] @[]
   ```
2. Derive the corresponding `Show` instance for `SomeSing`. For instance:

   ```haskell
   deriving instance (Show (Demote a), SingKind a, Typeable a) => Show (SomeSing [a])
   ```

**Comment by RyanGlScott** [comment]
I realize that the `Show (Sing (x :: [a]))` instance is a little unsavory, since it doesn't show the `Sing` values containing within `SCons`. But I don't think there's any way to express the constraint you'd need for that without the use of [`QuantifiedContexts`](https://ghc.haskell.org/trac/ghc/ticket/2256):

```haskell
instance (Show (Demote a), SingKind a, Typeable a,
          forall z. Show (Sing (z :: a)))
  => Show (Sing (x :: [a])) where
```

So if we restrict ourselves to just `Show`, the example I gave above is the best we can do.

Alternatively, if we come up with our own variant of `Show`, we could get what we want:

```haskell
class ShowSing k where
  showSing :: Int -> Sing (a :: k) -> ShowS

instance ShowSing a => ShowSing [a] where
  showSing p SNil
    = showParen (p > 10)
      ( showString "SNil"
        . showString " @"
        . showsPrec 11 (typeOf (undefined :: a))
      )
  showSing p (SCons x xs)
    = showParen (p > 10)
      ( showString "SCons"
        . showString " @"
        . showsPrec 11 (typeOf (undefined :: a))
        . showString " @"
        . showsPrec 11 (fromSing x)
        . showString " @"
        . showsPrec 11 (fromSing xs)
        . showChar ' '
        . showSing 11 x
        . showChar ' '
        . showSing 11 xs
      )
instance ShowSing a => Show (SList (x :: [a])) where
  showsPrec = showSing
deriving instance ShowSing a => Show (SomeSing [a])
```
```
λ> SCons @Nat @0 @'[] sing sing
SCons @Nat @0 @[] (SNat @0) (SNil @Nat)
λ> SCons @[Nat] @'[0] @'[] sing sing
SCons @[Nat] @[0] @[] (SCons @Nat @0 @[] (SNat @0) (SNil @Nat)) (SNil @[Nat])
```

To be honest, I think I like this approach better. What do you think?

**Comment by RyanGlScott** [comment]
It might also be worthwhile to augment `showSing` with a flag that toggles whether or not to print all the visible type applications, since they can be pretty noisy.

**Comment by goldfirere** [comment]
I'm confused by the final GHCi session above. If there is `Show` instance for `SomeSing`, why would GHCi use that instance for a `Sing ...`? Or am I missing something.

Yes, I like the `ShowSing` approach much more. And I'd just drop the type applications entirely, but you have more experience than me and might disagree.

**Comment by RyanGlScott** [comment]
Sorry, that comment was heavily edited, and I seem to have butchered the order in which I meant to present things. Those outputs would be for `Sing`s, not `SomeSing`s (for the `SomeSing` output, just imagine it was wrapped in `SomeSing (...)`.

> And I'd just drop the type applications entirely, but you have more experience than me and might disagree.

I don't feel too strongly here, but there is somewhat of a precedent here, since #179 introduced the convention. There are times when they're useful, and times when they're not... perhaps it would be best to support both?

**Comment by goldfirere** [comment]
Yes, but #179 absolutely needs to have the visible type application; otherwise, we can't tell what number the singleton is for. I don't think that problem happens elsewhere.

In any case, I really don't feel strongly at all, so you're free to implement as you like here.

**Comment by RyanGlScott** [comment]
Ah, I see what you mean. `SNat` and `SSym` are the only two singleton constructors to date where the constructor name doesn't uniquely determine the type constructor `T` in the return type `Sing (T t_1 ... t_n)`, so you pretty much need VTA to disambiguate it.

In that case, I'd be happy to leave out the VTA business for other `ShowSing` instances. That would also allow me to share a lot of the code from `Data.Singletons.Derive.Show`, which would be swell, and it would avoid thorny issues like VTA for infix singleton constructors ([GHC Trac #12363](https://ghc.haskell.org/trac/ghc/ticket/12363)) or singleton constructors with records ([GHC Trac #13853](https://ghc.haskell.org/trac/ghc/ticket/13853)).
