### ISSUE TITLE
Implement DeriveAnyClass, and make deriving strategy detection smarter

### ISSUE THREAD

**Issue by RyanGlScott** [goldfirere/singletons#209]
Currently, you can only derive classes with the stock strategy. There's currently a comment to this effect in [the source code](https://github.com/goldfirere/singletons/blob/d02b290765cea5a4126ff0480b732d1f6c9f8ee4/src/Data/Singletons/Partition.hs#L159-L166):

```haskell
isStock :: Maybe DerivStrategy -> Bool
isStock Nothing = True -- We assume the lack of an explicit deriving strategy to
                       -- indicate defaulting to stock. In reality, GHC's defaulting
                       -- behavior is much more complex than this, but implementing
                       -- this in singletons would be impossible, as that would require
                       -- detecting the presence of extensions.
isStock (Just StockStrategy) = True
isStock (Just _) = False
```

I now realize that this comment is wrong. We _do_ have the ability to query the currently enabled language extensions via `qExtsEnabled`. With this, we could certainly detect the presence of, say, `DeriveAnyClass`, and emulate [GHC's deriving strategy resolution algorithm](https://ghc.haskell.org/trac/ghc/wiki/Commentary/Compiler/DerivingStrategies#Thederivingstrategyresolutionalgorithm) in `singletons`.

Thinking more about what other strategies besides `stock` we could implement, I believe the only other feasible strategy is `anyclass`, since `newtype` deriving isn't possible in a `singletons` context (at least, not the `coerce`-based incarnation of it).

**Comment by goldfirere** [comment]
If you really need to, go ahead with this, but I try to keep `singletons` out of the "inferring" business. In this case, the algorithm is likely straightforward (if fiddly), but still.

**Comment by RyanGlScott** [comment]
Hm, now that you mention it, it would probably be best to avoid emulating that strategy inference algorithm - not only because I dislike it, but because it would be possible for GHC and `singletons` to infer two different things:

```haskell
{-# LANGUAGE GeneralizedNewtypeDeriving #-}
newtype Age = MkAge Int deriving Num
```

GHC would default to the `newtype` strategy, but since `singletons` doesn't support GND, it would default to the `anyclass` strategy. Bleugh.

How about we only use `DeriveAnyClass` if the user explicitly requests it with the `anyclass` keyword + `DerivingStrategies`. That way, there's no surprises or inconsistency between GHC and `singletons`. (If a user tries using the `newtype` strategy keyword in `singletons`, it'd be a warning saying that it's not supported.)

**Comment by goldfirere** [comment]
Yes. And perhaps a note in our README of how `singletons` infers the strategy (which is different from GHC). Thanks. :)
