### ISSUE TITLE
Revise the "my brain just exploded" check

### ISSUE THREAD

**Issue by RyanGlScott** [goldfirere/singletons#210]
Currently, `singletons` [attempts to prevent you](https://github.com/goldfirere/singletons/blob/aa01b459bcbee9e07b6d2f219a93963777a42c78/src/Data/Singletons/Single.hs#L466-L471) from generating code which might trigger GHC's infamous ["my brain just exploded"](http://git.haskell.org/ghc.git/blob/d86420021ffd35e8f09216364d65bd1d18581731:/compiler/typecheck/TcPat.hs#l1168) error message. This check is useful in GHC 8.0:

```
> let SJust x = t in x

<interactive>:5:5: error:
    * My brain just exploded
      I can't handle pattern bindings for existential or GADT data constructors.
      Instead, use a case-expression, or do-notation, to unpack the constructor.
    * In the pattern: SJust x
      In a pattern binding: SJust x = t
      In the expression: let SJust x = t in x
```

But it's less useful in GHC 8.2, since the [brain-explosion check has been removed](http://git.haskell.org/ghc.git/commit/15b9bf4ba4ab47e6809bf2b3b36ec16e502aea72). Indeed, the code above now works in 8.2:

```
> let SJust x = t in x

<interactive>:6:1: error:
    * No instance for (Show (Sing 'False))
        arising from a use of `print'
    * In a stmt of an interactive GHCi command: print it
```

(OK, I lied. That doesn't _quite_ work because we don't yet have a `Show` instance for `SBool`, but [we're working on that...](https://github.com/goldfirere/singletons/issues/208))

We should see if we can remove the brain-explosion check on `singletons`' side, or at the very least give a more pertinent error message.

**Comment by RyanGlScott** [comment]
That being said, I'm not sure how to actually trigger the `singletons` version of the brain-exploded error in practice, since it's quite smart at desugaring `let` expressions in other things...

**Comment by goldfirere** [comment]
It may indeed be impossible to trigger. I seem to recall that it was triggered unnecessarily in the past, and so I changed either th-desugar or singletons to work around this. But the details are no longer in my head, unfortunately.
