### ISSUE TITLE
Implement toSing for (~>)

### ISSUE THREAD

**Issue by RyanGlScott** [goldfirere/singletons#214]
After toying around with [Justin Le's verified version of the `Functor` typeclass](https://blog.jle.im/entry/verified-instances-in-haskell.html), I wanted to try out this convoluted definition of `fmap`:

```haskell
{-# LANGUAGE ScopedTypeVariables #-}
{-# LANGUAGE TypeFamilies #-}
{-# LANGUAGE TypeInType #-}
{-# LANGUAGE TypeOperators #-}
{-# LANGUAGE UndecidableInstances #-}
module Bug where

import Data.Singletons.Prelude
import Prelude hiding (Functor(..))

class Functor f where
    type Fmap a b (g :: a ~> b) (x :: f a) :: f b

    sFmap
        :: Sing (g            :: a ~> b)
        -> Sing (x            :: f a   )
        -> Sing (Fmap a b g x :: f b   )

instance Functor [] where
    type Fmap a b g x = Map g x
    sFmap = sMap

fmap :: (SingKind a, SingKind b, SingKind (f a), SingKind (f b), Functor f)
     => (Demote a -> Demote b) -> Demote (f a) -> Demote (f b)
fmap f x = withSomeSing f $ \sF ->
             withSomeSing x $ \sX ->
               fromSing (sFmap sF sX)

main :: IO ()
main = print $ fmap not [True, False]
```

But:

```
$ /opt/ghc/8.2.1/bin/runghc Bug.hs
Bug.hs: Cannot create existentially-quantified singleton functions.
CallStack (from HasCallStack):
  error, called at src/Data/Singletons.hs:210:14 in singletons-2.3-JXZMZqhKweIL1B7HrQTXDn:Data.Singletons
```

Darn. That's because the [implementation of `toSing`](https://github.com/goldfirere/singletons/blob/349a56667071a962ff45e0a1440daefae8f384d9/src/Data/Singletons.hs#L207-L210) in the `SingKind` instance for `k1 ~> k2` is left undefined:

```haskell
instance (SingKind k1, SingKind k2) => SingKind (k1 ~> k2) where
  type Demote (k1 ~> k2) = Demote k1 -> Demote k2
  fromSing sFun x = withSomeSing x (fromSing . applySing sFun)
  toSing _ = error "Cannot create existentially-quantified singleton functions."
```

I believe we _could_ implement `toSing`, provided that we're willing to put up with some `unsafeCoerce` shenanigans. What about this implementation?

```haskell
instance (SingKind k1, SingKind k2) => SingKind (k1 ~> k2) where
  type Demote (k1 ~> k2) = Demote k1 -> Demote k2
  fromSing sFun x = withSomeSing x (fromSing . applySing sFun)
  toSing f = SomeSing slam
    where
      slam :: forall (f :: k1 ~> k2). Sing f
      slam = singFun1 @f lam
        where
          lam :: forall (t :: k1). Sing t -> Sing (f @@ t)
          lam x = case toSing (f (fromSing x)) of
                    SomeSing s -> unsafeCoerce s
```

Annoyingly, we have to use `unsafeCoerce` to massage the existentially quantified `Sing` to be of type `Sing (f @@ t)`. But I think this is pretty much unavoidable here, since we can't know anything about the `Apply` instance that might be used to reduce `f @@ t`, so we have to rely on the term-level function `f` to do the right thing.

Experimentally, this seems to work with `fmap` as defined above:

```
λ> fmap not [True, False]
[False,True]
λ> fmap not []
[]
λ> fmap isJust [Just (), Nothing]
[True,False]
```

**Comment by goldfirere** [comment]
This looks plausible. Can it be abused? I can't wrap my head all the way around it right now...

**Comment by RyanGlScott** [comment]
> Can it be abused?

My hypothesis is: assuming `k1` and `k2` have well behaved `SingKind` instances, then this instance shouldn't go astray. By "well behaved", I mean that it satisfies the following laws:

```
toSing . fromSing = SomeSing
(\x -> withSomeSing x fromSing) = id
```

If we had a non-well behaved instance like this:

```haskell
data instance Sing (z :: Bool) where
  SFalse :: Sing False
  STrue  :: Sing True

instance SingKind Bool where
  type Demote Bool = Bool
  fromSing SFalse = False
  fromSing STrue  = True
  toSing   False  = SomeSing STrue
  toSing   True   = SomeSing STrue
```

Then we'd get surprising results like `fmap not [False, True] = [True, True]`. Still much better than segfaulting, though!

**Comment by goldfirere** [comment]
Your example is a straightforward "garbage in; garbage out" kind of flaw -- very acceptable. If you think no segfaults are possible, go for it.

And, document those fine laws for `SingKind`! :)
