### ISSUE TITLE
Eq and Ord instances for SomeSing

### ISSUE THREAD

**Issue by RyanGlScott** [goldfirere/singletons#215]
In the vein of @andrewthad's [`pringletons`](http://hackage.haskell.org/package/pringletons) library, I'd like to write `Eq` and `Ord` instances for `SomeSing`:

```haskell
instance SEq k => Eq (SomeSing k) where
  SomeSing a == SomeSing b = fromSing (a %:== b)

instance SOrd k => Ord (SomeSing k) where
  SomeSing a `compare` SomeSing b = fromSing (a `sCompare` b)
```

This is useful, for instance, for storing `SomeSing`s in `Map`s.

There's one problem with this idea: it's difficult to add these instances as non-orphans. We can't simply add them to `Data.Singletons`, as that would create import cycles with `Data.Singletons.Prelude.Eq` and `Data.Singletons.Prelude.Ord`. One solution is to add `Data.Singletons.Prelude.Eq.Internal` and `Data.Singletons.Prelude.Ord.Internal` modules to break the import cycles (which is something that probably needs to be done anyway, since a similar problem arose in https://github.com/goldfirere/singletons/issues/212).

**Comment by goldfirere** [comment]
By all means go ahead. I'm not terribly bothered by orphans, as they're very hard to avoid given the structure of `singletons`. You'll see that several other modules have orphan instances, too.

(That said, I do avoid them where possible. But don't lose sleep over this.)
