### ISSUE TITLE
genDefunSymbols doesn't play nicely with TypeInType

### ISSUE THREAD

**Issue by RyanGlScott** [goldfirere/singletons#216]
`genDefunSymbols` doesn't take dependent quantification into account. Here's a simple example:

```haskell
{-# LANGUAGE ExistentialQuantification #-}
{-# LANGUAGE TemplateHaskell #-}
{-# LANGUAGE TypeInType #-}
{-# LANGUAGE TypeFamilies #-}
{-# LANGUAGE TypeOperators #-}
module Bug where

import Data.Singletons.TH

type MyProxy k (a :: k) = Proxy a
$(genDefunSymbols [ ''MyProxy ])
```
```
$ /opt/ghc/8.2.1/bin/ghci Bug.hs -ddump-splices
GHCi, version 8.2.0.20170623: http://www.haskell.org/ghc/  :? for help
Loaded GHCi configuration from /home/ryanglscott/.ghci
[1 of 1] Compiling Bug              ( Bug.hs, interpreted )
Bug.hs:11:3-31: Splicing declarations
    genDefunSymbols [''MyProxy]
  ======>
    type MyProxySym2 (t_a6m5 :: GHC.Types.Type) (t_a6m6 :: k6989586621679023539) =
        MyProxy t_a6m5 t_a6m6
    instance SuppressUnusedWarnings MyProxySym1 where
      suppressUnusedWarnings _
        = snd ((GHC.Tuple.(,) MyProxySym1KindInference) GHC.Tuple.())
    data MyProxySym1 (l_a6m8 :: GHC.Types.Type) l_a6m7
      = forall arg_a6m9. SameKind (Apply (MyProxySym1 l_a6m8) arg_a6m9) (MyProxySym2 l_a6m8 arg_a6m9) =>
        MyProxySym1KindInference
    type instance Apply (MyProxySym1 l_a6m8) l_a6m7 = MyProxy l_a6m8 l_a6m7
    instance SuppressUnusedWarnings MyProxySym0 where
      suppressUnusedWarnings _
        = snd ((GHC.Tuple.(,) MyProxySym0KindInference) GHC.Tuple.())
    data MyProxySym0 l_a6ma
      = forall arg_a6mb. SameKind (Apply MyProxySym0 arg_a6mb) (MyProxySym1 arg_a6mb) =>
        MyProxySym0KindInference
    type instance Apply MyProxySym0 l_a6ma = MyProxySym1 l_a6ma

Bug.hs:11:3: error:
    • Invalid declaration for ‘MyProxySym2’; you must explicitly
      declare which variables are dependent on which others.
      Inferred variable kinds:
        t_a6m5 :: *
        t_a6m6 :: t
    • In the type synonym declaration for ‘MyProxySym2’
   |
11 | $(genDefunSymbols [ ''MyProxy ])
   |   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

One can manually work around this by patching up the kinds of `MyProxySym2` (and `MyProxySym1`) like so:

```haskell
data MyProxySym2 (t_a6m5 :: Type) (t_a6m6 :: t_a6m5)
data MyProxySym1 (l_a6m8 :: Type) (l_a6m7 :: TyFun l_a6m8 Type)
```

In addition, that `instance SuppressUnusedWarnings MyProxySym1` won't kind-check either due to [GHC Trac #13909](https://ghc.haskell.org/trac/ghc/ticket/13909). One can hack around this by adding an extra argument:

```haskell
instance SuppressUnusedWarnings (MyProxySym1 l)
```

(This is fine, since we're just using this instance to suppress warnings for the kind-inference data constructor `MyProxySym1KindInference` anyways.)

**Comment by RyanGlScott** [comment]
A more complicated example (and the place where I actually stumbled upon this issue in practice) is a type family for representing the symmetry of propositional equality:

```haskell
{-# LANGUAGE ExistentialQuantification #-}
{-# LANGUAGE TemplateHaskell #-}
{-# LANGUAGE TypeInType #-}
{-# LANGUAGE TypeFamilies #-}
{-# LANGUAGE TypeOperators #-}
module Bug where

import Data.Singletons.TH

type Symmetry (a :: t) (y :: t) (e :: a :~: y) = y :~: a
$(genDefunSymbols [ ''Symmetry ])
```
```
$ /opt/ghc/8.2.1/bin/ghci Bug.hs -ddump-splices
GHCi, version 8.2.0.20170623: http://www.haskell.org/ghc/  :? for help
Loaded GHCi configuration from /home/ryanglscott/.ghci
[1 of 1] Compiling Bug              ( Bug.hs, interpreted )
Bug.hs:11:3-32: Splicing declarations
    genDefunSymbols [''Symmetry]
  ======>
    type SymmetrySym3 (t_a6q7 :: t6989586621679023539) (t_a6q8 :: t6989586621679023539) (t_a6q9 :: (:~:) a6989586621679023540 y6989586621679023541) =
        Symmetry t_a6q7 t_a6q8 t_a6q9
    instance SuppressUnusedWarnings SymmetrySym2 where
      suppressUnusedWarnings _
        = snd ((GHC.Tuple.(,) SymmetrySym2KindInference) GHC.Tuple.())
    data SymmetrySym2 (l_a6qb :: t6989586621679023539) (l_a6qc :: t6989586621679023539) l_a6qa
      = forall arg_a6qd. SameKind (Apply (SymmetrySym2 l_a6qb l_a6qc) arg_a6qd) (SymmetrySym3 l_a6qb l_a6qc arg_a6qd) =>
        SymmetrySym2KindInference
    type instance Apply (SymmetrySym2 l_a6qb l_a6qc) l_a6qa = Symmetry l_a6qb l_a6qc l_a6qa
    instance SuppressUnusedWarnings SymmetrySym1 where
      suppressUnusedWarnings _
        = snd ((GHC.Tuple.(,) SymmetrySym1KindInference) GHC.Tuple.())
    data SymmetrySym1 (l_a6qf :: t6989586621679023539) l_a6qe
      = forall arg_a6qg. SameKind (Apply (SymmetrySym1 l_a6qf) arg_a6qg) (SymmetrySym2 l_a6qf arg_a6qg) =>
        SymmetrySym1KindInference
    type instance Apply (SymmetrySym1 l_a6qf) l_a6qe = SymmetrySym2 l_a6qf l_a6qe
    instance SuppressUnusedWarnings SymmetrySym0 where
      suppressUnusedWarnings _
        = snd ((GHC.Tuple.(,) SymmetrySym0KindInference) GHC.Tuple.())
    data SymmetrySym0 l_a6qh
      = forall arg_a6qi. SameKind (Apply SymmetrySym0 arg_a6qi) (SymmetrySym1 arg_a6qi) =>
        SymmetrySym0KindInference
    type instance Apply SymmetrySym0 l_a6qh = SymmetrySym1 l_a6qh

Bug.hs:11:3: error:
    • Invalid declaration for ‘SymmetrySym3’; you must explicitly
      declare which variables are dependent on which others.
      Inferred variable kinds:
        t6989586621679023539 :: *
        t_a6q7 :: t6989586621679023539
        t_a6q8 :: t6989586621679023539
        t_a6q9 :: t :~: t1
    • In the type synonym declaration for ‘SymmetrySym3’
   |
11 | $(genDefunSymbols [ ''Symmetry ])
   |   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

**Comment by goldfirere** [comment]
At first glance, these look like relatively straightforward bugs -- bugs which I don't have time right now to fix. If you're stuck on this, however, let me know. Thanks!

**Comment by RyanGlScott** [comment]
I took a crack at this last night, but alas, this proved to trickier than I though. Here's the problem: we're trying to come up with this defunctionalized type:

```haskell
data MyProxySym1 (k :: Type) (x :: TyFun k Type)
```

Except that currently, we're coming up with this instead:

```haskell
data MyProxySym1 (k :: Type) x
```

Why isn't `genDefunSymbols` coming up with the kind of `x`? That's because the kind of `x` is built with:

```haskell
buildTyFun_maybe :: Maybe DKind -> Maybe DKind -> Maybe DKind
```

That is, in order for `buildTyFun_maybe ki1 ki2` to return `Just (TyFun k Type)`, both `ki1` and `ki2` must be `Just`. In this case, `ki1` is `Just k`, since we learn what `k` is from the earlier tyvar binder. But what about `ki2`? We'd like to think that it'd obviously be `Just Type`. But unfortunately, it's `Nothing`.

The reason `ki2` is `Nothing` is because `ki2` comes from the return kind of the declaration we're defunctionalizing--in this case, `MyProxy`:

```haskell
type MyProxy k (a :: k) = Proxy a
```

The fact that `MyProxy` is a type synonym is a problem, because its reified Template Haskell AST doesn't tell you what is result kind is! See [this line of code](https://github.com/goldfirere/singletons/blob/58c66080c2e5264bb62c607525682e4553fb5d6e/src/Data/Singletons/Promote/Defun.hs#L47). Since `singletons` chooses not to perform kind inference, it defaults to `Nothing` and hopes that GHC's kind inference can do the job after `MyProxySym1` is spliced in (which, unfortunately, it can't).

I honestly have no idea how you'd work around this problem. My idea was to try and give an explicit kind annotation like this:

```haskell
type MyProxy k (a :: k) = (Proxy a :: Type)
```

And then from `genDefunSymbols`, look if the RHS has an outermost `SigT`, and if so, use _that_ as `ki2`. Alas, this doesn't work when `MyProxy` is reified:

```
λ> type MyProxy k (a :: k) = (Proxy a :: Type)
λ> $(reify ''MyProxy >>= stringE . pprint)
"type Ghci7.MyProxy (k_0 :: *) (a_1 :: k_0) = Data.Proxy.Proxy a_1"
```

I had some other crazy ideas for making this work, but neither of them panned out:

* Use `PartialTypeSignatures` to force GHC to infer the `_` in `data MyProxySym1 (k :: Type) (x :: TyFun k _)`. Sadly, GHC doesn't let you use wildcard types in data declarations.
* Abuse `KindOf` and create something like `data MyProxySym1 (k :: Type) (x :: TyFun k (KindOf (MyProxy k a))`. Alas, this doesn't work either, since GHC will also complain about dependency order:
   ```
    • These kind and type variables: k
                                     (x :: TyFun k (KindOf (MyProxy k a)))
      are out of dependency order. Perhaps try this ordering:
        k (a :: k) (x :: TyFun k (KindOf (MyProxy k a)))
      NB: Implicitly declared kind variables are put first.
    • In the data type declaration for ‘MyProxySym1’
   ```

So I'm out of ideas.

**Comment by RyanGlScott** [comment]
Well, to be clear, I'm out of ideas for making `MyProxy` work _as a type synonym_. If you define it as a type family:

```haskell
type family MyProxy (k :: Type) (a :: k) :: Type where
  MyProxy k (a :: k) = Proxy a
```

Then `singletons` is able to figure out that the return kind is `Type`, and all is well.

If defunctionalizing `MyProxy` as a type synonym is untenable, then I suppose we could throw an error message if any of a type synonyms tyvar binders are dependent, and recommend redefining the type synonym as a single-equation closed type family as a workaround.

**Comment by RyanGlScott** [comment]
Another bump in the road: when defunctionalizing `Symmetry`, you end up with something like this:

```haskell
data SymmetrySym0 (whargarbl :: TyFun t (TyFun t (TyFun ((:~:) a y) Type -> Type) -> Type))
```

About which GHC complains:

```
    You have written a *complete user-suppled kind signature*,
    but the following variable is undetermined: k0 :: *
    Perhaps add a kind signature.
    Inferred kinds of user-written variables:
      t :: *
      a :: k0
      y :: k0
      whargarbl0 :: TyFun
                      t
                      (TyFun
                         t
                         (TyFun (a :~: y) * -> *)
                       -> *)
```

What went wrong here? It turns out that the type variables `a` and `y` wound up in the `TyFun` part, something which wasn't happening before, and because `a` and `y` aren't explicitly quantified, GHC gets confused. The workaround would be to instead write `SymmetrySym0` like this:

```haskell
data SymmetrySym0 :: forall (a :: t) (y :: t). TyFun t (TyFun t (TyFun ((:~:) a y) Type -> Type) -> Type)
```

However, building such a datatype (with a `forall` in the return kind) is currently impossible with `th-desugar`, since [this](https://github.com/goldfirere/th-desugar/blob/31afa2c2ea6d8a15dbd286e5d4d868497c7df011/Language/Haskell/TH/Desugar/Core.hs#L120) is the API that `DDataD` has:

```haskell
| DDataD NewOrData DCxt Name [DTyVarBndr] [DCon] [DDerivClause]
```

Notice that this is missing the return kind that [`DataD`](http://hackage.haskell.org/package/template-haskell-2.12.0.0/docs/Language-Haskell-TH-Syntax.html#t:Dec) from `template-haskell` has:

```haskell
| DataD Cxt Name [TyVarBndr] (Maybe Kind) [Con] [DerivClause]
```

So we'll likely need to patch `th-desugar` to support this.

**Comment by goldfirere** [comment]
Now I understand better your motivation for goldfirere/th-desugar#65.

My thought on all this is to resist pushing too hard in this direction for now. It's going to be an uphill slog through a swamp filled with brambles, mostly because of CUSKs. So, I would wait for ghc-proposals/ghc-proposals#54. Of course, that will be long in coming, so I'd understand if you're inpatient and want to start your slog earlier.

**Comment by RyanGlScott** [comment]
Actually, now that I think about this some more, this doesn't require goldfirere/th-desugar#65 at all. In fact, I can just as well write this:

```haskell
data SymmetrySym0 (whargarbl :: TyFun t (TyFun t (TyFun ((:~:) (a :: k) (y :: k)) Type -> Type) -> Type))
```

And now GHC won't complain about CUSKs. Hooray!

(The only reason I generated `SymmetrySym0` without explicit kind signatures for `a` and `y` in the first place is because of some code in `Defun` that stripped away the kind signatures. But I shouldn't do so here.)

I'm still confident I can make this work without altering CUSK inference behavior. I won't be able to make this work for type synonyms at the moment, but c'est la vie. I can wait until after ghc-proposals/ghc-proposals#54 to add full support for type synonyms.

**Comment by RyanGlScott** [comment]
...well, we _could_ make this work in `singletons` current state. But perhaps it would be unwieldy—we'd have to go through, find every occurrence of `a` or `y`, and sprinkle a kind signature on it.

What would be much nicer is to write it like this:

```haskell
data SymmetrySym0 :: forall (t :: Type) (a :: t) (y :: t). t ~> t ~> a :~: y
```

This also has a CUSK, but this time, we only needed to annotate the `forall`'d variables with kinds.

So I change my mind: I'll say that this is blocked on https://github.com/goldfirere/th-desugar/pull/74 being merged.

**Comment by RyanGlScott** [comment]
https://github.com/goldfirere/singletons/pull/319 implements this.
