### ISSUE TITLE
Figure out a way to cache the Travis build

### ISSUE THREAD

**Issue by RyanGlScott** [goldfirere/singletons#225]
Currently, the Travis CI job for `singletons` rebuilds all of its dependencies, every time. This makes me immensely sad.

Unfortunately, actually making Travis cache the dependencies is easier said than done. The thorn in our side is the need to install `th-desugar` from a submodule separately from all other dependencies. The usual Travis script that caches Hackage dependencies, however, calculates whether dependencies have changed or not with this command:

```bash
$ cabal install --only-dependencies --enable-tests --enable-benchmarks --dry -v > installplan.txt
```

You can't just throw `th-desugar` in there, since it doesn't play nicely with `--only-dependencies` and `--enable-tests`.

The proper solution would be to switch over to a `.travis.yml` file that uses `cabal new-build` (i.e., the approach [here](https://github.com/hvr/multi-ghc-travis/blob/800980d76f7a74f3cdfd76b3dff351d52d2c84ee/.travis.yml)). But migrating over to `cabal new-build` comes with its own set of problems, as the `singletons` test suite is designed with some "old-build" assumptions in mind. Namely,

1. It assumes that a file named `"../dist/build/autogen/cabal_macros.h"` exists. This assumption doesn't hold under `cabal new-build`.
2. It assumes that you're either using the global package database or one from a sandbox. `cabal new-build` organizes its own package databases, however.

@hvr had some ideas for porting the test suite over. Some possibilities:

1. Use a `Setup.hs` script to determine the right paths for `cabal_macros.h`/package databases. (I'm not especially eager to do this, since `Setup.hs` scripts come with their own problems.)
2. Augment `Paths_singletons` with the necessary information. This would require waiting for some number of `Cabal` releases, but it would likely be a clean solution.

**Comment by ezyang** [comment]
I think if you take an approach similar to how cabal-testsuite goes about doing it, you might be able to handle the "invoke GHC to run tests" pattern (because this is exactly what cabal-testsuite does.) The key is that using the Cabal library and the path to the `dist` directory (which can be passed by hand or inferred from the path of the test executable), you can pull out all of the other information you need to do it. In cabal-testsuite, it loads in via https://github.com/haskell/cabal/blob/master/cabal-testsuite/Test/Cabal/Monad.hs (`--builddir` into `testArgDistDir`), and then we load the config with `getPersistBuildConfig` and then use values from the `lbi` to do the rest of our business. Of particular interest is the `withPackageDB` field. Let me know if you have other questions.

**Comment by RyanGlScott** [comment]
Now that we're depending on GHC 8.4, this has become a more pressing issue, as `singletons`' dependencies on Hackage don't all support 8.4 yet.

@goldfirere, should I try to push on this before a `singletons-2.4` release? Or do you think we should release now and push on the CI infrastructure later?

**Comment by goldfirere** [comment]
We can test locally, so there's no hard reason not to release. The testing infrastructure of `singletons` needs major attention, and I'm afraid I don't have the attention to offer. The immediate problem (no CI) will dissolve after another month or so, as Hackage gets updated, so it's not strictly necessary to do this work.

What I'm trying to say is: yes we can release (are we ready now?) and we should try to fix the testing infrastructure only if you feel like doing so. :) But you don't have to. If you do look at it, see if you can parallelize en route. Thanks!

**Comment by RyanGlScott** [comment]
I certainly can't promise I can deliver anything before POPL, but I would be willing to give this a shot when I get a chance (i.e., after I update all of the other libraries I maintain to support GHC 8.4.). I'm confident that pestering the good folks on the `#ghc` IRC channel enough will help me figure out what to do :)

> are we ready now?

I'd say so. Go for it!

> But you don't have to. If you do look at it, see if you can parallelize en route.

Referring to https://github.com/goldfirere/singletons/issues/123, I presume? @ezyang, do you know if the `Cabal` test suite has similar problems with parallelism and test dependencies?

**Comment by ezyang** [comment]
I'm not sure what you are asking about. cabal-testsuite runs tests in parallel but I grew that infrastructure from scratch. You are welcome to try to repurpose it for your uses.

**Comment by RyanGlScott** [comment]
I've been digging into this recently, and one drawback that I didn't anticipate is that the technique that `Cabal`'s test suite is using apparently requires the use of a [`Custom` build type](https://github.com/haskell/cabal/blob/67276f870a55e6a913b98ef7b2ca22a8def21a6e/cabal-testsuite/cabal-testsuite.cabal#L15). I'm hesistant to foist this requirement on all `singletons` users just for the sake of testing, so perhaps it would be worthwhile to split off the test suite into a separate package (similarly to how `Cabal` and `cabal-testsuite` are different packages).

**Comment by RyanGlScott** [comment]
Upon further thought, I think I'm going to abandon the idea of trying to use the `Cabal` library to do this. The complexity it adds to the test suite is massive, and there are enough tradeoffs involved to the point where it makes me nervous.

A much, much simpler approach is to simply invoke `cabal new-exec ghc -- <opts>` instead of `ghc -this-unit-id singletons -i<path-to-build-files> <opts>`. `cabal new-exec` manages all of the store paths and package information for you, which is wonderful. This does come at the downside that we'd require the use of new-fangled `cabal` to run the testsuite, but this isn't exactly an unprecedented development, as we've always had an implicit `cabal` dependency anyways.

**Comment by ezyang** [comment]
@RyanGlScott There is a very specific reason Cabal's test suite uses a Custom setup which is because of bootstrapping issues with Cabal library described here: https://github.com/haskell/cabal/blob/67276f870a55e6a913b98ef7b2ca22a8def21a6e/cabal-testsuite/Setup.hs

This doesn't apply to singletons because you don't have a Cabal library that you are building in your project that you need to force your Setup file to link to.

**Comment by RyanGlScott** [comment]
Thanks @ezyang, that's good to know (I'm still not sure if I want to pursue a `Cabal` API–based approach, but that would be one less roadblock to overcome if I do go down that route).

The biggest obstacle that I'm facing now, more than anything, is figuring out the right directory to use! Currently, the `singletons` test suite just hardcoded `tests/compile-and-dump` as the (relative) directory to look for files, but this makes the big assumption that you're currently located inside the `singletons` directory. This assumption doesn't hold true in a modern `multi-ghc-travis` setup, where you typically invoke `cabal new-test` in a directory _above_ the `singletons` directory. Trying to guess where the test suite repo might live is proving to be a challenge as a result.

It appears that the approach that `cabal-testsuite` takes is to [manually pass the testsuite location](https://github.com/haskell/cabal/blob/b4907cccd414f4d0f448a63cdf05d5f9b8733837/travis-script.sh#L127)! Is there really no better way to do this? My hope would be that users could simply run `cabal new-test` without having to worry about this sort of thing...

**Comment by ezyang** [comment]
This snippet may be of interest:

```
-- | Guess what the dist directory of a running executable is,
-- by using the conventional layout of built executables
-- in relation to the top of a dist directory.  Will not work
-- if the executable has been installed somewhere else.
guessDistDir :: IO FilePath
guessDistDir = do
#if MIN_VERSION_base(4,6,0)
    exe_path <- canonicalizePath =<< getExecutablePath
    let dist0 = dropFileName exe_path </> ".." </> ".."
    b <- doesFileExist (dist0 </> "setup-config")
#else   
    let dist0 = error "no path"
        b = False
#endif
    if b then canonicalizePath dist0
         else findDistPrefOrDefault NoFlag >>= canonicalizePath
```

It works well enough that I don't need to specify it explicitly when I run the tests myself. I don't remember why I passed it explicitly in CI.

**Comment by RyanGlScott** [comment]
If I'm reading this correctly, this isn't what I'm looking for. The executable is typically located somewhere deep within `dist-newstyle` (e.g., `/u/rgscott/Software/singletons/dist-newstyle/build/x86_64-linux/ghc-8.4.0.20171222/singletons-2.4.1/t/singletons-test-suite/build/singletons-test-suite/singletons-test-suite`). Wouldn't this function just return `/u/rgscott/Software/singletons/dist-newstyle/build/x86_64-linux/ghc-8.4.0.20171222/singletons-2.4.1/t/singletons-test-suite` in that case?

**Comment by RyanGlScott** [comment]
I tried tracing how `cabal-testsuite` infers this information, but that takes me back to `testArgDistDir` which, AFAICT, has no default values and must be specified manually via [`--builddir`](https://github.com/haskell/cabal/blob/b24c84612d2ba2a3365b44ea1b7d29768788dd7d/cabal-testsuite/Test/Cabal/Monad.hs#L149-L152).

**Comment by ezyang** [comment]
Oh, I guess per-component build might make it so this code doesn't work. But I guess the directory layout for per-component build is pretty regular and so you can still find the relevant BuildInfo with a little more work?

**Comment by RyanGlScott** [comment]
#290 should fix this.
