### ISSUE TITLE
Function names with a leading underscore don't promote

### ISSUE THREAD

**Issue by RyanGlScott** [goldfirere/singletons#229]
```
λ> ; $(singletons [d| _foo :: Bool; _foo = True |])

<interactive>:8:5: error:
    Illegal type constructor or class name: ‘_fooSym0’
    When splicing a TH declaration: type _fooSym0 = _foo
```

We clearly shouldn't be picking the name `_fooSym0` for a type... but what _should_ we pick?

**Comment by goldfirere** [comment]
I vote `_FooSym0`. That is, all the rules for swizzling alphanumeric identifiers apply immediately after any prefix of underscores. If an identifier consists solely of underscores (which is legal in Haskell, as long as there is strictly more than 1 underscore), issue an error saying the user is being obstreperous and loses their `singletons` privileges.

**Comment by RyanGlScott** [comment]
But that's just the thing: `_FooSym0` isn't a legal datatype name either:

```
λ> data _FooSym0

<interactive>:1:6: error:
    Malformed head of type or class declaration: _FooSym0
```

**Comment by goldfirere** [comment]
Oh, of course it isn't. Blech. You could always translate `_` to `us` (for "underscore") and carry on. It's terribly ugly though. My bottom line: do what you like. This won't keep me up at night. :)

**Comment by RyanGlScott** [comment]
That sounds about right. I propose this special casing:

> original value: `___foo`
>
> promoted type*: `US___foo` ("`US`" stands for "underscore")
>
> singleton value*: `___sfoo`
>
> symbols*: `US___fooSym0`
>
> All functions that begin with a leading underscore are treated similarly.

This would even allow promotion/singling of `___` to work, since that would give you `US___` and `___s`, both of which are fine.

The only downside is that you wouldn't be able to squash unused warnings for `US___` since it doesn't being with an underscore. One might be able to tweak `SuppressUnusedWarnings` to make this happen, but I think that would fixing [GHC Trac #12564](https://ghc.haskell.org/trac/ghc/ticket/12564) first, so I won't worry about it for now.
