### ISSUE TITLE
[RFC] Don't generate defunctionalization symbols for constructors by default

### ISSUE THREAD

**Issue by RyanGlScott** [goldfirere/singletons#233]
(Spun off from #200.)

Currently, this fails:

```haskell
{-# LANGUAGE ExistentialQuantification #-}
{-# LANGUAGE TemplateHaskell #-}
{-# LANGUAGE TypeFamilies #-}
{-# LANGUAGE TypeInType #-}
{-# LANGUAGE TypeOperators #-}
module Bug where

import Data.Singletons.TH

$(singletons [d|
      data Foo = MkFoo Bool Bool

      mkFoo :: Bool -> Bool -> Foo
      mkFoo x y = MkFoo x y
    |])
```

```
Bug.hs:10:3: error:
    Multiple declarations of ‘MkFooSym0’
    Declared at: Bug.hs:10:3
                 Bug.hs:10:3

Bug.hs:10:3: error:
    Multiple declarations of ‘MkFooSym1’
    Declared at: Bug.hs:10:3
                 Bug.hs:10:3

Bug.hs:10:3: error:
    Multiple declarations of ‘MkFooSym2’
    Declared at: Bug.hs:10:3
                 Bug.hs:10:3
```

There's no reason why it shouldn't be able to work - the only reason it doesn't is because we happen to generate defunctionalization symbols for `mkFoo` and `MkFoo` with the same names. This is an unfortunate consequence of the naming convention where `mkFoo` is promoted to `MkFoo`.

Now, I quite like this naming convention, so I'm not proposing we change that. Rather, I propose something more... modest? I propose that we not generate defunctionalization symbols for the `MkFoo` constructor at all.

After all, we don't need to! Promoted constructors are one of the few things that can currently be partially applied at the type level in GHC, so instead of using defunctionalization symbols, we can just use `'MkFoo`, `TyCon1 'MkFoo`, and `TyCon2 'MkFoo` as appropriate. This would require changing some code generation in `singletons` to accommodate the change, but I think it would be possible.

The downside to this proposal is that some folks quite like having defunctionalization symbols for constructors. We could make this opt-in by still allowing users to write `$(genDefunSymbols [''Foo])` if they really want it. However, this behavior would _not_ be implied by `promote` or `singletons`.

**Comment by goldfirere** [comment]
I have to say that I don't love this solution -- singletons should generate the defun symbols for everything it touches, in my opinion.

Perhaps this is something else to throw into some sort of options structure being passed to `singletons`. Of course, if others out there disagree with me, speak up and I'll happily be overruled.

**Comment by RyanGlScott** [comment]
> I have to say that I don't love this solution

That's fine by me - I just wanted to see what your reaction was. I recognize that this is very much a corner case, so the solution might very well be to just tell folks to use custom naming options (once #204 is implemented).

> singletons should generate the defun symbols for everything it touches, in my opinion.

FWIW, this principle currently isn't followed. There is one class of things for which we don't generate defunctionalization symbols - datatype names. For instance, we don't have [`EitherSym0` and friends](https://github.com/goldfirere/singletons/issues/10).

Also, if we _did_ generate defunctionalization symbols for datatype names, we would rule out more programs from being singled. For instance, we could no longer single `newtype Identity a = Identity a`, since the defunctionalization symbols for `Identity` and `'Identity` would clash.

**Comment by int-index** [comment]
What if we don't generate singletons for constructors and users can opt-in like this?

```
mkFoo = MkFoo
```

**Comment by RyanGlScott** [comment]
@int-index, that would be a nice trick that could serve as an alternative to `$(genDefunSymbols [''Foo])` (or `$(genDefunSymbols [''Foo])`, assuming we augment `genDefunSymbols` with the ability to recognize individual constructor names).

If we adopted this trick, we'd have to revisit it if lowercase alphanumeric names ever become allowed at the type level (`map id :~: id`, anyone?) and we change the convention for promoting alphanumeric functions, but that's probably a long ways away.

**Comment by RyanGlScott** [comment]
It seems we're not willing to give up this feature, and moreover, there's a more general solution in the form of #200. In light of this, I'll retract this suggestion.
