### ISSUE TITLE
Proposal: demote GHC.TypeLits.Nat to Numeric.Natural instead of Integer

### ISSUE THREAD

**Issue by RyanGlScott** [goldfirere/singletons#238]
GHC 8.2 introduced the [`GHC.TypeNats`](http://hackage.haskell.org/package/base-4.10.0.0/docs/GHC-TypeNats.html) module which provides an alternative interface for `natVal`, `natVal'` _et al._ which uses [`Natural`](http://hackage.haskell.org/package/base-4.10.0.0/docs/Numeric-Natural.html#t:Natural) (an unbounded, non-negative integral type) from `Numeric.Natural` instead of `Integer`. In light of this, why not change `Demote Nat` to be `Natural` instead of `Integer`? Aside from being closer philosophically to `Nat` than `Integer`, this would allow us to make `toSing` total in the `SingKind` instance for `Nat`.

**Comment by goldfirere** [comment]
Sounds good to me. Thanks!
