### ISSUE TITLE
Add combinator for demoting a type to its corresponding value

### ISSUE THREAD

**Issue by RyanGlScott** [goldfirere/singletons#251]
We have the `SingI` class for conjuring up `Sing` values given, their type and kind. But sometimes you want to directly produce the value corresponding to that type. This combinator (which I've called `demote` for now, but don't feel strongly about) can be implemented like so:

```haskell
{-# LANGUAGE AllowAmbiguousTypes #-}
{-# LANGUAGE ScopedTypeVariables #-}
{-# LANGUAGE TypeApplications #-}
{-# LANGUAGE TypeInType #-}

import Data.Singletons

demote :: forall k (a :: k). (SingKind k, SingI a) => Demote k
demote = fromSing (sing @k @a)

example :: Bool
example = demote @_ @True
```

In GHCs prior, `demote` would have been impossibly awkward to use due to the inherent ambiguity of its `a` type argument. But now that `AllowAmbiguousTypes` and `TypeApplications` have entered the fray, using `demote` becomes cheap and cheerful. We should consider adding it to `singletons` (after deciding on a name).

**Comment by goldfirere** [comment]
A fine idea. Go for it.
