### ISSUE TITLE
type Π = Sing

### ISSUE THREAD

**Issue by RyanGlScott** [goldfirere/singletons#255]
Inspired by https://gist.github.com/goldfirere/013a71f3775a09c7ff2f3980f4d54133#file-vec-hs-L52:

```haskell
type Π = Sing -- because I can
```

Any objections to adding this to `singletons`? It does make hand-waving about dependently typed code snippets in Haskell much more convincing ;)

**Comment by goldfirere** [comment]
It does pose a future-compatibility problem, in that `∏` will become a keyword with `-XUnicodeSyntax -XDependentTypes`. I'm not sure that the language with those extensions will be able to refer at all to a symbol named `∏`.

But by then, `singletons` can be deprecated, so maybe it's all OK.

Yes, OK, go for it. :)

**Comment by RyanGlScott** [comment]
Oh dear, you're right. I had only suggested this because I thought it would be a painless addition, so I'd hate to fold this in if it will eventually need to be removed later on down the road.
