### ISSUE TITLE
Could not deduce (SingI is)

### ISSUE THREAD

**Issue by LeanderK** [goldfirere/singletons#260]
I am unable/unsure how to solve this problem:

```
Could not deduce (SingI is) arising from a use of ‘sing’
      from the context: Row row
        bound by the class declaration for ‘Row’
        at src/Extra/Row2.hs:104:7-9
```
`is` is of the kind `[Nat]`. 
Am i required to write the SingI instance by hand? Or can i generate it using singletons?
minimal non-compiling example (row is something like a optionally named record), i am currently experimenting with singletons, so don't expect great code 🙂

```haskell
$(promoteOnly [d|
    allInRange :: [Nat] -> [Type] -> Bool
    allInRange indexes types = all (\i -> i < leng) indexes
        where
            leng = length types

    mapToElement :: [Nat] -> [a] -> [a]
    mapToElement indexes types = map (\i -> types !! i) indexes

    maybeFilterNames :: [Nat] -> Maybe [Symbol] -> Maybe [Symbol]
    maybeFilterNames indexes (Just names) = Just $ map (\i -> names !! i) indexes
    maybeFilterNames indexes Nothing = Nothing

    getIndexOfNames :: [Symbol] -> Maybe [Symbol] -> Maybe [Nat]
    getIndexOfNames sys Nothing = Nothing
    getIndexOfNames sys (Just names) = seqMaybes $ map (\sy -> elemIndex sy names) sys

    seqMaybes :: [Maybe a] -> Maybe [a]
    seqMaybes [] = Just []
    seqMaybes ((Just x) : xs) = case seqMaybes xs of
        (Just rest) -> Just (x : rest)
        (Nothing)   -> Nothing
    seqMaybes ((Nothing) : ignored) = Nothing
 |])

type GetSliceNamedConstraints snames (is :: [Nat]) temp types names rts rns =
    (True ~ IsJust names, temp ~ GetIndexOfNames snames names, True ~ IsJust temp,
    is ~ FromJust temp, True ~ AllInRange is types, rts ~ MapToElement is types, 
    rns ~ MaybeFilterNames is names)

-- a row is ExampleRow (types :: [Type]) (names :: Maybe [Symbol])  

class Row row where
    getSlice :: 
        forall (is :: [Nat]) (rts :: [Type]) (rns :: Maybe [Symbol]) -- input / output types + names
            (types :: [Type]) (names :: Maybe [Symbol]). -- input row
        (True ~ AllInRange is types, rts ~ MapToElement is types, rns ~ MaybeFilterNames is names) 
        => Sing is -> row types names -> row rts rns

    getSliceNamed :: 
        forall (snames :: [Symbol]) -- input
            (is :: [Nat]) temp -- temp
            (rts :: [Type]) (rns :: Maybe [Symbol]) -- output types + names
            index (types :: [Type]) (names :: Maybe [Symbol]). -- input row
        (GetSliceNamedConstraints snames is temp types names rts rns) 
        => Sing snames -> row types names -> row rts rns
    getSliceNamed _ row = getSlice (sing :: Sing is) row
```
i know this is ugly, consider this a failed experiment in designing type-level code. I am currently rewriting the code, but i still have this problem.

**Comment by RyanGlScott** [comment]
Well, as the error message suggests, you're missing a `SingI` constraint in `getSliceNamed`.

> Am i required to write the SingI instance by hand? Or can i generate it using singletons?

You can indeed generate `SingI` instances using the `singletons` function. As demonstrated with this code:

```haskell
{-# LANGUAGE ExistentialQuantification #-}                                                         
{-# LANGUAGE TemplateHaskell #-}                                                                   
{-# LANGUAGE TypeFamilies #-}                                                                      
{-# LANGUAGE TypeInType #-}                                                                        

import Data.Singletons.TH

$(singletons [d| data MyBool = MyFalse | MyTrue |])
```

```
$ /opt/ghc/8.2.1/bin/ghci -ddump-splices Foo.hs
GHCi, version 8.2.1: http://www.haskell.org/ghc/  :? for help
Loaded GHCi configuration from /home/ryanglscott/.ghci
[1 of 1] Compiling Main             ( Foo.hs, interpreted )
Foo.hs:8:3-50: Splicing declarations
    singletons [d| data MyBool_a3GQ = MyFalse_a3GR | MyTrue_a3GS |]
  ======>
    data MyBool_a6lw = MyFalse_a6lx | MyTrue_a6ly
    type MyFalseSym0 = MyFalse_a6lx
    type MyTrueSym0 = MyTrue_a6ly
    data instance Sing (z_a6lz :: MyBool_a6lw)
      = z_a6lz ~ MyFalse_a6lx => SMyFalse |
        z_a6lz ~ MyTrue_a6ly => SMyTrue
    type SMyBool = (Sing :: MyBool_a6lw -> GHC.Types.Type)
    instance SingKind MyBool_a6lw where
      type Demote MyBool_a6lw = MyBool_a6lw
      fromSing SMyFalse = MyFalse_a6lx
      fromSing SMyTrue = MyTrue_a6ly
      toSing MyFalse_a6lx = SomeSing SMyFalse
      toSing MyTrue_a6ly = SomeSing SMyTrue
    instance SingI MyFalse_a6lx where
      sing = SMyFalse
    instance SingI MyTrue_a6ly where
      sing = SMyTrue
Ok, 1 module loaded.
```

Notice that this generated `SingI` instances for all of the constructors (in this example, `MyFalse`, and `MyTrue`).

**Comment by LeanderK** [comment]
but `is` is of kind `[Nat]`, how can I generate `SingI`instances for it? A list kind is already defined.

**Comment by RyanGlScott** [comment]
Oh, I missed the fact that we're dealing with `[Nat]`. In that case, your job is much easier, as there's already a [`SingI` instance for any `KnownNat`](https://github.com/goldfirere/singletons/blob/fe370c4a26088cac370a14dc6be342194103f131/src/Data/Singletons/TypeLits/Internal.hs#L63-L64):

```haskell
instance KnownNat n => SingI n where
  sing = SNat
```

Examples of it in action:

```
GHCi, version 8.2.1: http://www.haskell.org/ghc/  :? for help
Loaded GHCi configuration from /home/ryanglscott/.ghci
λ> :m + Data.Singletons Data.Singletons.TypeLits
λ> :set -XTypeApplications -XDataKinds
λ> sing @Nat @0
SNat @0
λ> sing @Nat @1
SNat @1
```

**Comment by LeanderK** [comment]
i am sorry, i still don't get it.

```haskell
foo :: forall (is :: [Nat]) (inputRTypes :: RowTypes) index. 
     (index ~ RowIndex inputRTypes)
     => Sing is -> row inputRTypes -> index

bar :: forall (is :: [Nat]) (inputRTypes :: RowTypes) index. 
    (index ~ RowIndex inputRTypes)
    => row inputRTypes -> index
    baar row = foo (sing @[Nat] @is) row
```
when i try to compile it:

```
Could not deduce (SingI is) arising from a use of ‘sing’
      from the context: Row row
```

but `get (sing @Nat @i) row` is working.

**Comment by RyanGlScott** [comment]
Again, your type signature for `bar` is wrong. You need to declare a `SingI is` constraint, as GHC has no idea which inhabitant of `[Nat]` `is` is.

**Comment by LeanderK** [comment]
thank you, solves the problem. If somebody is reading this later and still wondering why exactly this is needed (Can't singletons just figure this out?) the singletons paper is enlightening, chapter 2.6 is relevant.

**Comment by AriFordsham** [comment]
Thanks! I was searching for this for ages. Maybe the documentation can point it out somewhere?

**Comment by RyanGlScott** [comment]
Could you expand a little more on what additional documentation you would want, and perhaps where you would want it to be placed? I have likely stared at this code for too long, but the [documentation for `SingI`](https://hackage.haskell.org/package/singletons-3.0.2/docs/Data-Singletons.html#t:SingI) does mention that it supports the use case of implicitly passing singletons. Maybe the confusion relates to some other aspect of `SingI`, however. If so, please let me know—I'm honestly not sure what it is.

**Comment by AriFordsham** [comment]
It was non-obvious to me (in foresight, not hindsight) that

```haskell
s :: forall (t :: T). (SingI t) => Sing t
s = sing 
```

would require the `SingI` constraint.

**Comment by RyanGlScott** [comment]
To make sure I understand the point of confusion, let me attempt to paraphrase the stumbling point. If you have this:

```hs
sing @(t :: T)
```

Then the tricky part is that you need a `SingI t` instance, not a `SingI T` instance. The latter of these would normally be discharged through a top-level instance, so one normally wouldn't think to add such a constraint. Is that right?

**Comment by AriFordsham** [comment]
Yup.

**Comment by RyanGlScott** [comment]
I've attempted to document this better in #544.
