### ISSUE TITLE
Extensible type computations

### ISSUE THREAD

**Issue by o1lo01ol1o** [goldfirere/singletons#261]
This involves no issue with singletons -- so forgive the noise -- but I need some help with a problem that is a bit too specific for people who haven't spent time thinking about singltons.

Effectively, my problem is that I have a number of functions, `Node op`, operating on multi-dimensional arrays of shape `[Maybe Nat]`. Each function has its own type-level function, `tyfun` that calculates the resultant shape of the array after the computation.  I would like to be able to specify declaratively a chain of such functions where the resulting type could be folded over at the  using somthing like `FoldS`, applying the calculation function `tyfun` on the output of the previous step, so that the whole chain will type check if all the calculations and constraints on the instances of `Node op tyfun` are met.

Something like: 

```haskell
type ValidQuux = FoldS Check ((:=>) Foo ((:=>) Bar Baz))

go = runIt (a :: ValidQuux)

``` 

where `Foo` `Bar` and `Baz` are all instances of `Node op fun` as in the below, invalid sketch. 

(I've used a type class because I would like to be able to define new instances of `Node op tyfun` without any knowledge of existing ops and their type-functions.)

Can anyone advise how this might be possible?

```haskell
class Node op (tyfun ::
   TyFun [Maybe Nat] (TyFun [Maybe Nat] [Maybe Nat] -> Type) -> *)

data S :: * -> * where
      Nil :: S a
      (:=>) :: (Node a tyfun) => a -> S a  -> S a

type family FoldS last mS where
  FoldS l Nil = l
  FoldS l ((:=>) a b) = FoldS (FoldS l a) b
```

**Comment by RyanGlScott** [comment]
I know very little about the actual problem you're trying to solve, so all I can offer are shots in the dark. But there's already a big problem with the pseudocode you have shown, as tossing that to the GHC typechecker makes it unhappy:

```
Foo.hs:27:12: error:
    • Illegal constraint in a type: Node a0 tyfun0
    • In the second argument of ‘FoldS’, namely ‘((:=>) a b)’
      In the type family declaration for ‘FoldS’
   |
27 |   FoldS l ((:=>) a b) = FoldS (FoldS l a) b
   |            ^^^^^^^^^
```

In other words, this code tickles [this GHC bug](https://ghc.haskell.org/trac/ghc/ticket/13895). So the approach of putting these constraints into a data constructor and then promoting them is, at least for the time being, a non-starter.

Perhaps what you're searching for is some kind of type family which applies a constraint to every element of a type-level list? That is, something like this:

```haskell
{-# LANGUAGE ConstraintKinds #-}
{-# LANGUAGE ExistentialQuantification #-}
{-# LANGUAGE FlexibleInstances #-}
{-# LANGUAGE ScopedTypeVariables #-}
{-# LANGUAGE TemplateHaskell #-}
{-# LANGUAGE TypeApplications #-}
{-# LANGUAGE TypeFamilies #-}
{-# LANGUAGE TypeInType #-}
{-# LANGUAGE TypeOperators #-}
module Foo where

import Data.Kind
import Data.Singletons.TH

type family All (p :: a ~> Constraint) (l :: [a]) :: Constraint where
  All _ '[]    = ()
  All p (x:xs) = (p @@ x, All p xs)

type ReadAndShow a = (Read a, Show a)
$(genDefunSymbols [''ReadAndShow])

runIt :: All ReadAndShowSym0 l => Proxy l -> Int
runIt _ = 42

compiles = runIt (Proxy @'[Int, Double, Float])

data Hm

-- doesn'tCompile = runIt (Proxy @'[Int, Hm])
```

With some modifications, you could replace `ReadAndShow` with a constraint of your choosing, such as `Node`.

**Comment by o1lo01ol1o** [comment]
Cool, thanks!  I ended up doing the following for the example I posted (in actuality my GADT is more complex than a linked list):

```haskell
data S :: * -> * where
      Nil :: S a
      (:=>) :: (tyfun ~ ([Maybe Nat] ~> [Maybe Nat] ~> [Maybe Nat] )) => [Maybe Nat] -> tyfun -> S a  -> S a

type family FoldS (acc :: [Maybe Nat]) (a :: S b) where
  FoldS acc Nil = acc
  FoldS acc ((:=>) a f n) = FoldS ((f @@ acc) @@ a) n

type family Smush (acc :: [Maybe Nat]) (t ::[Maybe Nat]) where
  Smush acc t = acc :++ t

$(genDefunSymbols [''Smush])

type G = (:=>) '[Just 1] SmushSym0 ((:=>) '[Just 2] SmushSym0 Nil)

runIt :: forall v l. ( v ~ FoldS l G, SingI v ) => Proxy l -> [Maybe Int]
runIt _ = case (sing :: Sing v) of
  SNil -> []
  (SCons x xs) -> map go ( fromSing x: fromSing xs)
  where go v = case v of
          Just v -> Just (P.fromIntegral v)
          Nothing -> Nothing

compiles = runIt (Proxy @'[Just 3])
```
👍

**Comment by RyanGlScott** [comment]
Good to know. Can this issue be closed, then?
