### ISSUE TITLE
Audit uses of newUniqueName in singletons and th-desugar

### ISSUE THREAD

**Issue by RyanGlScott** [goldfirere/singletons#270]
As noted in https://ghc.haskell.org/trac/ghc/ticket/14436, because of `singletons`' liberal use of `newUniqueName`, it frequently generates long variable names like `_z_6989586621679437436` which look awful to read in Haddocks. However, after doing a quick skim over the places where `singletons` currently uses `newUniqueName`, many of them seem wholly unnecessary, as they produce names that are only used locally, not globally! (Which is ostensibly why `newUniqueName` exists at all.)

We should do a more thorough review of the places where `newUniqueName` is called and see which occurrences can be switched over to `newName` to hopefully make the Haddocks more tolerable when possible.

**Comment by RyanGlScott** [comment]
Ugh. Turns out this is far more complicated than I could have ever envisioned. I was naïve and assumed that only top-level names would ever need to use `newUniqueName`, but this isn't true—due to `singletons` name-mangling scheme, it frequently takes existing names and attaches prefixes to them. For example, during singling we might turn `foo a_{123} a_{456}` (where `{n}` denotes a unique) into `sFoo sA sA`. But notice that there are now duplicate `sA` variables!

Here, we can't reuse the unique 123 from `a_{123}` for `sA`, so it would seem our only choice is to make it so that the name of the variable is literally `a_123` (using `newUniqueName`). That way, we mangle this to `sA_123` during singling, and then there is no conflict. Alas, this does mean that we now have lots of ugly uniques that manifest in the Haddocks, but I can't think of another way around this...

**Comment by goldfirere** [comment]
Perhaps a middle ground is to come up with a different implementation of `newUniqueName` that isn't as ugly. Specifically, we could generate our own, small unique numbers to affix to names. I'm not sure this is really worth the bother, though.

**Comment by RyanGlScott** [comment]
> I'm not sure this is really worth the bother, though.

This is the conclusion that I've come to. That is, it's not worth the bother to re-architect large parts of `singletons` just to have shorter generated variable names.
