### ISSUE TITLE
singletons uses two completely different (and incompatible) type inference algorithms for deriving Eq and Ord

### ISSUE THREAD

**Issue by RyanGlScott** [goldfirere/singletons#271]
This doesn't compile:

```haskell
{-# LANGUAGE ExistentialQuantification #-}
{-# LANGUAGE GADTs #-}
{-# LANGUAGE InstanceSigs #-}
{-# LANGUAGE ScopedTypeVariables #-}
{-# LANGUAGE TemplateHaskell #-}
{-# LANGUAGE TypeFamilies #-}
{-# LANGUAGE TypeInType #-}
{-# LANGUAGE UndecidableInstances #-}
module Bug where

import Data.Kind
import Data.Singletons.Prelude
import Data.Singletons.TH

$(singletons [d| newtype Constant (a :: Type) (b :: Type) =
                    Constant a deriving (Eq, Ord) |])
```

```
$ /opt/ghc/8.2.1/bin/ghci Bug.hs
GHCi, version 8.2.1: http://www.haskell.org/ghc/  :? for help
Loaded GHCi configuration from /home/ryanglscott/.ghci
[1 of 1] Compiling Bug              ( Bug.hs, interpreted )

Bug.hs:15:3: error:
    • Could not deduce (SEq b)
        arising from the superclasses of an instance declaration
      from the context: SOrd a
        bound by the instance declaration at Bug.hs:(15,3)-(16,52)
      Possible fix:
        add (SEq b) to the context of the instance declaration
    • In the instance declaration for ‘SOrd (Constant a b)’
   |
15 | $(singletons [d| newtype Constant (a :: Type) (b :: Type) =
   |   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^...
```

`-ddump-splices` reveals the reason why:

```haskell
    instance (SEq a_a7tf, SEq b_a7tg) =>
             SEq (Constant_a7td a_a7tf b_a7tg) where
      ...
    instance SOrd a_a7tf => SOrd (Constant_a7td a_a7tf b_a7tg) where
      ...
```

Notice that the `SEq` and `SOrd` instances have two completely different inferred instance contexts! For `SEq`, there's a redundant `SEq b` constraint, whereas the `SOrd` instance lacks this.

This leads one to wonder: why are there two completely different ways to infer the instance contexts for `SEq` and `SOrd`? And shouldn't we use the algorithm for `SOrd` for `SEq` as well, given that the current algorithm for `SEq` appears to be plain broken?

**Comment by RyanGlScott** [comment]
I might have spoken too soon when I said that `deriving Eq` is broken. In a somewhat different context (GADTs), it turns out that `deriving Eq` does the right thing, and that `deriving Ord` is broken:

```haskell
{-# LANGUAGE ExistentialQuantification #-}
{-# LANGUAGE GADTs #-}
{-# LANGUAGE InstanceSigs #-}
{-# LANGUAGE ScopedTypeVariables #-}
{-# LANGUAGE TemplateHaskell #-}
{-# LANGUAGE TypeFamilies #-}
{-# LANGUAGE TypeInType #-}
{-# LANGUAGE UndecidableInstances #-}
module Bug where

import Data.Kind
import Data.Singletons.Prelude
import Data.Singletons.TH

$(singletons
    [d| data Identity :: Type -> Type where
          Identity :: a -> Identity a
          deriving (Eq, Ord)
      |])
```
```
../Bug.hs:15:3: error:
    • Could not deduce (SOrd a0)
      from the context: SOrd a
        bound by an instance declaration:
                   forall a a1. SOrd a => SOrd (Identity a1)
        at ../Bug.hs:(15,3)-(19,8)
      The type variable ‘a0’ is ambiguous
    • In the ambiguity check for an instance declaration
      To defer the ambiguity check to use sites, enable AllowAmbiguousTypes
      In the instance declaration for ‘SOrd (Identity a_a3qHD)’
   |
15 | $(singletons
   |   ^^^^^^^^^^...
```

Let's see what `-ddump-splices` has in store for us this time:

```haskell
    data instance Sing (z_a3qSV :: Identity_a3qSg a_a3qSj)
      where
        SIdentity :: forall (n_a3qSW :: a_a3qSi).
                     (Sing (n_a3qSW :: a_a3qSi)) -> Sing (Identity_a3qSh n_a3qSW)
    ...
    instance SOrd a_a3qSi => SOrd (Identity_a3qSg a_a3qSj) where
      ...
    instance SEq a_a3qSj => SEq (Identity_a3qSg a_a3qSj) where
      ...
```

Oh bother. It turns out that the instance context for the `SEq` instance:

```haskell
instance SEq a_a3qSj => SEq (Identity_a3qSg a_a3qSj)
```

Is using the type variable `a_a3qSj`, which is obtained from the `Identity` //type// constructor. This gives a well formed instance like you'd expect. However, the instance context for the `SOrd` instance:

```haskell
instance SOrd a_a3qSi => SOrd (Identity_a3qSg a_a3qSj)
```

Is using a completely different type variable, `a_a3qSi`! This variable is taken from the `Identity` //data// constructor. If `Identity` were defined as `newtype Identity a = Identity a`, then these two occurrences of `a` would just happen to line up without any extra fuss. But since `Identity` is defined here with GADT syntax, the two `a`s have different uniques, causing the pandemonium above.

Ultimately, I think the approach that the inference algorithm for `deriving Ord` is using is the more correct one, but this does demonstrate that we need to perform a substitution to get the right type variables in the instance head.

**Comment by goldfirere** [comment]
It seems you're hot on the trail on this one. Let me know if you need input from me, but everything above makes it look like you've got a handle on what's going on.
