### ISSUE TITLE
Guard promotion to singleton failure

### ISSUE THREAD

**Issue by brunom** [goldfirere/singletons#282]
$(singletons [d|
        data Tree a
            = Empty
            | Node a (Tree a) (Tree a)
        |])

    $(singletons [d|
        height :: Tree e -> Nat
        height Empty = 0
        height (Node _ _ t) = 1 + height t
        |])

    $(singletons [d|
        skew' :: e -> [Tree e] -> [Tree e]
        skew' f (a:b:ts) | height a == height b = Node f a b : ts
        skew' f ts = Node f Empty Empty : ts
        |])
won't work.  Changing the last splice to promote fixes it.

**Comment by RyanGlScott** [comment]
This is a known limitation, see the [Supported Haskell constructs](https://github.com/goldfirere/singletons/tree/2ac40b37af03a5e613daf020a515305663877403#supported-haskell-constructs) section of the `README`. In order to successfully single `skew'`, you'll need to rewrite it into a form that doesn't use overlapping patterns, such as this:

```haskell
{-# LANGUAGE ExistentialQuantification #-}
{-# LANGUAGE ScopedTypeVariables #-}
{-# LANGUAGE TemplateHaskell #-}
{-# LANGUAGE TypeFamilies #-}
{-# LANGUAGE TypeInType #-}
{-# LANGUAGE UndecidableInstances #-}
module Foo where

import Data.Singletons.Prelude
import Data.Singletons.TH
import GHC.TypeLits

$(singletons [d|
    data Tree a
        = Empty
        | Node a (Tree a) (Tree a)
    |])

$(singletons [d|
    height :: Tree e -> Nat
    height Empty = 0
    height (Node _ _ t) = 1 + height t
    |])

$(singletons [d|
    skew' :: e -> [Tree e] -> [Tree e]
    skew' f (a:b:ts) =
      if height a == height b
         then Node f a b : ts
         else Node f Empty Empty : a : b : ts
    skew' f [a] = [Node f Empty Empty, a]
    skew' f []  = [Node f Empty Empty]
    |])
```
