### ISSUE TITLE
Generalize Data.Singletons.TypeRepStar to work over any TYPE rep

### ISSUE THREAD

**Issue by RyanGlScott** [goldfirere/singletons#286]
Currently, `Data.Singletons.TypeRepStar` looks like this:

```haskell
newtype instance Sing :: Type -> Type where
  STypeRep :: TypeRep a -> Sing a
```

This works, but it might be too specific. It turns out that all of the code in `Data.Singletons.TypeRepStar` works if you generalize `Type` to `TYPE rep`. Here is a sketch of what that might look like (with some suggested renamings):

```haskell
{-# LANGUAGE FlexibleInstances #-}
{-# LANGUAGE GADTs #-}
{-# LANGUAGE RankNTypes #-}
{-# LANGUAGE TypeFamilies #-}
{-# LANGUAGE TypeInType #-}
module SingTypeRep where

import Data.Kind
import Data.Singletons.Decide
import Data.Singletons.Prelude
import Data.Singletons.ShowSing

import GHC.Exts (RuntimeRep, TYPE)

import Type.Reflection
import Type.Reflection.Unsafe (typeRepFingerprint)

import Unsafe.Coerce (unsafeCoerce)

newtype instance Sing :: forall (rep :: RuntimeRep). TYPE rep -> Type where
  STypeRep :: forall (rep :: RuntimeRep) (a :: TYPE rep). TypeRep a -> Sing a
    deriving (Eq, Ord, Show)

-- | A variant of 'SomeTypeRep' whose underlying 'TypeRep' is restricted to
-- kind @'TYPE' rep@ for some 'RuntimeRep' @rep@.
data SomeTypeRepTYPE :: RuntimeRep -> Type where
  SomeTypeRepTYPE :: forall (rep :: RuntimeRep) (a :: TYPE rep). !(TypeRep a) -> SomeTypeRepTYPE rep

instance Eq (SomeTypeRepTYPE rep) where
  SomeTypeRepTYPE a == SomeTypeRepTYPE b =
    case eqTypeRep a b of
      Just HRefl -> True
      Nothing    -> False

instance Ord (SomeTypeRepTYPE rep) where
  SomeTypeRepTYPE a `compare` SomeTypeRepTYPE b =
    typeRepFingerprint a `compare` typeRepFingerprint b

instance Show (SomeTypeRepTYPE rep) where
  showsPrec p (SomeTypeRepTYPE ty) = showsPrec p ty

instance Typeable a => SingI (a :: TYPE rep) where
  sing = STypeRep typeRep
instance SingKind (TYPE rep) where
  type Demote (TYPE rep) = SomeTypeRepTYPE rep
  fromSing (STypeRep tr) = SomeTypeRepTYPE tr
  toSing (SomeTypeRepTYPE tr) = SomeSing $ STypeRep tr

instance PEq (TYPE rep) where
  type a == b = EqTYPE a b

type family EqTYPE (a :: TYPE rep) (b :: TYPE rep) where
  EqTYPE (a :: TYPE rep) (a :: TYPE rep) = 'True
  EqTYPE a               b               = 'False

instance SEq (TYPE rep) where
  STypeRep tra %== STypeRep trb =
    case eqTypeRep tra trb of
      Just HRefl -> STrue
      Nothing    -> unsafeCoerce SFalse
                    -- the Data.Typeable interface isn't strong enough
                    -- to enable us to define this without unsafeCoerce

instance SDecide (TYPE rep) where
  STypeRep tra %~ STypeRep trb =
    case eqTypeRep tra trb of
      Just HRefl -> Proved Refl
      Nothing    -> Disproved (\Refl -> error "Type.Reflection.eqTypeRep failed")

instance ShowSing (TYPE rep) where
  showsSingPrec = showsPrec
```

One issue this would present is that the module name `TypeRepStar` would become a tad misleading. `TypeRepTYPE`, perhaps?

**Comment by goldfirere** [comment]
As remarked elsewhere (I forget where), the instance for `TypeRep` could be arbitrarily generalized: `newtype instance Sing :: forall k. k -> Type where ...` would work, too! Indeed, we could just throw out our singletons machinery in favor of just that. (Would this work for functions? Doubtful.) In any case, I agree that you propose a useful generalization. I'm not very bothered by the name, though.

**Comment by RyanGlScott** [comment]
We could. I suppose I'm drawing a (perhaps arbitrary) distinction between `TYPE rep` and other kinds we define singletons for (e.g., `Bool`) in the sense that the `Sing` instance for `Bool` is much easier to use in practice that `TypeRep (a :: Bool)` is, as pattern-matching on `TypeRep`s require extra view patterns and more runtime checks. Or, to put it another way: the singletons for closed kinds like `Bool` in this package are more convenient than the singletons for open kinds like `TYPE rep`, where we pretty much have no options besides `TypeRep`.

If we're drawing an open-versus-closed kind distinction, then I suppose there's the sticky issue of the other famous open kind, `Constraint`... But as you noted in https://github.com/goldfirere/singletons/issues/280#issuecomment-348354023, perhaps we ought not to define singletons for both `TYPE rep` and `Constraint` simultaneously until https://github.com/ghc-proposals/ghc-proposals/pull/32 is resolved.

**Comment by goldfirere** [comment]
Yes, let's please not have competing singletons for `Type` and `Constraint`. That whole swamp is boggy enough as it is. :)

I think your arbitrary distinction is a useful one. Go for it.
