### ISSUE TITLE
Can't promote or single an instance for (a -> b)

### ISSUE THREAD

**Issue by RyanGlScott** [goldfirere/singletons#287]
While working on https://github.com/goldfirere/singletons/issues/184#issuecomment-355857980, I ran into an issue: the following instance will not single:

```haskell
{-# LANGUAGE DefaultSignatures #-}
{-# LANGUAGE FlexibleInstances #-}
{-# LANGUAGE GADTs #-}
{-# LANGUAGE InstanceSigs #-}
{-# LANGUAGE ScopedTypeVariables #-}
{-# LANGUAGE TemplateHaskell #-}
{-# LANGUAGE TypeFamilies #-}
{-# LANGUAGE TypeInType #-}
{-# LANGUAGE TypeOperators #-}
{-# LANGUAGE UndecidableInstances #-}
module Bug where

import Prelude ()
import Data.Singletons.TH

$(singletons [d|
  class Semigroup a where
    (<>) :: a -> a -> a

  instance Semigroup b => Semigroup (a -> b) where
    f <> g = \x -> f x <> g x
  |])
```

```
$ /opt/ghc/8.4.1/bin/ghc Bug.hs
[1 of 1] Compiling Bug              ( Bug.hs, Bug.o )

Bug.hs:16:3: error:
    • Expected kind ‘TyFun a b -> *’,
        but ‘Apply (Apply TFHelper_6989586621679033749Sym0 a_a6en) a_a6eo’ has kind ‘TyFun
                                                                                       (TyFun a b) *
                                                                                     -> *’
    • In the type ‘Apply (Apply TFHelper_6989586621679033749Sym0 a_a6en) a_a6eo’
      In the type instance declaration for ‘<>’
      In the instance declaration for
        ‘PSemigroup (TyFun a_a6dJ b_a6dI -> GHC.Types.Type)’
   |
16 | $(singletons [d|
   |   ^^^^^^^^^^^^^^...
```

Moreover, I can't even find an alternative way to write the instance that does work. This also fails with the same error:

```haskell
  instance Semigroup b => Semigroup (a -> b) where
    f <> g = h
      where
        h x = f x <> g x
```

This also fails, but with a different error:

```haskell
  instance Semigroup b => Semigroup (a -> b) where
    (f <> g) x = f x <> g x
```
```
$ /opt/ghc/8.4.1/bin/ghc Bug.hs
[1 of 1] Compiling Bug              ( Bug.hs, Bug.o )

Bug.hs:16:3: error:
    Function being promoted to (<>@#@$) has too many arguments.
   |
16 | $(singletons [d|
   |   ^^^^^^^^^^^^^^...

Bug.hs:16:3: error: Q monad failure
   |
16 | $(singletons [d|
   |   ^^^^^^^^^^^^^^...
```

Promotion doesn't work either. If I try to promote either of the first two variants of the program, such as:

```haskell
$(promote [d|
  class Semigroup a where
    (<>) :: a -> a -> a

  instance Semigroup b => Semigroup (a -> b) where
    f <> g = \x -> f x <> g x
  |])
```

It fails with:

```
$ /opt/ghc/8.4.1/bin/ghc Bug.hs
[1 of 1] Compiling Bug              ( Bug.hs, Bug.o )

Bug.hs:16:3: error:
    • Expected kind ‘TyFun a b -> *’,
        but ‘Apply (Apply TFHelper_6989586621679033837Sym0 a_a6fN) a_a6fO’ has kind ‘TyFun
                                                                                       (TyFun a b) *
                                                                                     -> *’
    • In the type ‘Apply (Apply TFHelper_6989586621679033837Sym0 a_a6fN) a_a6fO’
      In the type instance declaration for ‘<>’
      In the instance declaration for
        ‘PSemigroup (TyFun a_a6f9 b_a6f8 -> GHC.Types.Type)’
   |
16 | $(promote [d|
   |   ^^^^^^^^^^^...
```

And attempting to promote this:

```haskell
$(promote [d|
  class Semigroup a where
    (<>) :: a -> a -> a

  instance Semigroup b => Semigroup (a -> b) where
    (f <> g) x = f x <> g x
  |])
```

fails with:

```
$ /opt/ghc/8.4.1/bin/ghc Bug.hs
[1 of 1] Compiling Bug              ( Bug.hs, Bug.o )

Bug.hs:16:3: error:
    • Number of parameters must match family declaration; expected 2
    • In the type family declaration for ‘TFHelper_6989586621679033740’
   |
16 | $(promote [d|
   |   ^^^^^^^^^^^...
```

I have no choice but to define these instances by hand as a result.

**Comment by RyanGlScott** [comment]
After staring at the `-ddump-splices` output for a while, I've found something which looks suspicious. First, take a look at the definition of the auto-generated `TFHelper` type family (after some cleanup for presentation purposes):

```haskell
type family TFHelper (f :: TyFun a b -> Type) (g :: TyFun a b -> Type) :: TyFun a b -> Type where
  TFHelper f g = Apply (Apply LambdaSym0 f) g

type family Lambda f g x where
  Lambda f g x = Apply (Apply (<>@#@$) (Apply f x)) (Apply g x)
```

This appears to be in working order. It's when we get to `TFHelper`'s defunctionalization symbols, however, that things go awry. For instance, here is the definition of `TFHelperSym3`:

```haskell
type TFHelperSym3 (f :: TyFun a b -> Type) (g :: TyFun a b -> Type) (x :: TyFun a b) =
    TFHelper f g x
```

The kind of `x` looks mighty strange. Recall that `type a ~> b = TyFun a b -> Type`, but `x :: TyFun a b`, without the trailing `-> Type` part. This likely explains why the error message mentions the nonsensical kind `TyFun (TyFun a b) * -> *`. My hunch is that `genDefunSymbols` is generating defunctionalization symbols one at a time by splitting along occurrences of the `(->)` type constructor, and mistakenly thinks that `TFHelper`'s return kind `TyFun a b -> Type` should be turned into `(x :: TyFam a b) -> Type`.

If this hunch is correct, a possible easy fix would be to generate `a ~> b` instead of `TyFun a b -> Type` so the `genDefunSymbols` doesn't become confused. An interesting consequence of this would be that `TFHelperSym3` wouldn't be generated in the first place—the highest arity that `genDefunSymbols` would go to would be `Sym2`. Is this correct? After all, one could conceivably generate `TFHelperSym3` as:

```haskell
type TFHelperSym3 (f :: TyFun a b -> Type) (g :: TyFun a b -> Type) (x :: a) =
    Apply (TFHelper f g) x
```

I don't know if this would be worth the effort, though.

**Comment by goldfirere** [comment]
I think you're right on the money here. No, we don't need `TFHelperSym3` at all. `TFHelper` has arity 2.
