### ISSUE TITLE
Performance of singletons

### ISSUE THREAD

**Issue by LeanderK** [goldfirere/singletons#301]
I have googled a bit, but have not found anything.
I am interested in the performance of the singleton-library, for example, does singletons-style code get completely optimized away when the type is known at compile-time?
What is the performance of code that does depend on runtime type-information? Does it slow things down significantly?

**Comment by RyanGlScott** [comment]
I think you're going to have to be a lot more specific, since the phrases "when the type is known at compile-time" and "depend on runtime type-information" can mean different things in different contexts. In other words, what is the program you actually care about? :)

**Comment by LeanderK** [comment]
it's not a specific program or problem, I was just wondering 🙂
let's say we have these functions (i hope I am specific enough, my laptop is compiling gcc and it's taking ages...)

```haskell
dep1 :: SBool z -> Int -> Int
dep1 STrue a b = a + b
dep1 SFalse a b = a - b

depSumInts :: KnownNat n => Int -> Int
depSumInts ...


index :: KnownNat n,  KnownNat m, m '< n => Vec m a -> a
index ...


notAnymore1 = dep1 STrue
notAnymore2 = depSumInts @3
dependent c = case toSing c of
      SomeSing (SNat :: Sing n) -> index @n
````
so, my question is now what can be optimized? Will `notAnymore1` equal `a + b` and  `notAnymore2` equal `3 + a + b`?
Also, let's say I am calling `dependent` quite often, is `toSing c` a serious bottleneck compared to `index2 :: Int -> Vec a -> a`? I would guess so, but how big is the impact?

**Comment by RyanGlScott** [comment]
As with many questions of what will be optimized away in GHC, there's often not a reliable litmus test. The most dependable way to check is to inspect what Core will be generated yourself, using the `-ddump-simpl` flag. First, let's compare your `notAnymore1` example:

```haskell
{-# LANGUAGE GADTs #-}
module Foo where

import Data.Singletons.Prelude

dep1 :: SBool z -> Int -> Int -> Int
dep1 STrue a b = a + b
dep1 SFalse a b = a - b

notAnymore1 :: Int -> Int -> Int
notAnymore1 = dep1 STrue

notAnymore1' :: Int -> Int -> Int
notAnymore1' a b = a + b
```

If we compile this with `-ddump-simpl`, plus some extra flags for readability, we get this excerpt:

```
$ /opt/ghc/8.2.2/bin/ghc Foo.hs -O2 -ddump-simpl -dsuppress-uniques -dsuppress-module-prefixes -dsuppress-idinfo

-- RHS size: {terms: 1, types: 0, coercions: 0, joins: 0/0}
notAnymore1 :: Int -> Int -> Int
notAnymore1 = $fNumInt_$c+

-- RHS size: {terms: 1, types: 0, coercions: 0, joins: 0/0}
notAnymore1' :: Int -> Int -> Int
notAnymore1' = $fNumInt_$c+
```

So `notAnymore1` optimizes precisely to `(+)`.

As for `notAnymore2` (note that I'm completely guessing what you intended this function to do):

```haskell
{-# LANGUAGE AllowAmbiguousTypes #-}
{-# LANGUAGE DataKinds #-}
{-# LANGUAGE ScopedTypeVariables #-}
{-# LANGUAGE TypeApplications #-}
module Foo where

import Data.Proxy
import GHC.TypeNats

depSum3Ints :: forall n. KnownNat n => Int -> Int -> Int
depSum3Ints a b = fromIntegral (natVal (Proxy @n)) + a + b

notAnymore2 :: Int -> Int -> Int
notAnymore2 = depSum3Ints @3

notAnymore2' :: Int -> Int -> Int
notAnymore2' a b = 3 + a + b
```

You get:

```
-- RHS size: {terms: 56, types: 21, coercions: 0, joins: 0/0}
notAnymore1 :: Int
notAnymore1
  = case notAnymore3 of wild {
      S# i# ->
        case tagToEnum# @ Bool (>=# i# 0#) of {
          False -> case underflowError of wild2 { };
          True ->
            case integerToInt (wordToInteger (int2Word# i#)) of wild2
            { __DEFAULT ->
            I# wild2
            }
        };
      Jp# dt ->
        case uncheckedIShiftRL# (sizeofByteArray# dt) 3# of {
          __DEFAULT ->
            case sizeofByteArray# dt of {
              __DEFAULT ->
                case integerToInt wild of wild4 { __DEFAULT -> I# wild4 };
              0# -> case underflowError of wild4 { }
            };
          1# ->
            case indexWordArray# dt 0# of wild2 { __DEFAULT ->
            case integerToInt (wordToInteger wild2) of wild4 { __DEFAULT ->
            I# wild4
            }
            }
        };
      Jn# ipv -> case underflowError of wild1 { }
    }

-- RHS size: {terms: 17, types: 8, coercions: 0, joins: 0/0}
notAnymore2 :: Int -> Int -> Int
notAnymore2
  = \ (a :: Int) (b :: Int) ->
      case notAnymore1 of { I# x ->
      case a of { I# y -> case b of { I# y1 -> I# (+# (+# x y) y1) } }
      }

-- RHS size: {terms: 14, types: 6, coercions: 0, joins: 0/0}
notAnymore2' :: Int -> Int -> Int
notAnymore2'
  = \ (a :: Int) (b :: Int) ->
      case a of { I# y -> case b of { I# y1 -> I# (+# (+# 3# y) y1) } }
```

So this one doesn't optimize as much. But this has nothing to do with `singletons`, but rather how GHC optimizes `Natural` numbers (refer to the relevant [Trac ticket](https://ghc.haskell.org/trac/ghc/ticket/14170)).

I won't dare to guess what `depIndex` does :)

**Comment by LeanderK** [comment]
well, I think that answers my question! 
I guess since you just took my examples that this is simpler than I thought and just depends on whether the type is known and ghc can simplify the expression itself and not some type-trickery.
