### ISSUE TITLE
SingI Instance for data-types

### ISSUE THREAD

**Issue by LeanderK** [goldfirere/singletons#303]
I have a fixed-length vector defined by:

```haskell
data Vec (n :: Nat) a = UnsafeMkVec { getVector :: V.Vector a }
    deriving Show
```
is there some th-function that generates SingI-Instances for Vec so that I can access the length etc.?

**Comment by LeanderK** [comment]
What I want to write is something like this:

```haskell
class InitRandom a where
   init :: MonadRandom m => Sing a -> m a
```

**Comment by RyanGlScott** [comment]
If you're looking for something that _only_ generates `SingI` instances, the answer is no.

If you're looking for something that will generate `SingI` instances and some other things, the answer is... yes (sort of). There does exist the function [`genSingletons`](https://hackage.haskell.org/package/singletons-2.4.1/docs/Data-Singletons-TH.html#v:genSingletons) which, among other things, will generate `SingI` instances.

That being said, the code that `genSingletons` would generate for `Vec` wouldn't typecheck, as you have a type parameter that isn't of kind `Type`. See https://github.com/goldfirere/singletons/issues/150.

**Comment by LeanderK** [comment]
ok, can I write the instance by hand or is it a limitation of GHC?

**Comment by RyanGlScott** [comment]
You can certainly write `SingI` instances by hand in general—they follow a pretty predictable pattern. For instance:

```haskell
data Option a = None | Some a

data instance Sing (z :: Option a) where
  SNone :: Sing None
  SSome :: Sing a -> Sing (Some a)

instance SingI None where
  sing = SNone

instance SingI a => SingI (Some a) where
  sing = SSome sing
```

The real question is: how are you planning to give `Sing`/`SingI` instances for `Vector`? That's not a conventionally defined datatype (in the sense that it's not a simple ADT), so it's hard to imagine how that would work.

**Comment by LeanderK** [comment]
I think I confused myself with all these types 😀

**Comment by LeanderK** [comment]
I'll close it because the code above doesn't make sense, or at least is not what I want to do.

**Comment by RyanGlScott** [comment]
What may interest you is the idea of parameterizing `Vec` by whether you're using it at the type level or not. For instance, you could conceivably do something like this:

```haskell
{-# LANGUAGE FlexibleInstances #-}
{-# LANGUAGE GADTs #-}
{-# LANGUAGE TypeFamilies #-}
{-# LANGUAGE TypeInType #-}
module Foo where

import Data.Kind
import Data.Singletons.Prelude
import qualified Data.Vector as V
import GHC.TypeNats

newtype Vec' (p :: Type -> Type) (n :: Nat) a = MkVec (p a)
  deriving Show

-- Value-level
type Vec  = Vec' V.Vector
-- Type-level
type PVec = Vec' []

data instance Sing (z :: PVec n a) where
  SMkVec :: Sing x -> Sing (MkVec x :: PVec n a)

instance SingKind a => SingKind (PVec n a) where
  type Demote (PVec n a) = Vec n (Demote a)
  fromSing (SMkVec sx) = MkVec $ V.fromList $ fromSing sx
  toSing (MkVec x) = withSomeSing (V.toList x) $ SomeSing . SMkVec

instance SingI x => SingI (MkVec x :: PVec n a) where
  sing = SMkVec sing
```

Of course, you'd still have to write all of this out by hand, and you'd need to expose the constructor to `Vec'`. But it's technically possible!

**Comment by LeanderK** [comment]
I think there is a misunderstanding!

**Comment by LeanderK** [comment]
This does not work, but I think it illustrates what I want to do.
I am sorry for not communicating clearer, I am still a bit confused myself.

```haskell
data instance Sing (Vec l a) where
    SVec :: Sing l -> Sing a -> Sing (Vec l a)

instance (SingI l, SingI a) => SingI (Vec l a) where
    sing = SVec sing sing

data DoorState = Opened | Closed | Locked
  deriving (Show, Eq)

stest = sing @Type @(Vec 13 Int)
```

everything revolves around this class

```haskell
class InitRandom a where
   init :: MonadRandom m => Sing a -> m a
```

**Comment by RyanGlScott** [comment]
I'm afraid I don't know how to respond, since a good chunk of the code in https://github.com/goldfirere/singletons/issues/303#issuecomment-364700800 is nonsense. For one thing, one never writes a `Sing` instance like this:

```haskell
data instance Sing (Vec l a) where ...
```

`Sing` instances are intended to be indexed by their kinds, so what you really wanted to write was:

```haskell
data instance Sing (z :: Vec l a) where ...
```

Also, the constructor itself makes little sense to me:

```haskell
    SVec :: Sing l -> Sing a -> Sing (Vec l a)
```

The return type of a `Sing` instance is usually of the form `Sing (C a1 ... an)`, where `C` is a constructor that inhabits the type you put into `Sing`'s kind.

**Comment by LeanderK** [comment]
I think I just solved it...

```haskell
data Vec (n :: Nat) a = UnsafeMkVec { getVector :: V.Vector a }
    deriving Show

data instance Sing (Vec l a) where
    SVec :: Sing l -> Sing (Vec l a)

instance (SingI l) => SingI (Vec l a) where
    sing = SVec sing

stest = sing @Type @(Vec 13 Int)
```
Does this make sense? At least it compiles!

**Comment by mstksg** [comment]
This is definitely not what you want.  A 'Sing a' should represent literally just 'a'.  What you wrote isn't really a singleton.

If you want a way to create a random value from the shape, you'd have something like:

```
class InitRandom a where
   init :: MonadRandom m => m a
```

And you could write an instance for your vector:

```
instance SingI n => InitRandom (Vec n a) where
   ...
```

**Comment by LeanderK** [comment]
I feel a bit stupid 😀

of course
```haskell
instance SingI n => InitRandom (Vec n a) where
   ...
```
would solve my problem.
