### ISSUE TITLE
Confusing error message 

### ISSUE THREAD

**Issue by LeanderK** [goldfirere/singletons#308]
I made a mistake and it took me some time to realize that I just forgot an arrow. I don't know whether this is fixable without some significant amount of work.

```haskell
$(promoteOnly [d|
    replaceAllGTypes :: (a -> Type -> a) [Type] -> [a] -> [a]
    replaceAllGTypes replace _ [] = []
    replaceAllGTypes replace (t:ts) (a:as) = (replace a t):(replaceAllGTypes replace ts as)
 |])
```

here is what I get:
```
src/V3/Error.hs:32:3: error:
    Illegal Haskell construct encountered:
headed by: DArrowT
applied to: [DVarT a_6989586621679139836,DAppT (DAppT DArrowT (DAppT (DAppT (DConT Data.Singletons.TyFun) (DAppT (DConT GHC.Prim.TYPE) (DConT GHC.Types.LiftedRep))) (DVarT a_6989586621679139836))) DStarT,DAppT (DConT GHC.Types.[]) (DAppT (DConT GHC.Prim.TYPE) (DConT GHC.Types.LiftedRep))]
   |
32 | $(promoteOnly [d|
   |   ^^^^^^^^^^^^^^^...

src/V3/Error.hs:32:3: error: Q monad failure
   |
32 | $(promoteOnly [d|
   |   ^^^^^^^^^^^^^^^...
Failed, no modules loaded.
```

**Comment by RyanGlScott** [comment]
Do you have a concrete suggestion for what `singletons` should report to help one figure out the issue? Do note that we're not doing any sort of typechecking of Template Haskell–quoted code, so all we can realistically do is perform a syntactic check over the input.

**Comment by LeanderK** [comment]
Hmm well, it seems like there is no way out. 
Is `replaceAllGTypes :: (a -> Type -> a) [Type] -> [a] -> [a]` even correct haskell syntax?

**Comment by RyanGlScott** [comment]
> Is `replaceAllGTypes :: (a -> Type -> a) [Type] -> [a] -> [a]` even correct haskell syntax?

It's syntactically correct, yes—you're applying the type `(a -> Type -> a)` to `[Type]`. Whether that typechecks is a much different story (spoiler: it doesn't).

**Comment by LeanderK** [comment]
thank you!
