### ISSUE TITLE
Singletons and Associated Type Families

### ISSUE THREAD

**Issue by LeanderK** [goldfirere/singletons#309]
I have a class with associated type families and I want to use them with `singletons`. Is there a somewhat elegant solution to use "singletonised" type-level code? `genDefunSymbols` doesn't work and writing them by hand would lead to a very complicate typeclass, which I want to avoid.

**Comment by RyanGlScott** [comment]
Without knowing what your exact use case is, I'd say that even if you wrote out the defunctionalization symbols by hand, you'd run into the same issue as in https://github.com/goldfirere/singletons/issues/198#issuecomment-308626145. So I'd say you're running into the same issue as #198.

**Comment by LeanderK** [comment]
Okay, well seems like I have to write the type-families by hand.
