### ISSUE TITLE
how to transform SingI-instances?

### ISSUE THREAD

**Issue by LeanderK** [goldfirere/singletons#310]
This might be obvious, but I am not able to figure it out. (Or I am doing something wrong, this is some critical, but complicated, piece of code).

I essentially need:
```haskell
doSomething :: forall s l. (s ~ SelectAll l) => Sing l -> o
doSomething snat = case proveThisIsCorrect @s @l (bunch of stuff) of
    Refl -> callAnother (sing @[Nat] @s)
```
but haskell complains
```
Could not deduce (SingI s) arising from a use of ‘sing’
```
select all is defined as (I had no Enum instance for Nat (singletons 2.3.1)?)
```haskell
$(promote [d|
    selectAll :: Nat -> [Nat]
    selectAll = go 0
        where
            go x 0 = []
            go x n = x : (go (x + 1) (n - 1))
    |])
```

**Comment by RyanGlScott** [comment]
OK. Is there some reason why you can't put a `SingI s` constraint in your type signature?

**Comment by LeanderK** [comment]
I think I made it more complicated than it is 😀. The essential problem:
I have this: `Sing l`
I need this: `Sing (SelectAll l)`

**Comment by RyanGlScott** [comment]
I'm still not sure what the bug is here. Why can't you just declare a `SingI (SelectAll l)` constraint`?

**Comment by LeanderK** [comment]
But can I satisfy a `SingI (SelectAll l)`?
I have another function `length :: g ts -> Sing (Length ts)` (l in my example was `(Length ts)`).

**Comment by RyanGlScott** [comment]
Unfortunately, this post is too vague for me to know what exactly the difficulty is. But the root of your problem appears to be:

```haskell
callAnother (sing @[Nat] @s)
```

In order for this to work, there must be a `SingI s` instance in scope. Full stop.

If that won't work for you, another alternative is to use:

```haskell
callAnother (sSelectAll snat)
```

Where:

```haskell
sSelectAll :: Sing l -> Sing (SelectAll l)
```

Would be generated if you had used `single` instead of `promote` in https://github.com/goldfirere/singletons/issues/310#issue-301523937.

**Comment by LeanderK** [comment]
the second part of your answer is the solution. I used `promote` because 

$(singletons [d|
    selectAll :: Nat -> [Nat]
    selectAll = go 0
        where
            go x 0 = []
            go x n = (x : (go (x + 1) (n - 1)))
    |])

complained about literals not being legal in patterns and later forgot this (of course) doesn't generate the stuff I want. Some If/else solved the problem.
