### ISSUE TITLE
Defunctionalization of symbolic functions

### ISSUE THREAD

**Issue by LeanderK** [goldfirere/singletons#315]
I am wondering what the reasoning behind the defunctionalization of symbolic functions is. Common operators like `.` get transformed into `.@#@$$$`, which bloats code and is unintuitive (well, more than `.$$$` 🙂). [Changes.md](https://github.com/goldfirere/singletons/blob/master/CHANGES.md) mentions:
>The suffix for defunctionalized names of symbolic functions (e.g., (+)) has changed. Before, the promoted type name would be suffixed with some number of dollar signs (e.g., (+$) and (+$$)) to indicate defunctionalization symbols. Now, the promoted type name is first suffixed with @#@ and then followed by dollar signs (e.g., (+@#@$) and (+@#@$$)). Adopting this conventional eliminates naming conflicts that could arise for functions that consisted of solely $ symbols

#203 and #197 talks about having problems with handling functions named`$`. My question is why it was chosen to append everything with `@#@` instead of for example "escaping" functions consisting solely of `$` (for example by appending `@#@`)?
Was is just simpler to do or is there a reason?
(I don't know whether some ghc-proposal is right around the corner to alleviate us from the pain of having all these symbols though...https://github.com/ghc-proposals/ghc-proposals/pull/52 seems relevant to me)

**Comment by RyanGlScott** [comment]
The short answer to your question is: uniformity.

The long answer is that our previous approach to promoted/singled infix names caused us a _lot_ of headaches. https://github.com/goldfirere/singletons/issues/29, https://github.com/goldfirere/singletons/issues/160#issuecomment-308519043, https://github.com/goldfirere/singletons/issues/172, and https://github.com/goldfirere/singletons/issues/197 are just a handful of the examples where either preceding promoting infix names with a `:` or special-casing names that contain `$`s caused undesirable behavior.

The new naming convention avoids that issue entirely, and moreover, is more consistent with how we promote prefix names. Whenever we come up with defunctionalization symbols for prefix names, we give them the three-character suffix `Sym`, followed by how many arguments they take. For example:

* `Sym0` (zero arguments)
* `Sym1` (one argument)
* `Sym2` (two arguments)
* etc.

Similarly, for defunctionalization symboms for infix names, we give them the three-character suffix `@#@`, followed by a symbol representation of how many arguments they take. For example:

* `@#@$` (zero arguments)
* `@#@$$` (one argument)
* `@#@$$$` (two arguments)
* etc.

Now we don't have to awkwardly special-case the defunctionalization symbols for functions that end with `$` (which is quite common).

I agree that defunctionalization symbols are a pain, and would gladly drop them in a heartbeat in exchange for something more pleasant like https://github.com/ghc-proposals/ghc-proposals/pull/52. But that day is not yet here, so until then, this is the best we can do.

**Comment by LeanderK** [comment]
makes sense. Thanks!
