### ISSUE TITLE
Should we continue maintaining the `Data.Promotion.Prelude.*` namespace?

### ISSUE THREAD

**Issue by RyanGlScott** [goldfirere/singletons#341]
Currently, for every module in the `Data.Singletons.Prelude.*` namespace, we have a counterpart in the `Data.Promotion.Prelude.*` namespace which exports the exact same things except for the singled definitions. @goldfirere and I have wondered whether this double-duty treatment is even worthwhile, since:

1. It requires lots of work to keep the two in sync.
2. The number of definitions that we can promote but not single is quite small. Off the top of my head, I can only think of [these functions in `Data.Promotion.Prelude.List`](https://github.com/goldfirere/singletons/blob/56e4676f4ba68dc995cf9a644c13d489ffba366e/src/Data/Promotion/Prelude/List.hs#L238-L308). But we could just as well define them in `Data.Singletons.Prelude.List`, and include a Haddock blurb to explain that they are only promoted, and not singled.
3. The benefits are questionable. Are folks even using the `Data.Promotion.Prelude.*` namespace?

@goldfirere was looking into finding a quantitative result to that last question. (Do you have one now?)

**Comment by goldfirere** [comment]
The following packages are the only Hackage packages with `Data.Promotion` imports: type-natural, ghc-exactprint, ixshader, lol-apps, mathflow, servant-zeppelin-swagger. That's it. Of course, the migration for these packages is easy.

I personally don't think it's worth it to keep supporting the `Data.Promotion` namespace.
