### ISSUE TITLE
"self-contained" dependent datatypes possible?

### ISSUE THREAD

**Issue by LeanderK** [goldfirere/singletons#346]
If I write something like:

```haskell
data Option a n = First [a] | Second n
```
(btw: the second thing should be a Nat...what is the recommended way to solve this? type synonyms?)

the SingI instances are now defined like:

```haskell
instance forall n1 a (n2 :: [a]).
         SingI n2 =>
         SingI ('First n2)
```

which I can't use, since I want to abstract over something I depend on, like:

```haskell
class ValidThing a where
     length :: SingI a => Nat
```

I can't implement length for `Option a n`, since I need `SingI (as :: [a])`.
I also can't place a dictionary in the definition. Is there a way to solve this? I want to dependend on `Option` and all it's fields in a generic way.

**Comment by mstksg** [comment]
What is `ValidThing` doing here?  What is the kind of `a` intended to be?  And what exactly do you mean by `ValidThing a n`, which appears to be a kind error?

**Comment by mstksg** [comment]
In what way are you defining an `Option a n` to have length?  Is it the length of the items in `First`?  Maybe can you provide an example of an instance of `ValidThing`, so I can know how it is intended to interact with something like `Option` ?

**Comment by LeanderK** [comment]
ah, I see. `data Option a n = First [a] | Second n` should be `data Option a = First [a] | Second Nat` (I am not sure right now why I placed the `n` there...I think there was trouble promoting types with Nat?)

**Comment by mstksg** [comment]
Ah.  Yes, at this point you do need to keep it as a type variable; your type would be `Option a Natural` and your kind would be `Option a Nat`, and `SingKind` etc. will respect this.

If you want to return either the length or the value of the `Nat`, you can do something like:

```
class ValidThing a where
    length :: Int

instance SingI o => ValidThing (o :: Option k Nat) where
    length = case sing @_ @o of             -- or `sing @o` in HEAD
      SFirst xs -> fromSing (sLength xs)
      SSecond n -> fromIntegral (fromSing n)
```

**Comment by LeanderK** [comment]
I think my simple mistake was instead of `(o :: Option k Nat)` to make an instance for `Option k Nat`.

**Comment by mstksg** [comment]
Right, you can even do this without the `SingI` or the singletons library, manually, which might help illustrate what's really going on:

```haskell
instance ValidThing ('First '[]) where
    length = 0

instance ValidThing ('First as) => ValidThing ('First (a ': as)) where
    length = 1 + length @('First as)

instance KnownNat n => ValidThing ('Second n) where
    length = natVal (Proxy @n)
```

**Comment by mstksg** [comment]
What the singletons library gives you is the ability to bring the pattern matches from the instance declaration level and unite them together at the method definition level.
