### ISSUE TITLE
singletons generates ill-kinded type signature for class method

### ISSUE THREAD

**Issue by RyanGlScott** [goldfirere/singletons#358]
The following code fails to single with `singletons-2.4.1` and HEAD:

```haskell
{-# LANGUAGE GADTs #-}
{-# LANGUAGE InstanceSigs #-}
{-# LANGUAGE ScopedTypeVariables #-}
{-# LANGUAGE TemplateHaskell #-}
{-# LANGUAGE TypeFamilies #-}
{-# LANGUAGE TypeInType #-}
{-# LANGUAGE UndecidableInstances #-}
module Bug where

import Data.Kind
import Data.Singletons.TH

$(singletons [d|
  class C (f :: k -> Type) where
    method :: f a
  |])

$(singletons [d|
  instance C [] where
    method = []
  |])
```
```
$ /opt/ghc/8.4.3/bin/ghc Bug.hs -ddump-splices
[1 of 1] Compiling Bug              ( Bug.hs, Bug.o )
Bug.hs:(13,3)-(16,4): Splicing declarations
    singletons
      [d| class C_a2X8 (f_a3qK :: k_a2Xa -> Type) where
            method_a2X9 :: f_a3qK a_a3qL |]
  ======>
    class C_a6d2 (f_a6d5 :: k_a6d4 -> Type) where
      method_a6d3 :: f_a6d5 a_a6d6
    type MethodSym0 = Method
    class PC (f_a6d5 :: k_a6d4 -> Type) where
      type Method :: f_a6d5 a_a6d6
    class SC (f_a6d5 :: k_a6d4 -> Type) where
      sMethod :: Sing (MethodSym0 :: f_a6d5 a_a6d6)
Bug.hs:(18,3)-(21,4): Splicing declarations
    singletons
      [d| instance C [] where
            method = [] |]
  ======>
    instance C GHC.Types.[] where
      method = []
    type family Method_6989586621679034099_a6k4 :: [a_a6d6] where
      Method_6989586621679034099_a6k4 = '[]
    type Method_6989586621679034099Sym0 =
        Method_6989586621679034099_a6k4
    instance PC [] where
      type Method = Method_6989586621679034099Sym0
    instance SC [] where
      sMethod ::
        forall (a_a6d6 :: []). Sing (MethodSym0 :: f_a6d5 a_a6d6)
      sMethod = singletons-2.4.1:Data.Singletons.Prelude.Instances.SNil

Bug.hs:18:3: error:
    • Expecting one more argument to ‘[]’
      Expected a type, but ‘[]’ has kind ‘* -> *’
    • In the kind ‘[]’
      In the type signature:
        sMethod :: forall (a_a6d6 :: []).
                   Sing (MethodSym0 :: f_a6d5 a_a6d6)
      In the instance declaration for ‘SC []’
   |
18 | $(singletons [d|
   |   ^^^^^^^^^^^^^^...
```

Two important things to note:

* This relies on the declaration for `instance C []` instance being in a separate splice from the declaration for `class C f`. In other words, the bug appears to have something to do with the way that `singletons` is reifying `SC`.
* `f` having kind `k -> Type` is also important, because changing it to `Type -> Type` makes the bug go away.

**Comment by goldfirere** [comment]
Instead of slurping the `cls_tvbs` from the quantified variables, can we look at the arguments to, e.g., `SC`? That would seem to work in all cases, I think.

**Comment by RyanGlScott** [comment]
I'm not sure what you mean by "look at the arguments". Can you give a more detailed example of how this would work?

**Comment by goldfirere** [comment]
We have

```
sMethod :: forall k (f :: k -> Type). SC f => forall (a :: k). Sing (MethodSym0 :: f a)
```

Currently, you're describing that we consider (wrongly) `k` and `f` to be the `cls_tvbs` because they're quantified before the constraint. However, we can look at the constraint `SC f` and know that `SC`'s arguments are the `cls_tvbs`. (I know they're not `tvbs` there, but we can easily extract the variables.)

Or have I missed something?

**Comment by RyanGlScott** [comment]
Even if we actually mapped `f |-> []` correctly, that still wouldn't be enough to generate something which kind-checked. We'd instead generate:

```haskell
sMethod :: forall (a :: k). Sing (MethodSym0 :: [a])
```

Here, the kind of `a` is too general (it should actually be `Type`).

**Comment by goldfirere** [comment]
Ah, yes. Perhaps @mynguyenbmc's work on visible kind application (which includes an update to TH) will solve the problem. I believe she'll be posting her work for review soon.

**Comment by RyanGlScott** [comment]
Now that I think about it, I have to wonder: why are we giving singled instance methods type signatures in the first place? As far as I can tell, they're completely unnecessary, since GHC is more than capable of inferring these types by itself. Plus, it's not like we're using them to bring type variables into scope, since that's a role that's already served by pattern signatures.

As evidence for this claim, I commented out singled instance method type signatures in `Data.Singletons.Single`, and all the tests still pass (modulo generating less code). Oh, and it also fixes the original program, which is nice too.

**Comment by goldfirere** [comment]
Well, it sounds like you've solved this then. I think we needed the signatures before TH could deal with pattern signatures that bound variables.

**Comment by goldfirere** [comment]
Ugh. It looks like we need to be able to bind type variables explicitly....

**Comment by RyanGlScott** [comment]
Indeed. My next thought was "well what if we just use kinds in the pattern signatures"? Something like:

```haskell
    instance SC [] where
      sMethod (sX :: Sing (x :: a))
        = case sX of { _ -> sX } ::
            Sing (Case x x :: [a])
```

Would work for that example, I think, but that only works because `a` happens to be mentioned in the first (explicit) argument in the type of `method`. If there was a variable that was only mentioned in the _result_ type of `method`, I'm worried that this approach might fall down somewhere.

I agree that in order to fix this robustly, we'll likely need visible type variable patterns. I'll go ahead and park this ticket for now pending further developments on GHC's side.

**Comment by RyanGlScott** [comment]
Hold on, I just thought of another approach which might bypass this issue entirely. I was so caught up in trying to _remove_ `InstanceSigs` that I never thought to wonder "what if I add _more_ `InstanceSigs`"? In particular, if you wrote:

```haskell
$(singletons [d|
  instance C [] where
    method :: [a]
    method = []
  |])
```

Then instead of trying to look up the type of `method` elsewhere, we could simply single the `method :: [a]` instance signature directly and use that. This way, we can have fine-tuned control over the kinds of each type variable, and avoid the dreaded bogus substitution entirely!

Of course, this wouldn't be a fix for the underlying bogus substitution. But it is a workaround, and a pretty solid one too. Plus, we'd be able to support another GHC language feature, which is a nice bonus.

Does that sound like a reasonable approach? I have a working prototype of this feature at the moment (that I'm currently testing on my upstream code which originally triggered this issue), so if you like what you see here, then we can get it in before the final 2.5 release.

**Comment by goldfirere** [comment]
Could I summarize your proposal as "Every instance of a poly-kinded type class must have signatures on all methods" (if we are to single it)? That's a cheap-and-cheerful way to make quick progress, and it's easy to specify and conform to.
