### ISSUE TITLE
Dodgy special-casing for String in promoteType

### ISSUE THREAD

**Issue by RyanGlScott** [goldfirere/singletons#361]
While investigating #358, I uncovered an oddity in the way `promoteType` is implemented. In particular, there's some dubious special-casing for `String` here:

https://github.com/goldfirere/singletons/blob/c776637d11055ac1c47ddf7e96c7ed9067687041/src/Data/Singletons/Promote/Type.hs#L43-L45

Here is what is dubious about it:

* This case is very unlikely to ever be reached in practice. That's because `singletons` is quite eager to expand type synonyms when possible, which means that you'll usually pass types to `promoteType` which mention `[Char]` instead of `String`.
* Even if this case were reached, what is it doing here? We certainly don't have any special case that turns, say, `Natural` into `Nat`, so it feels odd to turn `String` into `Symbol`. (And for that matter, shouldn't it be that we turn `Text` into `Symbol` instead?)

I can think of two possible options here:

1. Remove this special case entirely.
2. Fix the special case to turn `Text` into `Symbol`, and add a corresponding case for turning `Natural` into `Nat`.

**Comment by goldfirere** [comment]
That code likely predates `Natural` and quite possibly singletons's attempts at synonym expansion. I'm not wedded to it -- remove the line if it's getting in your way.

**Comment by RyanGlScott** [comment]
It's not actively getting in my way _per se_, but it does smell odd.

Speaking of odd smells, there's another case in `promoteType` that I just noticed which really makes my nose curl:

https://github.com/goldfirere/singletons/blob/5f867ace69ab12fc98fa71df1cdf7985afa3cb91/src/Data/Singletons/Promote/Type.hs#L53

Why can't we promote type-level literals? Isn't promoting them a no-op? Currently, this prevents this (relatively obscure) code from working:

```haskell
$(promote [d|
  f :: Proxy 1 -> Proxy 2
  f Proxy = Proxy
  |])
```

**Comment by goldfirere** [comment]
That looks like a historical accident to me. I see no trouble promoting literals like that.
