### ISSUE TITLE
How to generate singletons for types involving `Text`/`Symbol`?

### ISSUE THREAD

**Issue by dspies-leapyear** [goldfirere/singletons#370]
Question posted to StackOverflow: https://stackoverflow.com/q/53074944/403875

I can't find any documentation about how to work with `Symbol`s and `Singleton`s. It's all been trial and error so far.
Some help would greatly be appreciated. Thanks!

**Comment by RyanGlScott** [comment]
There is a `Demote Symbol = Text` instance, but `Text` values don't automatically promote to `Symbol`s yet due to #82.

If you want to use `Text` and `Symbol` within the same code, your best bet is to use the `IsString` class:

```haskell
{-# LANGUAGE OverloadedStrings #-}
{-# LANGUAGE ... #-}

$(singletons
  [d| foo :: IsString s => s
      foo = "bar"
    |])
```

Does this answer your questions?

**Comment by RyanGlScott** [comment]
I'll go ahead and close this issue, since I think the main point has been addressed. Please reopen if you disagree.
