### ISSUE TITLE
Generate SingI instances for TyCon{N} once-and-for-all using QuantifiedConstraints

### ISSUE THREAD

**Issue by RyanGlScott** [goldfirere/singletons#381]
In https://github.com/goldfirere/singletons/pull/285#issuecomment-366570150, I lamented the fact that the data family definition of `TyCon` prevented me from defining catch-all `SingI` instances for applications of `TyCon{N}` to type constructors. Why? Consider the following example:

```haskell
data family TyCon :: (k1 -> k2) -> unmatchable_fun
type family ApplyTyCon (f :: k1 -> k2) (x :: k1) :: k3 where
  ApplyTyCon (f :: k1 -> k2 -> k3) x = TyCon (f x)
  ApplyTyCon f x                     = f x
type instance Apply (TyCon f) x = ApplyTyCon f x
type TyCon1 = (TyCon :: (k1 -> k2)       -> (k1 ~> k2))
type TyCon2 = (TyCon :: (k1 -> k2 -> k3) -> (k1 ~> k2 ~> k3))
-- etc.

instance (forall a. SingI a => SingI (f a)) => SingI (TyCon1 f) where
  sing = SLambda $ \(x :: Sing a) -> withSingI x $ sing @(f a)
```

This gives the rather inscrutable error message:

```
$ ghc-cq/inplace/bin/ghc-stage2 --interactive -fprint-explicit-kinds Bug2.hs
GHCi, version 8.5.20180128: http://www.haskell.org/ghc/  :? for help
Loaded GHCi configuration from /home/rgscott/.ghci
[1 of 1] Compiling SingIForTyCons   ( Bug2.hs, interpreted )

Bug2.hs:76:52: error:
    • Couldn't match type ‘ApplyTyCon k2 k1 k2 f t’ with ‘f t’
      Expected type: Sing k2 (ApplyTyCon k2 k1 k2 f t)
        Actual type: Sing k2 (f t)
    • In the second argument of ‘($)’, namely ‘sing @_ @(f a)’
      In the expression: withSingI x $ sing @_ @(f a)
      In the second argument of ‘($)’, namely
        ‘\ (x :: Sing a) -> withSingI x $ sing @_ @(f a)’
    • Relevant bindings include
        x :: Sing k1 t (bound at Bug2.hs:76:22)
        sing :: Sing (TyFun k1 k2 -> *) (TyCon1 k1 k2 f)
          (bound at Bug2.hs:76:3)
   |
76 |   sing = SLambda $ \(x :: Sing a) -> withSingI x $ sing @(f a)
   |                                                    ^^^^^^^^^^^^^^
```

Unfortunately, we can't know here that `ApplyTyCon f t` should reduce to `f t`, so GHC gets stuck. Bummer.

At the time, I gave up and decided that I'd never make progress on this unless [GHC Trac #14645](https://ghc.haskell.org/trac/ghc/ticket/14645) were fixed. But it turns out that we don't need to wait! All we have to do is tweak our instance slightly:

```haskell
instance forall k1 k2 (f :: k1 -> k2).
         ( forall a. SingI a => SingI (f a)
         , (ApplyTyCon :: (k1 -> k2) -> (k1 ~> k2)) ~ ApplyTyConAux1
         ) => SingI (TyCon1 f) where
  sing = SLambda $ \(x :: Sing a) -> withSingI x $ sing @(f a)
```

Now it works! It turns out that we just needed to guide GHC along a bit with an equality constraint.

OK, that's clearly not the full story, since `ApplyTyCon` appears to be unsaturated in that instance. But with a little reshuffling of `ApplyTyCon`'s definition, this is actually quite possible:

```haskell
type family ApplyTyCon :: (k1 -> k2) -> (k1 ~> unmatchable_fun) where
  ApplyTyCon = (ApplyTyConAux2 :: (k1 -> k2 -> k3) -> (k1 ~> unmatchable_fun))
  ApplyTyCon = (ApplyTyConAux1 :: (k1 -> k2)       -> (k1 ~> k2))
type instance Apply (TyCon f) x = ApplyTyCon f @@ x

data ApplyTyConAux1 :: (k1 -> k2) -> (k1 ~> k2)
data ApplyTyConAux2 :: (k1 -> k2) -> (k1 ~> unmatchable_fun)
type instance Apply (ApplyTyConAux1 f) x = f x
type instance Apply (ApplyTyConAux2 f) x = TyCon (f x)
```

Now `ApplyTyCon` has no visible arguments, so we are free to unsaturate `ApplyTyCon` as much as we want.

This approach also scales to `TyCon2`, `TyCon3`, etc. I've pushed an implementation of these ideas to the `singi-once-and-for-all` branch. Does this seem like a sensible idea?

**Comment by goldfirere** [comment]
Other than yet another layer of indirection, I don't see any downsides here. Do you?
