### ISSUE TITLE
Is unsafeCoerce necessary?

### ISSUE THREAD

**Issue by howtonotwin** [goldfirere/singletons#388]
When

```haskell
data Nat = Z | S Nat
```

is singletonized, `singletons` currently generates

```haskell
type Sing = (Sing :: Nat -> Type)
data instance Sing (n :: Nat) where
    SZ :: SNat 'Z
    SS :: SNat n -> SNat ('S n)
instance SingI 'Z where sing = SZ
instance SingI n => SingI ('S n) where sing = SS sing
```

To convert `SingI n -> Sing n` is a contant-time operation; you simply unwrap the dictionary with `sing`. To convert `Sing n -> SingI n`, you really have to walk the entire structure `n` to rebuild the dictionary. Instead of doing this, `singletons` actually uses `unsafeCoerce`. This isn't really an issue, but it does make me (and I'm sure you'll agree) rather uncomfortable. Why do these powerful ideas, singletons and typeclasses, break down when they are put together?

The following is a bit of a pipe dream, placed here more for discussion than anything else. It's a whole lot of work to eliminate a single `unsafeCoerce`, and it will probably break down a lot more often. Still, would it be possible to rework `singletons` to work as follows?

```haskell
-- currently called SingInstance
data Sing (a :: k) = SingI a => Sing
-- currently called Sing
data family SingDef :: k -> Type
class SingI (a :: k) where singDef :: SingDef a
toSingDef :: Sing a -> SingDef a
toSingDef Sing = singDef

data instance SingDef (n :: Nat) where
    SZF :: SingDef 'Z
    -- subterms are now represented as SingI contexts, not Sing values
    SSF :: SingI n => SingDef ('S n)
instance SingI 'Z where singDef = SZF
instance SingI n => SingI ('S n) where singDef = SSF
type SNat = (Sing :: Nat -> Type) -- but Sing is still the main, user-facing data type!


-- with my (dormant) GHC proposal (More Symmetrical Pattern Synonyms)
-- pattern SZ :: forall (n :: Nat). () => (n ~ 'Z) => SNat n
-- pattern SZ <- (toSingDef -> SZF)
--     where SZ = Sing
-- pattern SS :: forall (n :: Nat). () => forall (m :: Nat). (n ~ 'S m) => SNat m -> SNat n
-- pattern SS Sing <- (toSingDef -> SSF)
--    where SS Sing = Sing
-- in general I guess it's
-- pattern Constructor Sing{num_subterms} <- (toSingDef -> ConstructorF)
--    where Constructor Sing{num_subterms} = Sing
-- real implementation is horrifying:
-- SingDef, but with an infuriatingly small difference
-- can also be written as a GADT
data PatternSynonymsAreVeryAnnoying n = (n ~ 'Z) => IsZ
                                      | forall m. (n ~ 'S m) => IsS (SNat m)
matchNat :: SNat n -> PatternSynonymsAreVeryAnnoying n
matchNat n = case toSingDef n of
                   SZF -> IsZ
                   SSF -> IsS Sing
pattern SZ :: forall (n :: Nat). () => (n ~ 'Z) => SNat n
pattern SZ <- (matchNat -> IsZ)
    where SZ = Sing
pattern SS :: forall (n :: Nat). () => forall (m :: Nat). (n ~ 'S m) => SNat m -> SNat n
pattern SS m <- (matchNat -> IsS m)
    where SS Sing = Sing
{-# COMPLETE SZ, SS #-}
```

`SingDef` is not meant for general use; it defines the singletons on a "middle ground," and then all real code refers to one of the extremes, `Sing` or `SingI`. Converting `Sing ~> SingI` is now constant time (peel off a `Sing` constructor), and so is its inverse. All that's left is to pray to [insert&nbsp;deity(s)&nbsp;here] that GHC manages (or learns) to unbox the dictionaries inside `Sing` and `SingDef`. I would guess that, since `SZ` and `SS` have their original signatures, that the existing code for singletonizing value definitions doesn't need to change a lick, which gives me some confidence that this can work in general.

**Comment by int-index** [comment]
I like it, and I've used a similar trick in the past for other GADTs. For example, to know a spine of a type-level list one could define

```
data Spine xs where
  SpineZ :: Spine '[]
  SpineS :: Spine xs -> Spine (x : xs)
```

and then a class to build and pass it implicitly

```
class Known a where
  known :: a

instance Known (Spine '[]) where
  known = SpineZ

instance Known (Spine xs) => Known (Spine (x : xs)) where
  known = SpineS known
```

This encoding requires helper functions to get `KnownSpine` evidence from `Spine`:

```
data Dict c where
  Dict :: c => Dict c

spineToDict :: Spine xs -> Dict (Known (Spine xs))
spineToDict SpineZ = Dict
spineToDict (SpineS s) =
  case spineToDict s of
    Dict -> Dict
```

And, unfortunately, `spineToDict` is linear in the size of the spine. So what I did was to change the definition of `Spine` to

```
data Spine xs where
  SpineZ :: Spine '[]
  SpineS :: Known (Spine xs) => Spine (x : xs)
```

And this simplifies both the inductive instance of `Known` and the inductive clause of `spineToDict`:

```
instance Known (Spine xs) => Known (Spine (x : xs)) where
  known = SpineS

spineToDict :: Spine xs -> Dict (Known (Spine xs))
spineToDict SpineZ = Dict
spineToDict SpineS = Dict
```

If I understand correctly, @howtonotwin proposes to generalize this technique to all singleton types. This sounds like a great idea to me.

**Comment by sweirich** [comment]
I also support this change. Even though the unsafeCoerce doesn't bother me, it is useful to already have the implicit version of the singleton argument available. 

However, note that this approach requires proxies to enable binding the type variables in pattern matching. For example, with the example above
```
data Spine xs where
  SpineZ :: Spine '[]
  SpineS :: Known (Spine xs) => Proxy x -> Proxy xs -> Spine (x : xs)
```

Without the proxies, x and xs cannot be bound in the pattern match below.
```
f :: Spine xs -> ...
f (SpineS (p1 :: Proxy x) (p2::Proxy xs))  = ... 
f SpineZ = ...
```

(There is a ghc-proposal to extend ghc to fix this, but I don't think it has been implemented yet.)

**Comment by RyanGlScott** [comment]
It looks like there are two distinct but related things being pursued here:

1. Eliminating a use of `unsafeCoerce` from `singletons`.
2. Having a convenient interface for bringing `SingI` constraints into scope when pattern-matching.

As far as (1) goes, I can't say I'm terribly bothered by the use of `unsafeCoerce` either. At least, it doesn't bother me any more than other `reflection`-based APIs that use `unsafeCoerce` under the hood, such as [`withTypeable`](https://hackage.haskell.org/package/base-4.12.0.0/docs/Type-Reflection.html#v:withTypeable). Moreover, redesigning `singletons` is not the only way we could remove the use of `unsafeCoerce`—there has been talk of allowing GHC to [safely coerce](https://github.com/ghc-proposals/ghc-proposals/pull/69) between `Sing` and `SingI`, for instance.

On the topic of (2), I'm somewhat on the fence. There's a question to be asked about whether "explicit-style" singletons (e.g., `SS :: Sing n -> Sing (S n)`) or "implicit-style" singletons (e.g., `SS :: SingI n => Sing (S n)`) should be the main data type in the API. In today's `singletons`, the explicit style is used as the main data type, and the implicit style can be recovered by way of pattern synonyms. One way to do this is to use the [`Sing`](https://hackage.haskell.org/package/singletons-2.5.1/docs/Data-Singletons.html#v:Sing) pattern synonym:

```hs
f :: SNat n -> SingInstance n
f SZ        = SingInstance
f (SS Sing) = SingInstance
```

Alternatively, one can define a [pattern synonym on top of `SS`](https://github.com/goldfirere/singletons/issues/274) to bring its `SingI` dictionary into scope without additional fuss:

```hs
gen :: Sing (a :: k) -> (Sing a, SingInstance a)
gen sing = (sing, singInstance sing)

pattern SS_ :: () => forall n. (S n ~ sn, SingI n) => Sing n -> Sing sn
pattern SS_ n <- SS (gen -> (n, SingInstance))
  where SS_ n =  SS n

f :: SNat n -> SingInstance n
f SZ    = SingInstance
f SS_{} = SingInstance
```

@howtonotwin proposes to invert this state of affairs by making implicit-style singletons the main data type and defining pattern synonyms to recover explicit-style singletons. I'm sure that this would be possible, but I wonder if the payoff would be worth it. Admittedly, I'm quite biased in that I almost exclusively use explicit `Sing`s and rarely reach for `SingI`.

There's also a practical concern that GHC's exhaustivity checking for pattern synonyms (even those with `COMPLETE` sets) is [quite buggy in practice](https://trac.haskell.org/trac/ghc/query?status=infoneeded&status=merge&status=new&status=patch&status=upstream&keywords=~PatternMatchWarnings+PatternSynonyms&order=priority), so whichever approach gets relegated to a pattern synonym encoding will be punished with crappier coverage checking. I'm under the general impression that explicit-style singletons are used more widely than implicit ones, so I'm a bit hesitant to make explicit singletons only accessible with pattern synonyms for this reason.

**Comment by howtonotwin** [comment]
Consider

```haskell
$(genSingletons [d|data Nat = Z | S Nat|])
data Vect (n :: Nat) (a :: Type) where
     VNil :: Vect Z a
     VCons :: a -> Vect n a -> Vect (S n) a
```

It is known that, metaphorically `forall n. Applicative (Vect n)`. How do we write this instance? Well, we are forced to ask that `SingI n`:

```haskell
instance SingI n => Applicative (Vect n) where
    pure = _hmm
    (<*>) = _easy
```

There are two ways to write `pure`:

* Explicit style

    ```haskell
    pure (x :: a) = pureImpl (sing @n)
      where pureImpl :: forall n. Sing n -> Vect n a
            pureImpl SZ = VNil
            pureImpl (SS m) = VCons x (pureImpl m)
    ```

    I write this, and I become sad because it's ugly.

* Implicit style

    ```haskell
    pure x = case sing @n of
                  SZ -> VNil
                  SS Sing -> VCons x (pure x)
                  --  ^ also a pattern synonym, though less likely to break
    ```

    I write this, and I become sad because it only works due to a hack that relies on an implementation detail of the compiler.

The upshot is that the Haskell language essentially requires that the implicit case be as streamlined as possible. Typeclass instances are not, conceptually, values, therefore they are harder to manipulate. When the explicit mode is the preferred one, you get conundrums like the above whenever the language forces you to use the implicit mode. If the implicit mode is preferred, the pattern synonyms fully recover the explicit mode (they have exactly the same signature as the GADT constructors), but it also eliminates my sadness, as the implicit form above now works entirely within the language. I realize that not everybody is uncomfortable with the `unsafeCoerce`, but  why should we break out of the language to do something when Haskell is powerful enough to encode it while staying within the rules?

@sweirich I don't think the `Proxy`s are required. As stated, `SingDef` is only really needed to define `SingI` and the pattern synonyms. The user shouldn't ever have to touch a `SingDef`, and the pattern synonyms, through all the equality evidence being bandied about, don't need any `Proxy`s. If they were necessary, [`Proxy#`s](https://hackage.haskell.org/package/ghc-prim-0.5.3/docs/GHC-Prim.html#t:Proxy-35-) could probably be used.

**Comment by RyanGlScott** [comment]
> I write this, and I become sad because it only works due to a hack that relies on an implementation detail of the compiler.

I'm not convinced by this argument, as the reason that _anything_ works in `singletons` works is due to implementation details of GHC. I don't find the use of `unsafeCoerce`-based reflection any more saddening than, say, our reliance on ~270 different language extensions or particular quirks in the ways GHC's kind inference engine works. In other words, we broke out of the language a long time ago, and I don't think that's a bad thing.

**Comment by howtonotwin** [comment]
> I don't find the use of unsafeCoerce-based reflection any more saddening than, say, our reliance on ~270 different language extensions or particular quirks in the ways GHC's kind inference engine works.

I'm going to state that I disagree with this viewpoint, on the grounds that I believe that most of the language extensions / kind inference quirks etc. have well-defined behaviors that are sanctioned by the specification of GHC. The `unsafeCoerce` trick, as long as it uses `unsafeCoerce` and not some specific GHC feature designed to replace it, is just a hack.

But anyway, I've sat down to hack at `singletons`, as this idea an interesting one that deserves exploration even if it is never used here, and I've quickly discovered it *can't* be used here for the foreseeable future. The reason is that `SLambda` becomes one-way! We're forced to write

```haskell
newtype instance SingDef (f :: k1 ~> k2) =
  SLambdaF { applySingDef :: forall t. Sing t -> Sing (f @@ t) }
 
pattern SLambda :: forall k1 k2 (f :: k1 ~> k2). (forall t. Sing t -> Sing (f @@ t)) -> Sing f
pattern SLambda { applySing } <- (toSingDef -> SLambdaF applySing)
```

with no direct way to manufacture `SLambda`s. Essentially, this enforces "one truth" for functions; the only way to get a `Sing (f :: a ~> b)` is to "freeze" one from the `SingI f` instance. So, all of `singFun1`..`8` blow up, and instead of writing `sMap (singFun1 @NotSym0 sNot)`, you *have* to write `sMap (Sing @NotSym0)` (which exists today). The `SingKind` instance blows up even more spectacularly. Very interesting, but that this happened so immediately seems to point out that the structural changes induced by this idea (though, I think they might be good ones) mean that it has absolutely no chance of existing in the `singletons-2` series, or maybe ever. I was hoping it would be more controlled.

**Comment by goldfirere** [comment]
There is another way to do this, and it was done way back in singletons-0: put both implicit and explicit singletons at every layer of the data structure. Unfortunately, this makes datatypes exponentially larger. Other than that little snag, it works beautifully.

The reason I reached for `unsafeCoerce` is that one use of it converted an exponential algorithm to a linear one, which is a significant enough win for me.
