### ISSUE TITLE
macOS `sed` fails to remove "singletons-x.x" prefix

### ISSUE THREAD

**Issue by int-index** [goldfirere/singletons#391]
Judging by the test output, it looks like this rule doesn't fire: https://github.com/goldfirere/singletons/blob/ea5787091689e857ea7c71a89ac2823644e493bd/tests/SingletonsTestSuiteUtils.hs#L178

Curiously, it seems like every other rule works alright.

This issue is specific to macOS `sed`.

**Comment by RyanGlScott** [comment]
I wonder if this is a quirk of how macOS `sed` handles the `+` character. If https://stackoverflow.com/a/4453890/1567086 is to be believed, then passing the `-E` flag makes `+` behave properly on macOS. Does that make a difference?

**Comment by int-index** [comment]
Adding `-E` not only has not solved this issue, but made it worse and now some other rules don't fire either.

Besides, I really don't think `ifdef darwin_HOST_OS` is a good check for the `sed` version, as I can use the GNU sed on macOS via `nixpkgs` or `brew`.

Why don't we write Haskell code to do this search-and-replace instead of `sed` regular expressions? We already use `turtle` in the `accept-all` util, might as well use it here.

**Comment by RyanGlScott** [comment]
> Adding `-E` not only has not solved this issue, but made it worse and now some other rules don't fire either.

Darn. I was hoping that there was a quick-and-easy fix that we could apply the interim, but alas, nothing is ever easy.

I certainly agree that switching over from `sed` to a native Haskell solution is the right direction.

**Comment by int-index** [comment]
If you don't mind `turtle` as a dependency I'll go ahead and implement it.

**Comment by RyanGlScott** [comment]
Go for it! :)
