### ISSUE TITLE
Consider promoting type class instance contexts

### ISSUE THREAD

**Issue by RyanGlScott** [goldfirere/singletons#396]
If you try to promote a type class instance, as in the following example:

```hs
{-# LANGUAGE DataKinds #-}
{-# LANGUAGE GADTs #-}
{-# LANGUAGE PolyKinds #-}
{-# LANGUAGE TemplateHaskell #-}
{-# LANGUAGE TypeFamilies #-}
{-# LANGUAGE UndecidableInstances #-}
{-# OPTIONS_GHC -ddump-splices #-}
module Foo where

import Data.Functor.Identity
import Data.Singletons.Prelude.Identity
import Data.Singletons.TH

$(promoteOnly [d|
  class C a where
    m :: a -> Bool

  instance C a => C (Identity a) where
    m (Identity x) = m x
  |])
```

You'll currently generate the following code (simplified):

```hs
class PC (a :: Type) where
  type M (arg :: a) :: Bool

instance PC (Identity a) where
  type M ('Identity x) = M x
```

There's nothing explicitly _wrong_ about this code, but it is a bit strange. Although the original `C (Identity a)` instance declaration has a `C a` constraint, the promoted `PC (Identity a)` instance has no constraints at all. This works since promoted classes can only ever have associated type families, which currently never make use of any class constraints at all.

I say "currently" since the status quo here could change in the future. If a proposal to add constrained type families (e.g., [this one](https://github.com/ghc-proposals/ghc-proposals/pull/177)) is ever implemented, then the `PC (Identity a)` instance above will no longer work without a `PC a` constraint. We might be a ways away from ever implementing such a proposal, but promoting `C a =>` to `PC a =>` would make `singletons` future-compatible with it.

There is one possible concern in that `-Wno-redundant-constraints` would produce a warning that `PC a` is redundant in `instance PC a => PC (Identity a)`. But this is really a moot concern, as there are several places in `singletons` where it generates code that trips up `-Wno-redundant-constraints` (e.g., singling derived instances). Given that we already warn users not to enable `-Wno-redundant-constraints` in the `singletons` README, I wouldn't lose sleep over this.

**Comment by RyanGlScott** [comment]
It turns out that `singletons` actually _does_ promote class contexts in one very specific place: superclasses. See [`promote_superclass_pred`](https://github.com/goldfirere/singletons/blob/d7c88e08b1597ec607575e04b0bc9765d82d831f/src/Data/Singletons/Promote.hs#L352-L364), which I stumbled upon when attempting to implement a prototype of this idea.

What's interesting is that [`singPred`](https://github.com/goldfirere/singletons/blob/d7c88e08b1597ec607575e04b0bc9765d82d831f/src/Data/Singletons/Single/Type.hs#L52-L75), which is essential the singleton-related counterpart to the promotion-related function `promote_superclass_pred`, has slightly different behavior than `promote_superclass_pred` in terms of what constructs are permitted. In particular:

* `promote_superclass_pred` allows explicit kind signatures, whereas `singPred` does not.
* `promote_superclass_pred` allows equality constraints, whereas `singPred` does not.

My vision was to factor out `promote_superclass_pred` into a more general `promotePred` function and use that to promote other class constraints. But if we do that, it would be strange to have `promotePred` and `singPred` have different behavior for unexplained reasons. Which function's conventions should we adopt, I wonder?

**Comment by RyanGlScott** [comment]
I've settled upon the following resolutions for the two bullet points in https://github.com/goldfirere/singletons/issues/396#issuecomment-490958894:

1. `promote_superclass_pred`'s support for equality constraints is completely broken, it turns out:

   ```
       promoteOnly [d| class (a_abUP ~ a_abUP) => C_abUO a_abUP |]
     ======>
       class (#~) a_aeP3 a_aeP3 => PC (a_aeP3 :: GHC.Types.Type)

   Bug.hs:12:3: error: Not in scope: type constructor or class ‘#~’
   ```

   Therefore, disallowing equality constraints during promotion is no worse than the status quo. We can always revisit this decision later.
2. I can't think of any good reason to explicitly disallow explicit kind signatures in constraints, so I'm just going to allow them in `singPred`.

See #397.

**Comment by goldfirere** [comment]
I don't find future-compatibility much of a motivation, given that `singletons` is updated for every GHC release. But if you want this, I won't stop you. :)

**Comment by RyanGlScott** [comment]
I'd be fine with not promoting instance contexts, but the asymmetry between `promote_superclass_pred` and `singlePred` is rather concerning, in my opinion, and deserves to be fixed on its own if nothing else. Moreover, if we're not going to promote instance contexts, should we be even promote superclass contexts at all?

**Comment by goldfirere** [comment]
Yes, the asymmetry is jarring, I agree. I'm not sure the original motivation for promoting superclass constraints, but I'm sure there must have been one. What happens if we don't?

**Comment by RyanGlScott** [comment]
There are several ways to interpret to your question:

* **Does anything break if we remove `promote_superclass_pred`?** No, the test suite continues to pass (aside from a harmless change in the expected output of `T175`).
* **What was the original motivation for introducing `promote_superclass_pred`?** No idea. `git blame` reveals that you introduced it in commit 79c686feb6ae025587c0ccebf08a1af7794e6d8c, but I couldn't find anything in the commit, commit message, or #41 (the accompanying issue) which documented your motivation for adding it.
* **Is there any code in the wild that could break if `singletons` didn't promote superclasses?** No, I can't imagine so.
* **Is there any invalid code that someone might try to write that would now be accepted if `singletons` didn't promote superclasses?** Yes, although I can only think of obscure examples. Imagine this scenario:

  ```hs
  $(promoteOnly [d|
    class Foo a => Bar a
    instance Bar Bool
    |])
  ```

  This would generate an `instance PBar Bool`. Moreover, it would would typecheck, despite the fact that there's no accompanying `instance PFoo Bool`. Whether this is a good thing or not is up to personal interpretation, I suppose. It's also not like you can't do strange things today due to the lack of instance context promotion. For instance, if you write this:

  ```hs
  $(promoteOnly [d|
    class C a where m :: a -> Bool
    instance C a => C (Maybe a) where m _ = True
    |])
  ```

  Then it's perfectly OK to use `M (Just '())` as a type, even though there's no `PC ()` instance. In this sense, the weirdness that not promoting superclasses would induce is no more unusual than the weirdness that already exists due to not promoting instance contexts.

**Comment by RyanGlScott** [comment]
To summarize https://github.com/goldfirere/singletons/issues/396#issuecomment-491373076, I don't think there would be any measurable downsides to just removing `promote_superclass_pred`. Does that sound agreeable?

**Comment by goldfirere** [comment]
Yes -- full steam ahead. Thanks!
