### ISSUE TITLE
Figure out a policy for rank-n types

### ISSUE THREAD

**Issue by RyanGlScott** [goldfirere/singletons#401]
What do you think the following code does?

```hs
$(singletons [d|
  f :: (forall a. a -> a) -> b -> b
  f _ x = x
  |])
```

To my complete surprise, this code actually _compiles_. I was baffled as to how this could possibly work until I looked at the `-ddump-splices` output, which I've produced below (after some minor cleanup):

```hs
    type family F (f :: a ~> a) (x :: b) :: b where
      F _ x = x
    sF ::
      forall b a (f :: a ~> a) (x :: b).
      Sing f -> Sing x -> Sing (F f x)
    sF _ sX = sX
```

Yikes. Unlike the type of `f`, which uses higher-rank polymorphism, neither the kind of `F` nor the type of `sF` are higher-rank! It seems that `singletons` drops the nested `forall` and, by sheer accident, this allows the generated code to compile.

This is clearly less than ideal, and we should aspire to do better. But what is the right thing to do when `singletons` is presented with rank-_n_ types? I contemplated how `singletons` might be changed so that the code it generates is also rank-_n_, but there are a number of obstacles that stand in the way of this vision:

## 1(a): Defunctionalization symbols (current `singletons`)

If we were to promote the `f` example above, here is a defunctionalization symbol that would need to be generated:

```hs
data FooSym0 :: (forall a. a ~> a) ~> b ~> b
```

But note that `(forall a. a ~> a) ~> b ~> b` is the same thing as `TyFun (forall a. a ~> a) (b ~> b) -> Type`, which is decidedly impredicative. I doubt that we want to require users to enable `ImpredicativeTypes`.

## 1(b): Defunctionalization symbols (alternative encoding of `(~>)`)

In an attempt to work around 1(a), I was reminded of [this alternative way](https://github.com/goldfirere/singletons/issues/320#issue-311443055) to encode `(~>)`:

```hs
type a ~> b = a -> b -> Type
```

I thought this might be worth considering because with this encoding, `(forall a. a ~> a) ~> b ~> b` would become `(forall a. a -> a -> Type) -> (b -> b -> Type) -> Type`, which isn't impredicative anymore! Alas, this doesn't get you very far. If you try to define an instance of `Apply` using this version of `(~>)`:

```hs
type instance forall (x :: forall a. a ~> a).
  Apply FSym0 x = FSym1 x
```

Then GHC is not happy:

```
Foo.hs:33:9: error:
    • Expected kind ‘(a0 ~> a0) ~> (b0 ~> b0)’,
        but ‘FSym0’ has kind ‘(forall a. a ~> a) -> (b0 ~> b0) -> *’
    • In the first argument of ‘Apply’, namely ‘FSym0’
      In the type instance declaration for ‘Apply’
   |
33 |   Apply FSym0 x = FSym1 x
   |         ^^^^^
```

It seems that GHC is reluctant to infer a higher-rank kind for `FSym0` in that spot. I tried to make GHC come to its senses:

```hs
type instance forall (x :: forall a. a ~> a).
  Apply @(forall a. a ~> a) FSym0 x = FSym1 x
```

But that makes GHC even less happy:

```
Foo.hs:33:3: error:
    • Illegal polymorphic type: forall a. a ~> a
    • In the type instance declaration for ‘Apply’
   |
33 |   Apply @(forall a. a ~> a) FSym0 x = FSym1 x
   |   ^^^^^
```

Bah. At this point, I gave up on the idea. (Man, I wish `(~>)` were [a part of GHC itself](https://github.com/ghc-proposals/ghc-proposals/pull/242) so that we didn't have to deal with defunctionalization-related crap...)

## 2: In singled definitions

Even if you ignore the challenges that defunctionalization presents, there's still another hurdle to clear: singling. What should the singled version of this function be?

```hs
g :: (forall a. a -> a) -> b -> b
g h x = h x
```

Here is a lousy first attempt:

```hs
type family G (h :: forall a. a ~> a) (x :: b) :: b where
  forall b (h :: forall a. a ~> a) (x :: b). G h x = h @@ x

sG :: forall b (h :: forall a. a ~> a) (x :: b).
      Sing h -> Sing x -> Sing (G h x)
sG sH sX = applySing sH sX
```

Sadly, `sG` does not typecheck:

```
Foo.hs:36:25: error:
    • Couldn't match type ‘x’ with ‘t0’
      ‘x’ is a rigid type variable bound by
        the type signature for:
          sG :: forall a1 b (h :: forall a2. a2 ~> a2) (x :: b).
                Sing h -> Sing x -> Sing (G h x)
        at Foo.hs:(34,1)-(35,38)
      Expected type: Sing t0
        Actual type: Sing x
    • In the second argument of ‘applySing’, namely ‘sX’
      In the expression: applySing sH sX
      In an equation for ‘sG’: sG sH sX = applySing sH sX
    • Relevant bindings include
        sX :: Sing x (bound at Foo.hs:36:7)
        sH :: Sing h (bound at Foo.hs:36:4)
        sG :: Sing h -> Sing x -> Sing (G h x) (bound at Foo.hs:36:1)
   |
36 | sG sH sX = applySing sH sX
   |                         ^^
```

One way to work around this is to use the following type signature for `sG` instead:

```hs
sG :: forall b (h :: forall a. a ~> a) (x :: b).
      (forall a. Sing (h @a)) -> Sing x -> Sing (G h x)
sG sH sX = applySing sH sX
```

This works, but it doesn't scale well, since this trick can only work for rank-_n_ types where the `forall`s always appear in prenex form. That is to say, if you tried to single this definition:

```hs
j :: (a -> forall b. b -> b) -> a -> c -> c
j k x y = k x y
```

Then you're hosed, since there's no way to instantiate the `b` in `a ~> forall b. b ~> b` with visible kind application alone.

-----

All of these challenges lead me to believe that we should simply make any attempt to promote or single a rank-_n_ type an error. In fact, `singletons` currently implements a half-hearted attempt to do this here:

https://github.com/goldfirere/singletons/blob/27245e24d588a63620ffb7f0276345ac36f8a6ba/src/Data/Singletons/Promote/Type.hs#L27-L29

In practice, that `(DAppT (DAppT DArrowT (DForallT (_:_) _ _)) _)` case is very rarely exercised, since all top-level function types are passed to `promoteUnraveled` first, which splits apart `DArrowT`s and then promotes the individual function argument types. As a consequence, it would catch rank-3 (or above) types, but not rank-2 types.

If we do ban rank-_n_ types, what should become of types with nested `forall`s, such as in the following example?

```hs
$(singletons [d|
  const2 :: forall a. a -> forall b. b -> a
  const2 x _ = x
  |])
```

Again, this code actually compiles today, but only because `singletons` treats it as if you had written `forall a b. a -> b -> a`. Should these be banned alongside other rank-_n_ types, or should we grandfather in these sorts of functions that do anything that is explicitly higher-rank?

**Comment by goldfirere** [comment]
> All of these challenges lead me to believe that we should simply make any attempt to promote or single a rank-n type an error. 

I'm in strong favor of this conclusion, given your analysis.

> If we do ban rank-n types, what should become of types with nested foralls, such as in the following example?

I'm not terribly bothered by non-prenex `forall`s here. I say to ban them. If someone complains, we can work on hoisting them up to the top.

Good catch!
