### ISSUE TITLE
Importing Singletons.Prelude (without using it) can produce extremely long type errors

### ISSUE THREAD

**Issue by JakobBruenker** [goldfirere/singletons#405]
I'm not sure much can be done about this issue, but I thought reporting it is worth it since I actually came across it while trying to do something useful.

The following code

```haskell
{-# LANGUAGE GADTs #-}
{-# LANGUAGE TypeFamilies #-}
{-# LANGUAGE RankNTypes #-}
{-# LANGUAGE FlexibleInstances #-}
{-# LANGUAGE AllowAmbiguousTypes #-}

module LongTypeError where

import Data.Singletons.Prelude

data Data f where
  DataCon :: (a -> b) -> Data (a -> b)

function :: f -> Data f
function = undefined

type family TypeFam f fun where
  TypeFam f (a -> b) = f a -> TypeFam f b

lift :: forall f fun . fun -> TypeFam f fun
lift fun = case function fun of
  DataCon f -> \x -> _ (f <*> x)
```

produces roughly 5000 lines of type error, and takes a few minutes to compile. Without the Data.Singletons.Prelude import (no identifiers from the singletons package are used in the code), it produces only 75 lines of type error, and compiles within a few seconds.

[Here is most of the error message it produces, though the pastebin cut off part of it.](https://termbin.com/pqgg)
(This will stay up for a month, if someone knows of a terminal pastebin that accepts files of this size and doesn't delete them after some time, please let me know and I'll upload it there instead.)

I'm actually fairly confused as to why it just stops at some point rather than either explicitly saying that it hit some reduction limit, or failing in some other way, or just not terminating.

Tested on: ghc 8.6.5 with singletons 2.5.1 -- unfortunately I haven't quite managed to install singletons with ghc 8.8.1 yet.

**Comment by mstksg** [comment]
Hm, what happens if you import qualified?  I wonder if there is some weird shadowing going on here.

**Comment by JakobBruenker** [comment]
Importing qualified doesn't help. An empty import list does help, as does `import Data.Singletons.Prelude hiding (type (~>))`.

**Comment by RyanGlScott** [comment]
Thanks for the bug report.

I think this is almost assuredly a bug in GHC, not in `singletons`. I've reported a minimized version of your program upstream at https://gitlab.haskell.org/ghc/ghc/issues/17139. I've been able to reproduce this on GHC 8.6.5, 8.8.1, and HEAD.

**Comment by goldfirere** [comment]
Is this at all a `singletons` issue, then?

**Comment by RyanGlScott** [comment]
I don't think so, no, so I'll close this. Please reopen if you disagree.
