### ISSUE TITLE
Should the test suite continue to use .ghcXX.template files?

### ISSUE THREAD

**Issue by RyanGlScott** [goldfirere/singletons#417]
The test suite currently uses a somewhat unconventional `tasty-golden` setup. A typical setup would assume that one checks in the generated `.golden` files, but `singletons` adds a layer of indirection by instead checking in `ghcXX.template` files and then using those to generate the `.golden` files (which are _not_ checked in). On top of this, the process of going from `.ghcXX.template` files to `.golden` files makes use of a [hacky `awk` script](https://github.com/goldfirere/singletons/blob/499096a0376d3a8e2a636a05f605c02ee9a4a1be/tests/compile-and-dump/buildGoldenFiles.awk), which I've never quite liked.

I've been wondering recently if this extra complexity is even worth it, as it certainly poses a number of challenges. For one thing, it adds conceptual overhead to the test suite, as one must remember whether `.golden` or `.ghc88.template` is the _real_ golden file. Moreover, there is an additional maintenance burden; see #409 for a recent example of a bugfix that had to applied to make `tasty-golden`'s standard `--accept` flag work with the test suite. What's worse, I discovered recently that #409 wasn't entirely correct! If you run a test without a golden file and pass `--accept`, `tasty-golden` is supposed to create the golden file for you. Currently, this doesn't work however:

```
Test suite singletons-test-suite: RUNNING...
Testsuite
  Singletons
    T414: FAIL (0.99s)
      "Error when running awk:\nawk: cannot open /home/rgscott/Documents/Hacking/Haskell/staging/singletons/tests/compile-and-dump/Singletons/T414.ghc88.template (No such file or directory)\n"

1 out of 1 tests failed (0.99s)
Test suite singletons-test-suite: FAIL
```

Ugh, that blasted `awk` script strikes again.

It wouldn't be impossible to work around this issue, but it would require tweaking the unconventional `tasty-golden` setup even further. Instead of doing this, I have a more radical proposition to make. I propose that we:

1. Stop using an `awk` script.
2. Stop checking in separate `.ghcXX.template` files, and instead just check in ordinary `.golden` files.

Doing both of these things would provide a number of benefits:

* We could switch to a conventional `tasty-golden` setup (e.g., [`goldenVsFileDiff`](http://hackage.haskell.org/package/tasty-golden-2.3.2/docs/src/Test.Tasty.Golden.html#goldenVsFileDiff)) and increase our confidence that the test suite behaves like it should, especially with respect to flags like `--accept`.
* We would remove an undeclared dependency on the `awk` tool and make the test suite more portable.
* We would no longer need to change the names of `.ghcXX.template` files upon every new release of GHC, which would make the `git` history for these files easier to navigate.

-----

So why do we use these `.ghcXX.template` files in the first place? As far as I can tell, there are two reasons:

1. The need for the `awk` script is described in [this part](https://github.com/goldfirere/singletons/blob/499096a0376d3a8e2a636a05f605c02ee9a4a1be/tests/README.md#generating-golden-files-from-templates) of `tests/README.md`:

   ```
   ## Generating golden files from templates
   
   It is possible to have definitions generated in one tests used in another
   test. A good example of this is `SingletonsNat` test which singletonizes
   definition of `Nat` datatype. `SingletonsNat` is imported from other tests to
   reuse the generated `Nat` definitions. Due to `-fforce-recomp` option
   `SingletonsNat` module will be recompiled for every test and therefore splices
   generated during its compilation will be included in the output of every test
   that imports `SingletonsNat`. One way to deal with the problem would be to
   prepare golden files that include all generated splices, including those from
   imported modules. The problem with this approach is that if we have 100 tests
   that include `SingletonsNat` and change the way `singletons` are generated we
   will have to update 100 files with exected output. This problem is solved with
   templates. Template file contains expected output but it may also include
   `INSERT tests/compile-and-dump/Foo.XXXX.template` pragma, which inserts the
   contents of a specified template file (XXXX represents GHC version).
   
   This feature is recursive but can be a bit tricky. See `Singletons/EqInstances`
   test for example.
   ```
2. Another part of `tests/README.md` describes the need for the `.ghcXX` suffix:

   ```
   * Testsuite supports multiple GHC versions because each version produces
     different Template Haskell output. Every test requires a separate golden
     file. GHC HEAD is currently not supported. Golden files for GHC 8.4 have
     `.ghc84` appended before their extension.
   ```

I claim that neither of these reasons make much sense in a modern-day context:

1. The `INSERT` pragma is not actually used! And there's a good reason for this: there's really no need to, since the problem it exists to address no longer occurs. This is because all test suite files are [now compiled with the `-c` flag](https://github.com/goldfirere/singletons/blob/499096a0376d3a8e2a636a05f605c02ee9a4a1be/tests/SingletonsTestSuiteUtils.hs#L51), which means that GHC will only compile the module supplied on the command-line and _not_ the modules that it depends on. Therefore, the golden file for each test case will only contain the `-ddump-splices` output for that test case's file alone and nothing else.
2. The claim that the test suite "supports multiple GHC versions" is dubious at best, since `singletons` restricts its version bounds to permit one major version of GHC at a time. In theory, `singletons` could try having separate golden files for more recent versions of GHC, but in this context "more recent versions" means "GHC HEAD", and HEAD is a moving target. We'd likely have to update these special golden files frequently to stay up-to-date with changes in HEAD, and the payoff just doesn't seem worth it to me.

**Comment by goldfirere** [comment]
I thought the `awk` script also squishes uniques, which (to me) is more important than either of those other concerns.

**Comment by RyanGlScott** [comment]
The thing that squishes uniques is not the `awk` script, but rather a [separate normalization pass](https://github.com/goldfirere/singletons/blob/499096a0376d3a8e2a636a05f605c02ee9a4a1be/tests/SingletonsTestSuiteUtils.hs#L194-L213) implemented with `turtle`. We will need to perform this normalization pass regardless of whether we use `.ghcXX.template` files or not, but AFAICT, the `awk` script's _only_ reason for existence is to implement the `INSERT` pragma.

**Comment by goldfirere** [comment]
Then by all means blast `awk` into the oblivion of history.
