### ISSUE TITLE
Question: Motivation for switching Sing from a Data family to a Type family

### ISSUE THREAD

**Issue by epicallan** [goldfirere/singletons#421]
I couldn't find the reasons for switching `Sing` from a data family to a type family in v2.6 (GHC 8.8) with in the `Changes.md`. I am kindly curious about it. Thanks.

**Comment by RyanGlScott** [comment]
I think [this comment](https://github.com/goldfirere/singletons/issues/318#issuecomment-467067257) (and, to a lesser extend, the comments afterward) sum up the reasons for switching.

**Comment by epicallan** [comment]
Thanks, @RyanGlScott. It would have been nice to link that comment link in `Changes.md` in my opinion.

**Comment by RyanGlScott** [comment]
That sounds reasonable to me. Would you care to offer a patch?

**Comment by epicallan** [comment]
I don't mind, I will offer a patch. :)

**Comment by epicallan** [comment]
I have made one, will go ahead and close this comment. Thanks
