### ISSUE TITLE
Odd special case for [] in promoteValRhs

### ISSUE THREAD

**Issue by RyanGlScott** [goldfirere/singletons#428]
There is a rather unusual special case for `[]` wired directly in `promoteValRhs`:

https://github.com/goldfirere/singletons/blob/e24d655964b00785c73d71e344459c496c4ebb5a/src/Data/Singletons/Names.hs#L192-L198

Why? The comment mentions #21, but I can't find anything in the discussion there that would explain what motivated this. Nor can I find anything in be9c9cd56fdadc42760781515e6ab2764a83bdee, the commit which added that comment. This leads me to believe that this comment is vestigial.

If I remove this special case, then 27 test cases' expected output changes due to several occurrences of `[]` changing to `NilSym0`, which is expected. One test case, `Singletons.Nat`, stops compiling with this change due to `NilSym0` not being in scope, but that is simply because `Data.Singletons.TH` does not export it. It probably should, however, since `Data.Singletons.TH` _does_ export the defunctionalization symbols for `(:)`. Indeed, if I make this change:

```diff
diff --git a/src/Data/Singletons/TH.hs b/src/Data/Singletons/TH.hs
index 8b84847..e9a6014 100644
--- a/src/Data/Singletons/TH.hs
+++ b/src/Data/Singletons/TH.hs
@@ -105,7 +105,7 @@ module Data.Singletons.TH (
   type (<*>@#@$), type (<*>@#@$$), type (<*>@#@$$$),
   LiftA2Sym0, LiftA2Sym1, LiftA2Sym2, LiftA2Sym3,
   type (.@#@$), type (.@#@$$), type (.@#@$$$), type (.@#@$$$$),
-  (:@#@$), (:@#@$$), (:@#@$$$),
+  NilSym0, (:@#@$), (:@#@$$), (:@#@$$$),

   SuppressUnusedWarnings(..)
```

Then `Singletons.Nat` compiles again.

Is there any downside to doing things this way?

**Comment by RyanGlScott** [comment]
As soon as I submitted the issue, I realized one potential downside. Currently, this compiles:

```hs
{-# LANGUAGE DataKinds #-}
{-# LANGUAGE GADTs #-}
{-# LANGUAGE PolyKinds #-}
{-# LANGUAGE ScopedTypeVariables #-}
{-# LANGUAGE TemplateHaskell #-}
{-# LANGUAGE TypeApplications #-}
{-# LANGUAGE TypeFamilies #-}
{-# LANGUAGE UndecidableInstances #-}
module Foo where

import Data.Singletons.TH (singletons)

$(singletons [d|
  f :: [a]
  f = []
  |])
```

However, if I remove the aforementioned special case from `promoteValRhs`, then this will no longer compile, since `NilSym0` will not be in scope. Perhaps this isn't so bad, however, since this currently does *not* compile due to `(:@#@$)` not being in scope:

```hs
$(singletons [d|
  g :: a -> [a] -> [a]
  g = (:)
  |])
```

So removing the special case from `promoteValRhs` would bring `[]`'s treatment in line with `(:)`, which could be desirable for the sake of consistency.

**Comment by goldfirere** [comment]
I support this change. The original special case may predate symbols, etc. Go for it!
