### ISSUE TITLE
Constrained singleton generation

### ISSUE THREAD

**Issue by expipiplus1** [goldfirere/singletons#435]
Assuming I have the following class with associated type family and singleton
member function, is it possible to generate a type family and singleton which
depends on these? For example:

```haskell
class Barable (a :: Type) where
  type Bar a :: Nat -> Type
  sBar :: Proxy a -> Sing (n :: Nat) -> Sing (Bar a)

$(singletonsOnly [d|
  foo :: Type -> Nat -> [Type]
  foo a n = if n == 0
             then []
             else bar a n : foo a (n - 1)
  |])
```

Given the above, or something similar, I'd like to have generated the equivalent
of the following:

```haskell
-- A type family for `foo`
type family Foo (a :: Type) (n :: Nat) :: [Type] where
  Foo a 0 = '[]
  Foo a n = Bar a n ': Foo a (n - 1)

-- A singleton for `foo`. Importantly not taking a `Sing a` which may not
-- exist. Either of the following function or equivalent would do. The first of
-- which has an explicit `Barable a` constraint paired with `Proxy a`, the
-- second uses a GADT `SomeBar a` to transport the `Barable a` witness.

sFoo :: Barable a => Proxy a -> Sing (n :: Nat) -> Sing [Type]
sFoo a n = case n %== (sing @0) of
  STrue  -> SNil
  SFalse -> sBar a n `SCons` sFoo a (n %- sing @1)

sFoo :: forall a n. SomeBar a -> Sing (n :: Nat) -> Sing [Type]
sFoo a@SomeBar n = case n %== (sing @0) of
  STrue  -> SNil
  SFalse -> sBar (Proxy @a) n `SCons` sFoo a (n %- sing @1)
```

I'd really like to write `foo`/`Foo`/`sFoo` once and have `singletons` generate
the type level and term versions. As far as I can tell though, `singletons`
doesn't support such a thing, the particular stumbling blocks with the approach
above are:

- Expressing the `Barable a` constraint on the term `a` in `foo a n`
- Passing `a` not as `Sing a` in `sFoo`

I played around a bit with wrapping `a` in `foo` with some newtype with a
`Sing` instance which contained a `Barable a` witness without success.

**Comment by RyanGlScott** [comment]
`singletons` certainly doesn't support generating the code you want at present. Nor do I see an easy path to making this work, since your code deviates from an important `singletons` convention: singled type classes constrain _kind_ arguments, not _type_ arguments. On the other hand, your `Barable` class constrains `a`, which is never used as a kind in `Bar` or `sBar`. This makes singling `foo` to `sFoo` rather awkward, since `foo` lacks a `Barable` constraint altogether. In order to make this work, `sFoo` would somehow have to infer the `Barable` constraint during the singling process.

Can you give a more details on the actual problem you are trying to solve? That might be easier to diagnose that trying to figure out how to make this code work (which is rather mysterious to me).

**Comment by expipiplus1** [comment]
Thanks for the reply, it's pretty much what I was expecting :)

The actual problem is pretty much as I described. More specifically though:

I have a type `Waves (t :: RoseTree Symbol) a` which is a tree of shape `t`
with `a`s at the leaves. The class `ToWave a` contains `type WaveShape a ::
Symbol -> RoseTree Symbol` where for example `WaveShape (a, b) = Branch
'[WaveShape a "fst", WaveShape b "snd"]` or `WaveShape Int = Leaf`. I'd
like to be able to use the instance  `KnownTree t => Applicative (Waves t)`
whenever I have a `ToWave a` witness (for `t ~ WaveShape a`). In order to
use this instance I have to conjure up the `KnownTree t` witness, so in the
class `ToWave a` I have `sWaveShape :: Proxy a -> Sing s -> Sing (WaveShape
a s)`.

So far this works great and `sWaveShape` is easy to define, or can be
derived via `Generic`.

Where it falls down (i.e. I have to write the same code twice, for
WaveShape and sWaveShape (with an `unsafeCoerce` or two to help GHC along))
is for length indexed vectors where: `WaveShape (Vec n a) = Branch (Indexed
0 n a)`, `type family Indexed i n a where Indexed i 0 a = '[]; Indexed i n
a = WaveShape a (Show_ i) ': Indexed (i+1) (n-1)` and `sWaveShape = SBranch
(basically the same code as the type family)`

It would be really nice if there was some template haskell around for
reducing my duplication and `singletons` seems like the most likely place.

Without a doubt the pragmatic thing to do is to just keep the (already
written) duplicated code with a comment saying to keep them in line; but I
do rather want to scratch this itch...

**Comment by RyanGlScott** [comment]
I can't claim to understand the problem any better (mainly because GitHub didn't format the markdown in your response, which makes it difficult to read, and I can't seem to edit it to make it formatted either). But my advice is to structure your code in a way such that `singletons`' TH machinery works well with it. Here is one idea to make this happen:

```hs
{-# LANGUAGE DataKinds #-}
{-# LANGUAGE GADTs #-}
{-# LANGUAGE PolyKinds #-}
{-# LANGUAGE ScopedTypeVariables #-}
{-# LANGUAGE TypeApplications #-}
{-# LANGUAGE TemplateHaskell #-}
{-# LANGUAGE TypeFamilies #-}
{-# LANGUAGE UndecidableInstances #-}
module Foo where

import Data.Kind
import Data.Singletons.Prelude
import Data.Singletons.TH
import Data.Singletons.TypeLits
import Data.Singletons.TypeRepTYPE
import Type.Reflection

data SProxy :: forall a. Proxy a -> Type where
  SProxy :: forall a. SProxy ('Proxy @a)
type instance Sing = SProxy

class Barable (a :: Type) where
  type Bar (p :: Proxy a) :: Nat -> Type
$(genDefunSymbols [''Bar])

class SBarable (a :: Type) where
  sBar :: Sing (p :: Proxy a) -> Sing (n :: Nat) -> Sing (Bar p n)

$(singletonsOnly [d|
  foo :: Barable a => Proxy a -> Nat -> [Type]
  foo a n = if n == 0
             then []
             else bar a n : foo a (n - 1)
  |])

example :: forall a. SBarable a => Proxy a -> Sing (Foo ('Proxy @a) 42)
example _ = sFoo (SProxy @a) (SNat @42)
```

I took some liberties with your code by making the argument of `Bar` be of kind `Proxy a`. But since you indicated a desire to have a version of `sFoo` that takes a `Proxy` as an argument, I deemed this to be an acceptable compromise :)

**Comment by expipiplus1** [comment]
Ah, and I spend ever so long typing out those ticks on my phone... Here is my last message with formatting:

> Thanks for the reply, it's pretty much what I was expecting :)
> 
> The actual problem is pretty much as I described. More specifically though:
> 
> I have a type `Waves (t :: RoseTree Symbol) a` which is a tree of shape `t`
> with `a`s at the leaves. The class `ToWave a` contains `type WaveShape a ::
> Symbol -> RoseTree Symbol` where for example `WaveShape (a, b) = Branch
> '[WaveShape a "fst", WaveShape b "snd"]` or `WaveShape Int = Leaf`. I'd
> like to be able to use the instance  `KnownTree t => Applicative (Waves t)`
> whenever I have a `ToWave a` witness (for `t ~ WaveShape a`). In order to
> use this instance I have to conjure up the `KnownTree t` witness, so in the
> class `ToWave a` I have `sWaveShape :: Proxy a -> Sing s -> Sing (WaveShape
> a s)`.
> 
> So far this works great and `sWaveShape` is easy to define, or can be
> derived via `Generic`.
> 
> Where it falls down (i.e. I have to write the same code twice, for
> WaveShape and sWaveShape (with an `unsafeCoerce` or two to help GHC along))
> is for length indexed vectors where: `WaveShape (Vec n a) = Branch (Indexed
> 0 n a)`, `type family Indexed i n a where Indexed i 0 a = '[]; Indexed i n
> a = WaveShape a (Show_ i) ': Indexed (i+1) (n-1)` and `sWaveShape = SBranch
> (basically the same code as the type family)`
> 
> It would be really nice if there was some template haskell around for
> reducing my duplication and `singletons` seems like the most likely place.
> 
> Without a doubt the pragmatic thing to do is to just keep the (already
> written) duplicated code with a comment saying to keep them in line; but I
> do rather want to scratch this itch...

**Comment by expipiplus1** [comment]
Thanks again for the thoughtful reply, it was exactly what I needed.

With a couple of helpers `sBarP` and `BarP` which strip off the proxy, it can
be made to work without changing the definition of Barable.

```haskell
class Barable (a :: Type) where
  type Bar a :: Nat -> Type
  bar :: Proxy a -> Sing (n :: Nat) -> Sing (Bar a n)

data instance Sing :: Proxy a -> Type where
  SProxy :: Sing ('Proxy :: Proxy a)

type SBarable = Barable

sBarP :: forall a n p. Barable a => Sing (p :: Proxy a) -> Sing (n :: Nat) -> Sing (Bar a n)
sBarP _ = bar (Proxy @a)

type BarP (p :: Proxy a) n = Bar a n
$(genDefunSymbols [''BarP])

$(singletonsOnly [d|
  foo :: Barable a => Proxy a -> Nat -> [Type]
  foo a n = if n == 0
             then []
             else barP a n : foo a (n-1)
  |])

example :: forall a. SBarable a => Proxy a -> Sing (Foo ('Proxy :: Proxy a) 4)
example _ = sFoo (SProxy @a) (sing @4)
```

I'm not exactly sure how `singletons` can be improved here as it all seems so
obvious now, so I'm happy to close this issue.

**Comment by RyanGlScott** [comment]
I'm glad to hear that solution works for you. I'll opt to close this issue, but feel free to re-open it if you feel there is still an underlying issue on `singletons`' end.

**Comment by expipiplus1** [comment]
Actually one thing: Should `Sing (Proxy a)` be included in `singletons`?

**Comment by RyanGlScott** [comment]
Sure, I don't see why not. I've submitted #437, which adds `Data.Singletons.Prelude.Proxy`. Does this suit your needs?

**Comment by expipiplus1** [comment]
Looks perfect, thanks!
