### ISSUE TITLE
Promoting GADT field selectors fails with "Unable to match type" error

### ISSUE THREAD

**Issue by RyanGlScott** [goldfirere/singletons#443]
I would expect this to work:

```hs
{-# LANGUAGE DataKinds #-}
{-# LANGUAGE GADTs #-}
{-# LANGUAGE TemplateHaskell #-}
module Bug where

import Data.Kind
import Data.Singletons.TH

$(promote [d|
  data Nat = Z | S Nat

  data Vec :: Nat -> Type -> Type where
    Nil :: Vec Z a
    (:>) :: { head :: a, tail :: Vec n a } -> Vec (S n) a
  |])
```

But if I try compiling this, I get the following inscrutable error message:

```
[1 of 1] Compiling Bug              ( Bug.hs, interpreted )

Bug.hs:9:3: error:
    Unable to match type (DAppT (DAppT (DConT Vec_6989586621679040818) (DAppT (DConT S_6989586621679040817) (DVarT n_6989586621679040825))) (DVarT a_6989586621679040824)) with (DAppT (DAppT (DConT Vec_6989586621679040818) (DVarT a_6989586621679040826)) (DVarT a_6989586621679040827))
  |
9 | $(promote [d|
  |   ^^^^^^^^^^^...

Bug.hs:9:3: error: Q monad failure
  |
9 | $(promote [d|
  |   ^^^^^^^^^^^...
```

Some quick digging through the code reveals that [`conExistentialTvbs`](https://github.com/goldfirere/th-desugar/blob/612e58eacea0ef71f9f2ffbb1ae9305e77e303e3/Language/Haskell/TH/Desugar.hs#L412-L428) in `th-desugar` is the culprit, as it attempts to invoke `matchTy (Vec (S n) a) (Vec n a)`. If anything, I would have expected it to be the other way around, so I wonder if simply swapping the order of arguments to that call to `matchTy` would fix the issue.

**Comment by RyanGlScott** [comment]
I had a look at [`conExistentialTvbs`](https://github.com/goldfirere/th-desugar/blob/612e58eacea0ef71f9f2ffbb1ae9305e77e303e3/Language/Haskell/TH/Desugar.hs#L412-L428) in `th-desugar` and confirmed my suspicions—the implementation of this function is completely, utterly wrong. I have no idea how it ever worked before. The question now is: what can we do to repair it?

As it turns out, the `th-abstraction` library does much the same thing as `conExistentialTvbs`, but without the bugs. See [this code](https://github.com/glguy/th-abstraction/blob/e61bf339fbb089a216b5a3a9f4c33045d479742e/src/Language/Haskell/TH/Datatype.hs#L1075). My suspicion is that we'll need to reimplement some subset of that code in `th-desugar`. It's not yet clear how much of that code is already present in `th-desugar`. For example, `th-abstraction` makes use of a [`mergeArguments`](https://github.com/glguy/th-abstraction/blob/e61bf339fbb089a216b5a3a9f4c33045d479742e/src/Language/Haskell/TH/Datatype.hs#L1210) which is very similar to, but not quite like, `th-desguar`'s `matchTy`.

**Comment by RyanGlScott** [comment]
A bolder option is to not worry about existential type variables at all. That is, delete `conExistentialTvbs` and make no attempt to weed out naughty record selectors during promotion—just promote all records without question. If a user _does_ attempt to define a naughty record selector, they will have to deal with the consequences of their actions.

This wouldn't be as restrictive as it might sound at first glance. `th-desugar` already removes record syntax in pattern matches, and since the only legitimate way to use naughty record selectors is through pattern-matching, that basically removes the one compelling use case for them. The only real downside to this idea is that you would no longer be able to do this:

```hs
$(singletons [d|
  data O = forall o. MkO { unO :: o }
  |]

nonSingledCodeWithO :: O -> ...
nonSingledCodeWithO (O {unO = o}) = ...
```

It's unclear to me if many people (or even a single person) is writing code like this at the moment. The resulting code would be dramatically simpler, however, so I'm awfully tempted to just do this.

**Comment by goldfirere** [comment]
So: this solution would essentially ban existential records. Is that right?

**Comment by RyanGlScott** [comment]
Not quite. Record fields are still allowed to mention existential type variables as long as those variables also appear in the return type. For instance, this would still be permitted:

```hs
$(singletons [d|
  data HList :: [Type] -> Type where
    Nil :: HList '[]
    (:>) :: { head :: x, tail :: HList xs } -> HList (x:xs)
  |])
```

The types of `head` (`HList (x:xs) -> x`) and `tail` (`HList (x:xs) -> HList xs`) are perfectly fine. Record selectors are only naughty when they mention existential type variables that do not appear anywhere in the return type, like in the example below:

```hs
$(singletons [d|
  data Some :: (Type -> Type) -> Type where
    MkSome :: { getSome :: f a } -> Some f
```

**Comment by goldfirere** [comment]
It's a little sad to slide back down the hill of how much of Haskell `singletons` supports, but, hey, I'm not maintaining it so have little say. I agree that it's unlikely anyone will be hurt by this, and without a viable way forward (which I have not thought about), sliding down is less buggy than the status quo.

**Comment by RyanGlScott** [comment]
Well, there is one possible way forward: adopt the same strategy for computing existential type variables that `th-abstraction` uses, as https://github.com/goldfirere/singletons/issues/443#issuecomment-619082252 suggests. I'm slightly hesitant to go this route because there is absolutely no specification for what `th-abstraction` considers to be existential. In practice, `th-abstraction`'s implementation uses a relative complicated, _ad hoc_ algorithm that work a good chunk of the time, but still fall over if you push hard enough ([example](https://github.com/glguy/th-abstraction/pull/51#issuecomment-401218056)).

I haven't head any users of `th-abstraction` complain about this. Perhaps this is because people have accepted that `th-abstraction` is already full of cryptic TH hacks. But `singletons`, for all its complexity, is relatively forthcoming about what is and what isn't accepted. Adopting the `th-abstration` approach to computing existential type variables would be a departure from this convention, as I wouldn't be able to explain exactly which examples would be accepted by the `th-abstraction` approach.

Perhaps this is an acceptable compromise—I'm not sure. Given that this is a corner case, however, my gut reaction is to not increase the complexity budget unless someone specifically asks for it.

**Comment by goldfirere** [comment]
That's a fine answer. Go with your proposal to remove the feature.

**Comment by RyanGlScott** [comment]
Fun fact: promoting a naughty record selector might work by sheer accident. At first, I thought that this example wouldn't have a snowball's chance in hell of compiling:

```hs
$(promote [d|
  data O = forall a. MkO a
  |])

==>

type UnO :: forall a. O -> a
type family UnO a1 where
  UnO ('MkO field) = field
```

But lo and behold, it actually works! But not for the reasons I had expected. I was scratching my head until I checked out what was going on in GHCi with `-fprint-explicit-kinds`:

```
λ> :info UnO
type UnO :: forall a. O -> a
type family UnO @a a1 where
  forall a (field :: a). UnO @a ('MkO @a field) = field
```

Then I remembered that GADT pattern matching works completely differently in type families (ugh), so while `unO` would be completely bogus as a term-level function, it's a perfectly legitimate type family. The catch is that it's partial: it requires the input kind to `MkO` to be the same as the return kind of `UnO`, so things like `UnO @Ordering (MkO True)` will be stuck.

This doesn't impact the proposed fix in any way, but I thought this was too interesting not to share.

**Comment by goldfirere** [comment]
I presume you meant your code block at the top to define `unO` as a field name? Then, yes, I believe the rest of your post.

Now that we have SAKs, I can retire my infrequently-repeated mantra of "I hate CUSKs." Instead, perhaps it should now be "I hate type families."
