### ISSUE TITLE
Inconsistent treatment of Disproved in the SDecide instances for Nat, Symbol, and Type

### ISSUE THREAD

**Issue by RyanGlScott** [goldfirere/singletons#449]
Consider the following program:

```hs
{-# LANGUAGE DataKinds #-}
{-# LANGUAGE GADTs #-}
{-# LANGUAGE PolyKinds #-}
{-# LANGUAGE TypeApplications #-}
{-# LANGUAGE TypeOperators #-}
module Bug where

import Data.Singletons.Decide
import Data.Singletons.TypeLits
import Data.Singletons.TypeRepTYPE
import Data.Void
import Type.Reflection

f, g :: ()

f = case typeRep @Int %~ typeRep @Char of
      Disproved contra -> absurd $ contra fakeProof

g = case SSym @"Int" %~ SSym @"Char" of
      Disproved contra -> absurd $ contra fakeProof

fakeProof :: a :~: b
fakeProof = error "Fake equality proof"
```

If you evaluate `f`, you'll get this error message, as expected:

```
λ> f
*** Exception: Fake equality proof
```

If you evaluate `g`, on the other hand, you'll see an internal `singletons` error message!

```
λ> g
*** Exception: Broken Symbol singletons
```

I get the feeling that this shouldn't happen. As for _why_ it happens, compare the implementation of the `SDecide` instance for `TYPE rep`:

https://github.com/goldfirere/singletons/blob/779b8ccdb7cf8746fbe01ea521e035dd69e7aa64/src/Data/Singletons/TypeRepTYPE.hs#L94-L98

To the `SDecide` instance for `Symbol`:

https://github.com/goldfirere/singletons/blob/779b8ccdb7cf8746fbe01ea521e035dd69e7aa64/src/Data/Singletons/TypeLits/Internal.hs#L97-L103

In the former instance, the function passed to `Disproved` strictly matches on the equality proof, whereas the latter does not. The `SDecide` instance for `Nat` also does not strictly match on the argument.

I can't think of a good reason for this discrepancy. Why not just match strictly in all of these instances? That way, users should never be able to observe the internal error messages (at least, not without resorting to dirty tricks like `unsafeCoerce`).

**Comment by goldfirere** [comment]
Yes, I agree. The function provided in `Disproved` should always be strict.
