### ISSUE TITLE
Inconsistent wiring-in of promoted/singled names from the Prelude

### ISSUE THREAD

**Issue by RyanGlScott** [goldfirere/singletons#452]
This code best illustrates the problem:

```hs
{-# LANGUAGE DataKinds #-}
{-# LANGUAGE GADTs #-}
{-# LANGUAGE PolyKinds #-}
{-# LANGUAGE StandaloneKindSignatures #-}
{-# LANGUAGE TemplateHaskell #-}
{-# LANGUAGE TypeFamilies #-}
{-# OPTIONS_GHC -Wall #-}
module Bug where

import Data.Singletons.Prelude.Bool (SBool(..), FalseSym0, TrueSym0)
import Data.Singletons.Prelude.Eq (PEq(..))
import Data.Singletons.Prelude.Eq (SEq(..))
import Data.Singletons.TH (singletons)

$(singletons [d| data T = MkT deriving Eq |])
```

If you compile this, you'll actually get a warning:

```
[1 of 1] Compiling Bug              ( Bug.hs, interpreted )

Bug.hs:12:1: warning: [-Wunused-imports]
    The import of ‘Data.Singletons.Prelude.Eq’ is redundant
      except perhaps to import instances from ‘Data.Singletons.Prelude.Eq’
    To import instances alone, use: import Data.Singletons.Prelude.Eq()
   |
12 | import Data.Singletons.Prelude.Eq (SEq(..))
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

This is rather surprising. After all, `singletons [d| ... deriving Eq |]` should generate an `SEq` instance, so why would importing `SEq` be considered redundant? To make things even more confusing, if you comment out the `PEq` import, that will result in an error:

```
Bug.hs:14:3: error:
    Not in scope: type constructor or class ‘PEq’
    Perhaps you meant ‘Eq’ (imported from Prelude)
    Perhaps you want to add ‘PEq’ to the import list in the import of
    ‘Data.Singletons.TH’ (Bug.hs:12:1-38).
   |
14 | $(singletons [d| data T = MkT deriving Eq |])
   |   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

What's going on here? To reveal the full story, let's comment out the `SEq` import and compile with `-ddump-splices`:

```
Bug.hs:16:3-44: Splicing declarations
    singletons
      [d| data T_akCn
            = MkT_akCo
            deriving Eq |]
  ======>
    ...
    instance PEq T_al3x where ...
    instance Data.Singletons.Prelude.Eq.SEq T_al3x where ...
```

Notice how the generated `PEq` instance uses the name "`PEq`" unqualified, which demands that it be imported from elsewhere in order to be in scope. The generated `SEq` instance, on the other hand, uses "`Data.Singletons.Prelude.Eq.SEq`", which is fully qualified. As a result, GHC always figures out where `SEq` lives, even if it is not explicitly imported.

I find this state of affairs confusing, and I believe we should pick a consistent policy for all autogenerated names. My vote would be to generate all such names unqualified (like `PEq` above), although I could be convinced otherwise if others feel strongly.

**Comment by goldfirere** [comment]
I, for one, do not feel strongly. Do what's easiest, I think.

**Comment by RyanGlScott** [comment]
For what it's worth, both options are simple to implement, so I don't think that's really a factor. Besides the sake of consistency, which may not be a convincing enough argument on its own merits, there are two other downsides to generating fully qualified names:

1. They bypass `singletons`' naming `Options`. For example, if someone overrode `singledClassName`, it wouldn't apply when singling `Eq` in today's `singletons`.
2. They make it impossible for people to create their own versions of `SEq` should they so choose.

**Comment by goldfirere** [comment]
OK. Then go with unqualified names. Thanks!
