### ISSUE TITLE
More consistent module naming

### ISSUE THREAD

**Issue by RyanGlScott** [goldfirere/singletons#464]
Now that we've split `singletons` into three packages, it has shined a light on a lurking issue. Namely, the choices of module names. Ideally, it should be easy to tell apart modules from `singletons`, `singletons-th`, and `singletons-base` simply by looking at the module prefix, and to a certain extent, that is true today:

* `singletons` uses `Data.Singletons.*`
* `singletons-th` uses `Data.Singletons.TH.*` for most of its modules
* `singletons-base` uses `Data.Singletons.Prelude.*` for most of its modules

There are two problems, however:

1. The word "most". There are exceptions to the naming rules in `singletons-th` and `singletons-base`:
   * `singletons-th` defines `Data.Singletons.CustomStar` and `Data.Singletons.SuppressUnusedWarnings`, neither of which live in `Data.Singletons.TH.*`.
   * `singletons-base` defines `Data.Singletons.TypeError`, `Data.Singletons.TypeLits`, and `Data.Singletons.TypeRepTYPE`, none of which live in `Data.Singletons.Prelude.*`.
2. `singletons-base` overuses `Data.Singletons.Prelude.*`, especially since many of the things in that module namespace do not correspond to things from the actual `Prelude` (e.g., `Data.Singletons.Prelude.Proxy`).

Given that we're completely reorganizing the package structure in `singletons*-3.0`, now is the time to fix an issue like this. In particular, I propose that we do the following:

1. In `singletons-th`, use `Data.Singletons.TH.*` consistently by renaming `Data.Singletons.CustomStar` and `Data.Singletons.SuppressUnusedWarnings` to `Data.Singletons.TH.CustomStar` and `Data.Singletons.TH.SuppressUnusedWarnings`, respectively.
2. In `singletons-base`, use the module namespace `Data.Singletons.Base.*` to make it mesh better with the name of the library. In particular, I propose to rename most modules from `Data.Singletons.Prelude.X` to `Data.Singletons.Base.X` _carte blanche_. An exception to this rule would be `Data.Singletons.Prelude` itself, which I would propose renaming to `Data.Singletons.Base.Prelude`.

  I would also propose renaming `Data.Singletons.TypeError`, `Data.Singletons.TypeLits`, and `Data.Singletons.TypeRepTYPE` to `Data.Singletons.Base.TypeError`, `Data.Singletons.Base.TypeLits`, and `Data.Singletons.Base.TypeRepTYPE`, respectively.

What do others think of this plan?

**Comment by goldfirere** [comment]
You've listed only public-facing modules. But we should move our private modules, too, I think. For `singletons-th` this means moving the lot to live inside the `TH` directory -- seems easy enough. (Of course, `Data.Singletons.TH` would continue as it is today.)

I want to suggest an alternative to `singletons-base` naming: use a `.Singletons` suffix to existing module names. That is, we have `Prelude.Singletons` and `Data.List.Singletons` and `Data.Proxy.Singletons`, etc. It causes us to have more directories in our repo, etc., but I think it provides a nice experience for the user. It also makes a way forward in case we want to port e.g. `GHC.List` -- the current naming convention won't be happy if there are two modules in the same package with the same final component of their module names. I don't feel strongly, but I wanted to suggest this alternative.

**Comment by RyanGlScott** [comment]
I fully agree about renaming private modules.

Your alternative naming convention for `singletons-base` is intriguing, but it is worth noting that we wouldn't be able to adopt them consistently, as there are some public-facing modules that aren't direct ports of things from `base`. See, for instance, `Data.Singletons.Prelude.TH` and `Data.Singletons.Prelude.CustomStar`. This isn't necessarily a dealbreaker, but it would mean that we'd need a fallback module namespace for things that don't quite fit within the dotted lines.

**Comment by goldfirere** [comment]
I thought you might say that. I'd be fine with `Data.Singletons.Base` for those. If `singletons` is a compiler, then those modules play a role for singletons quite like the role `base` plays for GHC.

**Comment by phadej** [comment]
`.Singletons` suffixes seem nice, but that has bad ergonomics:
- Directory for each module
- Haddocks are *ugly* (See `lens`).

It does make more sense when one has a library `foo` with `Data.Foo` and then one could add `Data.Foo.Singletons`, yet even base does `Data.Type.Foo`, i.e. adds suffix to the prefix, not the whole module name :)

**Comment by RyanGlScott** [comment]
Your comparison to `lens` is an apt one. Both `lens` and `singletons-base` are "batteries-included" libraries that provide definitions based on things from other libraries (e.g., `lens`' `Data.List.Lens` and `singletons-base`'s `Data.Singletons.Base.List`) as well as supporting modules (e.g., `lens`' `Control.Lens.TH` and `singletons-base`'s `Data.Singletons.Base.TH`). As a result, we can study `lens` as a case study to figure out how well @goldfirere's naming suggestion works in practice.

I fully agree with your observation that this requires more directories, although this is really a maintainer inconvenience more than a user inconvenience. (Even then, I think it's a pretty manageable inconvenience, speaking as a maintainer.) I'm not sure I understand your point about the Haddocks being ugly—can you elaborate more on that point?

**Comment by phadej** [comment]
![Screenshot from 2020-06-12 14-42-07](https://user-images.githubusercontent.com/51087/84499256-ea1ec100-acba-11ea-8bd8-3ff33d098a52.png)

**Comment by RyanGlScott** [comment]
Ah, so you mean ugly in the sense of an increased branching factor from the overview page? Fair enough. I don't really have a good answer for how to improve that UI.

(In case it's not clear, I don't have a particularly strong preference one way or the other. I'm simply playing the role of devil's advocate to try and flesh out the pros and cons of each approach.)

**Comment by phadej** [comment]
In `lens` case the `Data.Aeson.Lens` pattern is nice, as those extras live somewhere else. I don't know how much of `Data.Stuff.Singletons` there will or even could be. You know better :)

**Comment by goldfirere** [comment]
That's an interesting point: it's possible that some libraries will want to export their own singletons. The suffix structure works better for that. For my part, I don't find the Haddock ugliness to be problematic -- especially when the haddocks for singletons-base will be essentially useless, anyway.

If anything, it seems better to copy `lens` than not to.

To clarify the strength of my opinion: I like the suffix idea quite a bit more than the `Data.Singletons.Base` idea. But, in the end, I don't care much about this issue, and so the product of these aspects of my preference is small. (This is as opposed to an issue where I care deeply but have only a small sense of what's better.) Bottom line: I will keep arguing for the suffix treatment, but will quickly fold against united opposition and will continue to lead a happy life if the decision goes against.

**Comment by RyanGlScott** [comment]
> I don't know how much of Data.Stuff.Singletons there will or even could be. You know better :)

Honestly, I don't that I know much more than you in this regard. I certainly haven't seen many examples of the `.Singletons` suffix in the wild, but then again, that's probably just a side effect of `singletons`' lack of adoption. Now that `singletons` is much lighter than it used to be, who knows? At the moment, however, there's not much (any?) data to extrapolate from.

**Comment by RyanGlScott** [comment]
To connect the dots in @goldfirere's proposal, here is what I believe the resulting module hierarchy would look like:

```
  exposed-modules:    Data.Singletons.Base.CustomStar
                      Data.Singletons.Base.TH
                      Data.Singletons.Base.SomeSing
                      Data.Singletons.Base.TypeError
                      Data.Singletons.Base.TypeRepTYPE

                      Control.Applicative.Singletons
                      Control.Monad.Singletons
                      Control.Monad.Fail.Singletons
                      Control.Monad.Zip.Singletons
                      Data.Bool.Singletons
                      Data.Either.Singletons
                      Data.Eq.Singletons
                      Data.Foldable.Singletons
                      Data.Function.Singletons
                      Data.Functor.Const.Singletons
                      Data.Functor.Identity.Singletons
                      Data.Functor.Singletons
                      Data.Monoid.Singletons
                      Data.String.Singletons
                      Data.List.Singletons
                      Data.List.NonEmpty.Singletons
                      Data.Maybe.Singletons
                      Data.Ord.Singletons
                      Data.Proxy.Singletons
                      Data.Semigroup.Singletons
                      Data.Show.Singletons
                      Data.Traversable.Singletons
                      Data.Tuple.Singletons
                      Data.Void.Singletons
                      GHC.Base.Singletons
                      GHC.Enum.Singletons
                      GHC.Num.Singletons
                      GHC.TypeLits.Singletons
                      Prelude.Singletons

  other-modules:      Data.Singletons.Base.Instances
                      Data.Singletons.Base.Util

                      Control.Monad.Singletons.Internal
                      Data.List.Singletons.Internal
                      Data.List.Singletons.Internal.Disambiguation
                      Data.Ord.Singletons.Disambiguation
                      Data.Semigroup.Singletons.Internal
                      Data.Semigroup.Singletons.Internal.Disambiguation
                      GHC.TypeLits.Singletons.Internal
```

For the most part, the mapping between the [current modules](https://github.com/goldfirere/singletons/blob/912092709fd0aa824ea989d06247d24e6db3de29/singletons-base/singletons-base.cabal#L84-L139) and the proposed ones should be fairly self-explanatory. Here are some mappings that are less obvious:

* `Data.Singletons.Prelude.Enum` would now be named `GHC.Enum.Singletons`. Surprisingly, there's nothing like `Data.Enum` in `base`. The closest thing we have is `GHC.Enum`, so I chose that.
* `Data.Singletons.Prelude.Num` would now be named `GHC.Num.Singletons`, for similar reasons as above.

There are a total of seven modules that have a generic `Data.Singletons.Base.*` prefix, since there aren't modules in `base` that directly correspond to them. (Note that the version of `TypeError` offered by `Data.Singletons.Base.TypeError` is distinct from the `TypeError` offered by `GHC.TypeLits`, which is why I didn't consolidate it with `GHC.TypeLits.Singletons`.)

**Comment by phadej** [comment]
`GHC.Enum.Singletons` and `GHC.Num.Singletons` sound like they could be `Prelude.Enum.Singletons` and `Prelude.Num.Singletons`. Aren't they just making `Prelude.Singletons` more modular?

Or they could be even internal, and non-exported if their contents is available through `Prelude.Singletons.

`GHC.Num` and `GHC.Enum` are artifacts of how GHC sets up `Prelude` contents. I boldly claim that is a leaked implementation detail, which shouldn't be embraced in downstream.

Otherwise that module structure is very nice.

**Comment by goldfirere** [comment]
I give a soft vote in favor of @phadej 's view that modules like `GHC.Enum` are a leaked implementation detail. But I'm largely happy with what you propose.

**Comment by RyanGlScott** [comment]
Hm. As it turns out, `Data.Singletons.Prelude` doesn't quite re-export everything from `Data.Singletons.Prelude.Enum`:

https://github.com/goldfirere/singletons/blob/912092709fd0aa824ea989d06247d24e6db3de29/singletons-base/src/Data/Singletons/Prelude.hs#L266-L267

As explained by this comment:

https://github.com/goldfirere/singletons/blob/912092709fd0aa824ea989d06247d24e6db3de29/singletons-base/src/Data/Singletons/Prelude.hs#L45-L50

I have to wonder if this is really the best design, however.

**Comment by goldfirere** [comment]
Urgh. I agree with the choice not to export `Succ` in this way. I'm tempted to say it should be `Data.Enum.Singletons`, correcting something that `base` should have done. But I'm not against `GHC.Enum.Singletons`.

**Comment by RyanGlScott** [comment]
To be honest, I'm a bit surprised by the reluctance to steal the name `Succ` given that most Peano natural definitions that I've seen in the wild use the name `S`, not `Succ`. At least, these seven libraries use `S`:

* [`hedgehog`](https://hackage.haskell.org/package/hedgehog-1.0.2/docs/Hedgehog-Internal-Gen.html#t:Nat)
* [`fin`](https://hackage.haskell.org/package/fin-0.1.1/docs/Data-Nat.html#t:Nat)
* [`registry`](https://hackage.haskell.org/package/registry-0.1.7.1/docs/Data-Registry-Lift.html#t:Nat)
* [`singleton-nats`](http://hackage.haskell.org/package/singleton-nats-0.4.5/docs/Data-Nat.html#v:Succ)
* [`type-combinators`](https://hackage.haskell.org/package/type-combinators-0.2.4.3/docs/Type-Family-Nat.html#v:S)
* [`type-fun`](https://hackage.haskell.org/package/type-fun-0.1.1/docs/TypeFun-Data-Peano.html#v:S)
* [`world-peace`](https://hackage.haskell.org/package/world-peace-1.0.1.0/docs/Data-WorldPeace.html#t:Nat)

Whereas these four libraries use `Succ`:

* [`hvect`](https://hackage.haskell.org/package/hvect-0.4.0.0/docs/Data-HVect.html#v:Succ)
* [`numeric-prelude`](https://hackage.haskell.org/package/numeric-prelude-0.4.3.1/docs/Number-Peano.html#v:Succ)
* [`PeanoWitnesses`](https://hackage.haskell.org/package/PeanoWitnesses-0.1.0.0/docs/Data-Numeric-Witness-Peano.html)
* [`peano`](https://hackage.haskell.org/package/peano-0.1.0.1/docs/Data-Peano.html)

(For some variety, [`nat`](https://hackage.haskell.org/package/nat-0.3/docs/Data-Number-Nat.html#v:Pos) uses `Pos`.)

-----

I suppose I could live with not re-exporting `Succ` from `singleton-base`'s `Prelude` so long as we agree on a name for the module that defines it:

* `GHC.Enum.Singletons` is one possibility, although there have been concerns expressed about this being too "internal". If we expose this, then that raises the question if _other_ `GHC.*.Singletons` modules should be public.
* `Data.Enum.Singletons` is another possibility, although that completely bucks the naming conventions that mother modules use, since there is no `Data.Enum` in `base`. Then again, the whole reason for this module's existence is because of a `singletons`-specific special case, so perhaps that special-casing should extend to its name as well.
* `Prelude.Enum.Singletons` is yet another possibility, suggested in https://github.com/goldfirere/singletons/issues/464#issuecomment-645807086. Again, there is no `Prelude.Enum` in `base`. Is this special case more palatable than the bullet point above?

Gah, names are hard.

**Comment by phadej** [comment]
`nat` uses `Pos` because it's binary (not unary) numbers:

```haskell
- | Natural numbers and zero
data Nat
  -- | Constructor representing zero
  = Zero  
  -- | A natural number 
  | Pos Nat1

-- | A binary representation of natural numbers which starts with the least
--   significant bit.
data Nat1
  -- | This constructor represents the most significant bit. There are no 
  --   leading zero bits. 
  = IHi 
  -- | A zero bit
  | O Nat1 
  -- | A one bit
  | I Nat1
```

related to that, my `bin` library (which has binary natural numbers as well), uses `Succ` for a name of `1 +` function: https://hackage.haskell.org/package/bin-0.1/docs/Data-Type-Bin.html#t:Succ

---

Note, that Agda uses `suc` for the name of construct: https://agda.github.io/agda-stdlib/Agda.Builtin.Nat.html#192

---

All that said, I don't see I'd ever use `Enum` class on type-level. Most of its instances are partial, so maybe its *better* to not export that Haskell Prelude wart from `Prelude.Singletons`.

**Comment by RyanGlScott** [comment]
Alright, it sounds like the consensus is that we shouldn't re-export `Succ` from `Prelude.Singletons`. In that case, the only remaining item of discussion is to decide what we should name the module that _does_ export it. I've listed the three options considered so far at the bottom of https://github.com/goldfirere/singletons/issues/464#issuecomment-646320047.

**Comment by goldfirere** [comment]
I vote for `Data.Singletons.Base.Enum`. It's not on the list of options, but the `Data.Singletons.Base` space is used for singletons-specific stuff, and we've argued here that `Enum` (or, rather, the lack of its export from our Prelude) is singletons-specific. Choosing this name also makes it less of a special case (or, rather, adds only to the special case we already have).

**Comment by RyanGlScott** [comment]
Very well, `Data.Singletons.Base.Enum` it is. See #468.
