### ISSUE TITLE
Missing re-exports from Data.Singletons.Prelude

### ISSUE THREAD

**Issue by RyanGlScott** [goldfirere/singletons#465]
While combing through `Data.Singletons.Prelude` recently, I noticed that there are several things that it does not re-export but ought to. These are:

* `Until`/`sUntil`/`UntilSym{N}`
* `type (++@#@$$$)`
* `type (.@#@$$$$)`
* `FlipSym3`
* `type (!!)`/`(%!!)`/`type (!!@#@{$})`
* `Length`/`sLength`/`LengthSym{N}`
* `DropWhile`/`sDropWhile`
* `LookupSym{N}`

I also noticed that `Data.Singletons.Prelude` re-exports `Symbol`, but not `Nat`. Besides being inconsistent, there are several functions re-exported by `Data.Singletons.Prelude` that mention `Nat` in their type/kind signatures (e.g., `Replicate`/`sReplicate`), so it seems like `Nat` should be re-exported along with them.

**Comment by goldfirere** [comment]
The fact that no one has noticed the lack of `Sym` exports means the functions aren't being used. Oh well.

About `Nat`: I'm on the fence. The built-in `Nat` is mostly useless. And users will likely want another `Nat` instead. I agree about being consistent, but perhaps we should just stop exporting `Symbol`.

**Comment by RyanGlScott** [comment]
> The built-in `Nat` is mostly useless.

Is it? As I mentioned above, it's used in the types of various functions that are exported by `singletons-base`'s `Prelude`, filling the same role that `Int` plays in `base`'s `Prelude`. By analogy, `Symbol` is playing the same role that `String` plays.

Then again, this isn't a hill I want to die on. I'd also be OK with not exporting `Nat` or `Symbol`.

**Comment by goldfirere** [comment]
> Is it?

In my experience, yes. But I don't much care here.

**Comment by RyanGlScott** [comment]
Hm. After implementing the patch, I'm very hesitant to remove the `Symbol` re-export, as it would be terribly awkward to export `SChar` (a synonym for `Symbol`) and `SymbolS` (a synonym for `Symbol -> Symbol`) but _not_ export `Symbol`.

I think I would be OK with not exporting `Nat`, not because it's useless, but because it would likely clash with anyone who attempts to define a unary natural number type. We already have precedent for not exporting `Succ` and `Enum` from `Prelude.Singletons`, so not exporting `Nat` would appear to follow this same convention.

**Comment by goldfirere** [comment]
Sounds fine by me. It's generally a fine idea to keep the status quo.
