### ISSUE TITLE
Use type-level characters in Text.Show.Singletons

### ISSUE THREAD

**Issue by RyanGlScott** [goldfirere/singletons#487]
GHC 9.2 will feature [type-level `Char`s](https://gitlab.haskell.org/ghc/ghc/-/commit/7f3524efcbd58ca6837ec0ffca6ddd121d64e4de). This will likely prove useful for `singletons-base`'s purposes, as the `Text.Show.Singletons` module currently employs several nasty hacks to work around the lack of type-level `Char`s. This code in particular speaks volumes:

https://github.com/goldfirere/singletons/blob/38eac92d311ebd188d008190c84a20b664e2ab9d/singletons-base/src/Text/Show/Singletons.hs#L81-L84

I've started a [`type-level-chars` branch](https://github.com/goldfirere/singletons/tree/type-level-chars) which explores refactoring `singletons-base` to remove the `SChar` hack and just using the `Char` kind. I was able to do quite a bit with the current state of GHC HEAD, but I wasn't able to promote quite everything in `Text.Show` yet. In particular, I'm not able to promote the `Show Char` instance due to not having a type-level `ord` function. Such a function will be added in [this MR](https://gitlab.haskell.org/ghc/ghc/-/merge_requests/3598), but it's not yet clear to me if that will land in time for GHC 9.2.1.

When GHC 9.2.1 is released, we should revisit this and see how many hacks can be removed from `Text.Show.Singletons`.

**Comment by int-index** [comment]
@RyanGlScott Do you need anything besides `ord` to make this work? One of the issues with the MR you linked to is that it adds a lot of built-in type families, and it’s not clear whether we need them all.

But `ord` should be easy (and `chr` for symmetry, I suppose). If that’s all you need, we could easily extract them into a smaller MR.

**Comment by RyanGlScott** [comment]
> Do you need anything besides `ord` to make this work?

I'm not sure, as I didn't explore any further once I ran into the `ord` obstacle. But perhaps I should try building a stripped-down version of [this MR](https://gitlab.haskell.org/ghc/ghc/-/merge_requests/3598) that only defines type-level `ord` and `chr` and see if those are enough to remove all of the hacks currently used in `Text.Show.Singletons`. (I'm loosely defining "hack" to mean "using `Symbol` in a place where `Char` ought to be used instead".)

**Comment by int-index** [comment]
Alright, I’ll prepare a branch for this, and we can add more type families to it if you discover a need for them.

**Comment by int-index** [comment]
Here it is: https://gitlab.haskell.org/ghc/ghc/-/merge_requests/5258

**Comment by RyanGlScott** [comment]
Thanks, @int-index! With `CharToNat` and `NatToChar`, I was able to rework `Text.Show.Singletons` in the `type-level-chars` branch to a point where I'm satisfied with how it looks.

One interesting quirk this work revealed was that I found myself needing to duplicate functionality to work over both the `Symbol` and `String` kinds, i.e.,

```hs
  showLitString :: String -> SymbolS
  showLitString []         s = s
  showLitString ('"' : cs) s = showString "\\\"" (showLitString cs s)
  showLitString (c   : cs) s = showLitChar c (showLitString cs s)

  showLitSymbol :: Symbol -> SymbolS
  showLitSymbol sym s = case unconsSymbol sym of
    Nothing        -> s
    Just ('"', cs) -> showString "\\\"" (showLitSymbol cs s)
    Just (c,   cs) -> showLitChar c (showLitSymbol cs s)
```

I wonder if I should take the time to define a `StringToSymbol` type family—or, alternatively, `SymbolToString`—so that I can define one of these functions in terms of the other. In any case, this isn't anything which would impact your MR, as it would be possible to define these type families in terms of `ConsSymbol` or `UnconsSymbol`.

**Comment by int-index** [comment]
Another option is to define polymorphic `cons` and `uncons`:

```
class CharList a where
  cons :: Char -> a -> a
  uncons :: a -> Maybe (Char, a)
```

The instance for `Symbol` would use `ConsSymbol` and `UnconsSymbol`. The instance for `String` would use `:` and `Data.List.uncons`.
