### ISSUE TITLE
Why singletons use unsafeCoerce and not magicDict

### ISSUE THREAD

**Issue by phadej** [goldfirere/singletons#490]
See https://gitlab.haskell.org/ghc/ghc/-/blob/master/compiler/GHC/Types/Id/Make.hs#L1804-1844

Would it work?

**Comment by RyanGlScott** [comment]
> Would it work?

Probably. I don't really have a strong preference between `unsafeCoerce` and `magicDict` as far as unsafe primitives go. That being said, I've never quite understood what benefit `magicDict` provides over `unsafeCoerce`. The last time I tried [experimenting with these two functions](https://github.com/ekmett/reflection/issues/44#issuecomment-503588590) in the `reflection` library, I couldn't observe an appreciable difference in the Core that each function produces. But then again, this was only a small experiment—perhaps I overlooked something.

**Comment by phadej** [comment]
My hunch is that `magicDict` produces safe coercion, so doing something contrived as `reify . reflect` should optimise to `id`.

Note, that in 9.0 the `unsafeCoerce` is very ugly (for good reasons): https://hackage.haskell.org/package/base-4.15.0.0/docs/src/Unsafe-Coerce.html#unsafeCoerce so you might want to re-inspect Core differences there. in `optics` `unsafeCoerce` was in the way of optimizer on 9.2 (our `inspection-testing` tests caught an issue: https://github.com/well-typed/optics/issues/396)

**Comment by phadej** [comment]
To justify my hunch consider:

```haskell
{-# LANGUAGE TemplateHaskell #-}
module UC where

import Test.Inspection

import GHC.Exts (Any)
import Unsafe.Coerce (unsafeCoerce)

fromAny :: Any -> Int
fromAny = unsafeCoerce

toAny :: Int -> Any
toAny = unsafeCoerce

weirdId :: Int -> Int
weirdId = fromAny . toAny

normalId :: Int -> Int
normalId = \x -> x

inspect $ 'weirdId === 'normalId
```

The inspection test passes on GHC-8.6, 8.8 and 8.10, however GHC-9.0 yells:

```
[1 of 1] Compiling UC               ( src/UC.hs, /code/mess/uc/dist-newstyle/build/x86_64-linux/ghc-9.0.1/uc-0.1.0.0/build/UC.o, /code/mess/uc/dist-newstyle/build/x86_64-linux/ghc-9.0.1/uc-0.1.0.0/build/UC.dyn_o )
src/UC.hs:21:1: weirdId === normalId failed:
    LHS:
        weirdId :: Int -> Int
        [LclIdX,
         Arity=1,
         Str=<S,1*U>,
         Unf=Unf{Src=InlineStable, TopLvl=True, Value=True, ConLike=True,
                 WorkFree=True, Expandable=True,
                 Guidance=ALWAYS_IF(arity=1,unsat_ok=True,boring_ok=True)
                 Tmpl= \ (x [Occ=Once1] :: Int) ->
                         case unsafeEqualityProof @(*) @Any @Int of { UnsafeRefl co ->
                         case unsafeEqualityProof @(*) @Int @Any of { UnsafeRefl co -> x }
                         }}]
        weirdId
          = \ (x [Dmd=<S,1*U>] :: Int) ->
              case unsafeEqualityProof @(*) @Any @Int of
              { UnsafeRefl co [Dmd=<L,A>] ->
              case unsafeEqualityProof @(*) @Int @Any of
              { UnsafeRefl co [Dmd=<L,A>] ->
              x
              }
              }
        
    RHS:
        normalId :: Int -> Int
        [LclIdX,
         Arity=1,
         Str=<S,1*U>,
         Unf=Unf{Src=InlineStable, TopLvl=True, Value=True, ConLike=True,
                 WorkFree=True, Expandable=True,
                 Guidance=ALWAYS_IF(arity=1,unsat_ok=True,boring_ok=True)
                 Tmpl= \ (x [Occ=Once1] :: Int) -> x}]
        normalId = \ (x [Dmd=<S,1*U>] :: Int) -> x
        

src/UC.hs: error:
    inspection testing unsuccessful
         unexpected failures: 1
```

**Comment by phadej** [comment]
To summarise:
-  `magicDict` rules are not powerful enough (#16647)
- `magicDict` doesn't work if you interpret (GHCi) module using `magicDict`
- `unsafeCoerce` on GHC-9.0 adds a `case` which cannot be optimized away

So it's lose lose situation on GHC-9.

**Comment by RyanGlScott** [comment]
Fixes for [GHC#16646](https://gitlab.haskell.org/ghc/ghc/-/issues/16646) and [GHC#19667](https://gitlab.haskell.org/ghc/ghc/-/issues/19667) will be present in GHC 9.4. I've opened #497 as a reminder to do this.

**Comment by phadej** [comment]
Thanks @RyanGlScott, this is great news!

**Comment by phadej** [comment]
Is `runExists` in one of your fixes, i.e. can `reflection` be moved to use the `magicDict`, or is it still to do or even to design?

**Comment by monoidal** [comment]
As far as I understand, `runExists` (19675) is not a blocker and is independent of `unsafeCoerce` vs `magicDict`.

`runExists` is a better version of type application `@Any` (which is implicitly used in `someNatVal` in GHC) - normally, that pattern needs a NOINLINE pragma for reasons described in [Note [NOINLINE someNatVal]](https://github.com/ghc/ghc/blob/master/libraries/base/GHC/TypeNats.hs#L93). GHC.TypeNats have switched to `withDict`, but `someNatVal` still needs NOINLINE until `runExists` is implemented.

I have no idea about 15183 though.

**Comment by RyanGlScott** [comment]
Let's move this discussion to ekmett/reflection#44, as `reflection`'s needs are different than `singletons`'.
