### ISSUE TITLE
Add missing promotions

### ISSUE THREAD

**Issue by treeowl** [goldfirere/singletons#491]
There are some things we can promote that we can't singletonize. For example, I don't see any obvious problem with

```haskell
$(genPromotions [''Compose, ''Product])
$(promoteOnly [d|
  instance (Functor f, Functor g) => Functor (Compose f g) where
    fmap fun (Compose x) = Compose (fmap (fmap fun) x)

  instance (Functor f, Functor g) => Functor (Product f g) where
    fmap fun (Pair x y) = Pair (fmap fun x) (fmap fun y)
  |])
```

even though `genSingletons` fails for both `Compose` and `Product`.

I believe we should add such, just for folks using `singletons` facilities for type-level programming (e.g., the automatic defunctionalization).

**Comment by RyanGlScott** [comment]
This sounds reasonable to me. Can you see if #494 fulfills your needs?
