### ISSUE TITLE
Non-exhaustive pattern match with `FromSing` pattern synonym

### ISSUE THREAD

**Issue by jul1u5** [goldfirere/singletons#499]
Hello!
I was experimenting with pattern synonyms for singleton types and ran into the issue where I can't get rid of a warning about non-exhaustive pattern match. Even when I tried the [`singAnd` example](https://hackage.haskell.org/package/singletons-3.0/docs/Data-Singletons.html#v:FromSing) in the documentation I got a warning:
```haskell
{-# LANGUAGE PatternSynonyms #-}
{-# OPTIONS_GHC -Wincomplete-patterns #-}

module Main where

import Data.Singletons
import Prelude.Singletons

singAnd :: Bool -> Bool -> SomeSing Bool
singAnd (FromSing singBool1) (FromSing singBool2) =
  SomeSing (singBool1 %&& singBool2)
```
```
src/Main.hs:9:1: warning: [-Wincomplete-patterns]
    Pattern match(es) are non-exhaustive
    In an equation for ‘singAnd’:
        Patterns not matched:
            False False
            False True
            True False
            True True
            ...
  |
9 | singAnd (FromSing singBool1) (FromSing singBool2) =
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^...
```

As I understand the `COMPLETE` pragma [here](https://github.com/goldfirere/singletons/blob/70d622645b960d60411ab8f31d16ffb91e69379e/singletons/src/Data/Singletons.hs#L304) should convince GHC that `FromSing` is exhaustive, as explained in the [GHC Wiki for complete sigs](https://gitlab.haskell.org/ghc/ghc/-/wikis/pattern-synonyms/complete-sigs). Why is this not the case here? Could the underlying issue be in GHC itself?

**Additional information**
I tried the above example with singletons-3.0 on GHC 9.0.1, but I also noticed this behaviour in singletons-2.7 on GHC 8.10.4.

**Comment by RyanGlScott** [comment]
I'm going to wager that this is GHC's fault, as if I compile your example with GHC 9.2.1-alpha2 or HEAD (using [this `head.hackage` patch](https://gitlab.haskell.org/ghc/head.hackage/-/blob/a9bd5dab2cca0369519f1c379f2cf70ea85e47c7/patches/singletons-base-3.0.patch) to build `singletons-base`), then I do not experience the warning that appears with 9.0.1. It's not entirely clear to me which GHC commit fixed this, but in any case, it's good to know that it's fixed.

I don't think there's anything to be done on the library side, so I'll go ahead and close this. Please re-open if you feel there are unresolved issues to address.
