### ISSUE TITLE
Dead links in singleton-base README

### ISSUE THREAD

**Issue by bgohla** [goldfirere/singletons#521]
The links to the PDFs in the README are dead on Hackage:  https://hackage.haskell.org/package/singletons-base . They do work in the repo though.

**Comment by RyanGlScott** [comment]
The links were fixed in `master` in #516 and #518. I've applied revisions to the latest Hackage versions of `singletons`, `singletons-th`, and `singletons-base` just now to update the links in their `.cabal` files.
