### ISSUE TITLE
The link to the paper doesn’t work

### ISSUE THREAD

**Issue by schuelermine** [goldfirere/singletons#524]
On Hackage, the README links to https://cs.brynmawr.edu/~rae/papers/2012/singletons/paper.pdf. That link returns 404.

**Comment by RyanGlScott** [comment]
Yes, this was reported previously in #517. I fixed the issue in the repo in #518 and applied a corresponding Hackage revision such that the `.cabal` file description points to the correct link. Unfortunately, Hackage revisions don't let you update the displayed `README` contents (as far as I am aware), but the correct link will show up in the next `singletons` release.
