### ISSUE TITLE
Allow building with `ghc924`

### ISSUE THREAD

**Issue by MangoIV** [goldfirere/singletons#528]
Hi, I discovered that the `base` version you support doesn't allow for building with `ghc924`, same goes for `th-desugar` could that be changed? 
Thanks in advance.

**Comment by RyanGlScott** [comment]
I'm not quite sure what you mean here, since I am able to build `singletons-base-3.1` (the latest Hackage release) and related libraries on GHC 9.2.4 without any issues. Can you post the steps you are taking to build with GHC 9.2.4 that are failing?

**Comment by MangoIV** [comment]
Upon further research I think the issue is not with you; I'm trying to build with nix and use the correct inputs; however, when trying to build `singletons-base`, nix (I think it's nix) resolves `singletons- th` to version `3.0` and not `3.1` which is weird because `3.1` is specified in the cabal file. 

I can build `singletons-th` 3.1 just fine. 

Sorry for the inconveniences.

**Comment by MangoIV** [comment]
If anybody else runs into this, here is the corresponding issue at nixpkgs https://github.com/NixOS/nixpkgs/issues/187430
