### ISSUE TITLE
Use `cabal`'s `code-generators` to reimplement `singletons-base` test suite without custom `Setup.hs`

### ISSUE THREAD

**Issue by RyanGlScott** [goldfirere/singletons#532]
`Cabal-3.8` debuts a new [`code-generators`](https://github.com/haskell/cabal/pull/7688) feature that can be used to generate modules when preprocessing a test suite and include them as part of building the test suite. One of the intended use cases for a code generator is to fill the role that is often served today by custom `Setup.hs` scripts. In particular, `singletons-base`'s custom `Setup.hs` script seems like a prime candidate for being implemented as a code generator, since the primary reason for using a custom `Setup.hs` script is to learn what `-package-id` arguments to pass to GHC to get the dependencies right. That is exactly the sort of information that code generators have access to.

**Comment by phadej** [comment]
@RyanGlScott be aware that it's likely that `stack` will choke on code-generators stuff as well, so Stackage probably wont run the test-suites. Probably not a big deal, but something to be are off.

As far as I know no package on Hackage uses `code-generators` (based on https://hackage-search.serokell.io/?q=code-generators), so you are in uncharted territory.

**Comment by RyanGlScott** [comment]
> be aware that it's likely that `stack` will choke on code-generators stuff as well, so Stackage probably wont run the test-suites. Probably not a big deal, but something to be aware of.

Interestingly, the `singletons-base` test suite has disabled in Stackage ever since [this commit](https://github.com/commercialhaskell/stackage/commit/186f4e18dffc8312768c694a5dab2ba00f9942e3). In that sense, people are unlikely to notice if it suddenly doesn't work with `stack` :)

> As far as I know no package on Hackage uses code-generators (based on https://hackage-search.serokell.io/?q=code-generators), so you are in uncharted territory.

Fun! `singletons` has always pushed the boundaries of what the Haskell ecosystem can do, and this is no exception. Let's see what happens.
