### ISSUE TITLE
Case analysis?

### ISSUE THREAD

**Issue by treeowl** [goldfirere/singletons#533]
Is there anything like this?

```haskell
type List_ :: (a ~> [a] ~> r) -> r -> [a] -> r
```

I know we have `If` for `Bool`, `Either_` for `Either`, and (I assume) `Maybe_` for `Maybe`, but we should have such things (preferably automatically) for all supported types. Of course, maybe we do and I just don't know about it.

**Comment by RyanGlScott** [comment]
`singletons` doesn't generate these for you, no. Similar ideas have been proposed before (see #193 and #275), but the design space for eliminator functions such as these is varied enough that I've concluded it to be out of the scope of what the `singletons` library should accomplish.

The [`eliminators`](https://hackage.haskell.org/package/eliminators) library provides one point in this design space, and it offers a more general version of `List_` called [`ElimList`](https://hackage.haskell.org/package/eliminators-0.9.1/docs/Data-Eliminator.html#t:ElimList). Unfortunately, Haddock doesn't render standalone kind signatures, but the kind of `ElimList` is:

```hs
ElimList :: forall a.
            forall (p :: [a] ~> Type) (l :: [a]) ->
            (p @@ '[]) ->
            (forall (x :: a) (xs :: [a]) -> p @@ x ~> p @@ (x : xs)) ->
            (p @@ l)
```

One can define `List_` in terms of `ElimList` like so:

```hs
{-# LANGUAGE DataKinds #-}
{-# LANGUAGE GHC2021 #-}
{-# LANGUAGE RankNTypes #-}
{-# LANGUAGE TypeFamilies #-}
{-# LANGUAGE UndecidableInstances #-}
module Foo where

import Data.Eliminator
import Prelude.Singletons

type List_ :: (a ~> [a] ~> r) -> r -> [a] -> r
type List_ cons (nil :: r) l =
  ElimList (ConstSym1 r) l nil (List_HelperSym cons)

type List_HelperSym :: forall a r.
                       (a ~> [a] ~> r) ->
                       forall (x :: a) (xs :: [a]) -> r ~> r
data List_HelperSym cons x xs z
type instance Apply (List_HelperSym cons x xs) _ = cons @@ x @@ xs
```

**Comment by RyanGlScott** [comment]
Closing this as out of scope for `singletons`.
