### ISSUE TITLE
how do I suppress generating the Sym0 suffixed symbols? (or what do i reexport so FooSym0 etc count as used)

### ISSUE THREAD

**Issue by cartazio** [goldfirere/singletons#557]
I have a pretty elementary use case where I just want to scrap my singleton boiler plate for a simple tagged enum, i dont see any way to suppress it. 

to be clear, my motivation here is mostly that i dont have any clue what i could "reexport" in my module that would 
satisfy 
```    warning: [-Wunused-top-binds]
    Defined but not used: type constructor or class ‘BatchSym0’
```
and I dont wanna disable that warning wholesale because its generally useful!

**Comment by cartazio** [comment]
theres enough constructors that exporting them one by one isn't practical.

**Comment by cartazio** [comment]
do i just reexport `SuppressUnusedWarnings(..)`?

**Comment by cartazio** [comment]
nope, that doesn't work.

**Comment by RyanGlScott** [comment]
Defunctionalization symbols (i.e., the names with `Sym*` suffixes) are fundamental to how `singletons-th` works today. You simply can't suppress generating them, as the code that `singletons-th` generates requires the defunctionalization symbols to be present. Moreover, if downstream code uses uses `batch`, `singletons-th` will generate code that mentions `BatchSym0` and related symbols, so you unfortunately have no other option besides to export them alongside `Batch`.

(`SuppressUnusedWarnings` is meant to suppress warnings for a different kind of symbol. It's not meant to suppress warnings involving defunctionalization symbols.)

This is all terrible, I know. But there's not much an alternative in today's GHC:

* Ideally, Template Haskell could give us some way to automate exporting certain identifiers, but no such functionality currently exists: see [GHC#1475](https://gitlab.haskell.org/ghc/ghc/-/issues/1475), a 15-year-old GHC issue. (You'll find a comment on that issue involving `singletons`, appropriately enough.)
* In a world where GHC had the ability to partially apply type families and type synonyms, we wouldn't need any defunctionalization symbols. Such a world could be possible if [unsaturated type families](https://github.com/ghc-proposals/ghc-proposals/blob/ef3b8c00769778c678510c86e25c23ea625b9b5f/proposals/0242-unsaturated-type-families.rst) were implemented, but this has not yet happened.

Sorry to be the bearer of bad news here: this simply can't be done in today's GHC.

**Comment by cartazio** [comment]
ok, and this is the case even if restricted to just eg  taking `data Nat = Z | S Nat` into  `data SNat :: Nat -> Type` ?

**Comment by RyanGlScott** [comment]
That might be the one case where you could conceivably get away with not generating defunctionalization symbols. But even if you did, you'd be on thin ice: you wouldn't be able to use `singletons-th` to generate _any_ code that mentioned `Z` or `S`, as the generated code would require `ZSym0` or `SSym0`. It's for this reason that I'm reluctant to offer a configuration option to disable defunctionalization symbols wholesale, as it would backfire unless you were extremely careful.

**Comment by cartazio** [comment]
yeah, makes sense.

**Comment by RyanGlScott** [comment]
In that case, I'll close this, as there's nothing that can be done about this currently. To quote https://github.com/goldfirere/singletons/issues/498#issuecomment-841649537, I'll add this to my "revisit-this-when-GHC-gets-unsaturated-type-families" list.
