### ISSUE TITLE
Support promoting/singling namespace specifiers in fixity declarations

### ISSUE THREAD

**Issue by RyanGlScott** [goldfirere/singletons#582]
GHC 9.10.1 [adds support for namespaces in fixity declarations](https://gitlab.haskell.org/ghc/ghc/-/merge_requests/12012), e.g.,

```hs
$(singletons
  [d| infixl 4 data `f`
      f :: a -> a -> a
    |])
```

It would be nice if `singletons-th` could take these into account during promotion and singling. In particular, we could promote `f` to:

```hs
-- Promoted type-level declaration
infixl 4 type `F`
type F :: a -> a -> a
-- Defunctionalization symbols
infixl 4 type `FSym0`
infixl 4 type `FSym1`
```

And we could single `f` to:

```hs
infixl 4 data `sF`
sF :: forall a (x :: a) (y :: a). Sing x -> Sing y -> Sing (F x y)
```

Some wrinkles to this plan:

* What happens if we promote or single a quoted type-level declaration, such as this one?

  ```hs
  $(singletons
    [d| infixl 4 type `G`
        type G :: a -> a -> a
      |])
  ```

  In that case, we would simply return the original fixity declaration unchanged (including the `type` specifier).
* In the event that a fixity declaration lacks an explicit namespace specifier, I propose that we promote/single it to something that _does_ have an explicit namespace specifier. To see why, consider this example:

  ```hs
  $(singletons
    [d| infixl 4 ###
        (###) :: a -> a -> a
      |])
  ```
  
  We must _not_ promote this to the following:
  
  ```hs
  infixl 4 ###
  type (###) :: a -> a -> a
  ```
  
  If we did, there would be two clashing fixity declarations for `(###)`: one for the name in the `data` namespace, and another for the name in the `type` namespace. We should instead promote `(###)` to the following to avoid the risk of name clashes:
  
  ```hs
  infixl 4 type ###
  type (###) :: a -> a -> a
  ```
  
  If we did this, then we can remove a hack from `singletons-th` that is described in [`Wrinkle 1: When not to promote/single fixity declarations`](https://github.com/goldfirere/singletons/blob/2a604585d637d52256c31e1d4eee0c4d7150b7ef/singletons-th/src/Data/Singletons/TH/Single/Fixity.hs#L103-L116) of `Note [singletons-th and fixity declarations]`.

**Comment by goldfirere** [comment]
What's the reason to put fixity on defunctionalization symbols? Their arity generally differs from the original construct (and so their infix usage is likely quite different-looking). And programmatically generated uses won't care about the fixity.

Otherwise, this sounds great to me.

**Comment by RyanGlScott** [comment]
See [`Note [Fixity declarations for defunctionalization symbols]`](https://github.com/goldfirere/singletons/blob/2a604585d637d52256c31e1d4eee0c4d7150b7ef/singletons-th/src/Data/Singletons/TH/Promote/Defun.hs#L807-L826).

**Comment by goldfirere** [comment]
Ah right. Thanks!

**Comment by RyanGlScott** [comment]
A minor correction to my original proposal: we can't get rid of [`Wrinkle 1: When not to promote/single fixity declarations`](https://github.com/goldfirere/singletons/blob/2a604585d637d52256c31e1d4eee0c4d7150b7ef/singletons-th/src/Data/Singletons/TH/Single/Fixity.hs#L103-L116) of `Note [singletons-th and fixity declarations]` just yet. I wrote that comment under the assumption that GHC would accept this:

```hs
module Foo where

infixl 4 ###
(###) :: a -> a -> a
x ### y = x

infixl 4 type ###
type (###) :: a -> a -> a
type x ### y = x
```

That is, I had assumed that the `infixl 4 ###` fixity declaration would exclusively apply to the term-level `(###)` definition, the `infixl 4 type ###` fixity declaration would exclusively apply to the type-level `(###)` definition, and there would be no conflict. Reading [the relevant GHC proposal once more](https://github.com/ghc-proposals/ghc-proposals/blob/8443acc903437cef1a7fbb56de79b6dce77b1a09/proposals/0065-type-infix.rst), this is indeed the plan for a future version of GHC. In the meantime, however, `infixl 4 ###` still refers to both the term-level and type-level definitions, so there is still a conflict:

```
$ ghc-9.10 Foo.hs
[1 of 1] Compiling Foo              ( Foo.hs, Foo.o )
Foo.hs:3:10: error: [GHC-50419]
    Multiple fixity declarations for ‘###’
    also at  Foo.hs:7:1-17
  |
3 | infixl 4 ###
  |          ^^^
```

As such, `singletons` will still need the workaround from `Wrinkle 1: When not to promote/single fixity declarations` for some time yet. The thing that changes with namespace specifiers is that we only need the workaround in order to support writing this style of code:

```hs
$(singletons
  [d| infixl 4 ###
      (###) :: a -> a -> a
    |])
```

We _wouldn't_ need the workaround, however, if the user had written `infixl 4 data ###` instead. If that were the case, then we could promote the fixity declaration to `infixl 4 type ###`, and then the two fixity declarations really would be mutually exclusive.
