### ISSUE TITLE
Would it be useful to provide a Generic (SomeSing k) instance?

### ISSUE THREAD

**Issue by andremarianiello** [goldfirere/singletons#623]
SomeSing does not have a Generic instance, and GHC cannot currently derive one for us. Would it be useful to provide one?

Here is one option:

```haskell
 instance (SingKind k, Generic (Demote k)) => Generic (SomeSing k) where
   type Rep (SomeSing k) = Rep (Demote k)                               
   from :: SomeSing k -> Rep (Demote k) x                               
   from (SomeSing kSing) = from (fromSing kSing)                        
   to :: Rep (Demote k) x -> SomeSing k                                 
   to rep = toSing (to rep)                                             
```

I think this would be handy to have, and is "canonical" in some sense. One downside is that this piggybacks on the Generic instance for `Demote k`, which could cause confusion for people expecting a generic representation with different type or constructor names. However, I still think it would worth having. What do you think?

**Comment by RyanGlScott** [comment]
I'm not very enthusiastic about this option, as this `Generic` instance would not describe `SomeSing` itself, but rather the underlying `Demote` type.

I'd be interested to know why you need a `Generic` instance for `SomeSing` in the first place, as `GHC.Generics` is incapable of expressing `Generic` instances for GADTs like `SomeSing` in general. If you _do_ need to work over `SomeSing` instances in a datatype-generic way, then you might be interested in [`kind-generics`](https://hackage.haskell.org/package/kind-generics), which is capable of defining a `GenericK (SomeSing k)` instance.

**Comment by andremarianiello** [comment]
> I'd be interested to know why you need a Generic instance for SomeSing in the first place, as GHC.Generics is incapable of expressing Generic instances for GADTs like SomeSing in general.

I first started down this path because I was interested in serializing (via a library like `flat`) datatypes containing existentially wrapped singletons, but the lack of Generic instance for them prevented me from using the Generic-based instances for my type. I might be able to work around this by using the demoted type instead, but if the definition was from a library using an existentially wrapped singleton instead then I wouldn't have this option.

> If you do need to work over SomeSing instances in a datatype-generic way, then you might be interested in [kind-generics](https://hackage.haskell.org/package/kind-generics), which is capable of defining a GenericK (SomeSing k) instance.

I like `kind-generics`, but as of right now there is much more ecosystem support for GHC.Generics. In my case, I can derive Flat instances from GHC.Generic instances, but not GenericK instances (unless there is a way to derive a Generic instance from a GenericK instance that I haven't been able to find). This means I am stuck writing Flat instances by hand, or writing a Generic instance by hand. The Generic instance is much more widely useful and much easier to get behaviorally correct than a hand-written serialization instance, so I went the Generic route. Then once I decided upon this course of action did I figure out how easy it was to get a Generic instance for _all_ existentially wrapped singletons.

I can always just keep this instance for myself, but I assume others could find myself in this situation, and also the instance is an orphan, so, if it should exist, it should exist in `singletons`.

> I'm not very enthusiastic about this option, as this Generic instance would not describe SomeSing itself, but rather the underlying Demote type.

Are you talking about the type and constructor names matching `Demote k` rather than `SomeSing k`? I could modify the Demoted representation to better represent this: something like `type Rep (SomeSing k) = SingRep k` where `SomeSingRep k` is a type family that maps M1 type names from `Rep (Demote k)` to the corresponding singleton type name (e.g. `DoorState -> SDoorState` or `DoorState` -> `SomeSing DoorState`) and maps M1 constructor names similarly (e.g `Opened` -> `SOpened` or `Opened` -> `SomeSing SOpened`). Would this increase your enthusiasm?

**Comment by RyanGlScott** [comment]
> Are you talking about the type and constructor names matching `Demote k` rather than `SomeSing k`?

The metadata is part of it, but I'm more concerned about the fact that the generic representation doesn't reflect the structure of the actual data type. For example, with the `Rep` instance you propose, the generic representation for `SomeSing Bool` would have two constructors, but this just isn't true: `SomeSing` only has one. The generic representation should reflect this, just like all other `Generic` instances do.

**Comment by andremarianiello** [comment]
> The metadata is part of it, but I'm more concerned about the fact that the generic representation doesn't reflect the structure of the actual data type.

That seems equally fixable to me, but before we dive to far into what Rep should be, I think it would makes sense to figure out if you would want such an instance, assuming we pick a representation you actually like. If we had a representation you liked, would you want the instance included, or are there other factors as well?

**Comment by RyanGlScott** [comment]
I certainly don't want a `Generic` instance that doesn't directly correspond to what `deriving Generic` would give you, no. I feel less strongly about a `GenericK` instance, although `singletons` currently doesn't depend on `kind-generics`—we could ponder putting such an instance in a separate package.

**Comment by andremarianiello** [comment]
> I certainly don't want a Generic instance that doesn't directly correspond to what deriving Generic would give you, no.

This has me mightily confused, since the inability to derive this instance is precisely what is tripping me up. But GHC can't derive it, so "what deriving Generic would give you" is meaningless. Unless you are talking about an instance derived via some non-GHC mechanism? If there is one such mechanism you are referring to I am happy to explore it.

**Comment by RyanGlScott** [comment]
Sorry, I should have worded that differently. What I meant to say is: I certainly don't want a hand-written `Generic` instance. A `Generic` instance really ought to be uniquely determined by the structure of the data type itself. (I roughly characterized this as "what `deriving Generic` would give you"—apologies for the confusion there.) See also [this discussion](https://gitlab.haskell.org/ghc/ghc/-/issues/13065).

**Comment by andremarianiello** [comment]
Thanks for the clarification and the link. That gives me a good view into your standpoint on what a Generic instance should be, which I appreciate. Based on that discussion it seems like `Data.Data` might be the more correct way to handle derived serialization instances. I will look into that more, but I may end up falling back into using my orphan instance anyway. Thanks so much!
