### ISSUE TITLE
Unable to silence warnings about *Sym0 being unused.

### ISSUE THREAD

**Issue by ocharles** [goldfirere/singletons#90]
We have:

```haskell
$(singletons [d|

    data SubscriptionChannel
      = BookingsChannel
      | ClassTemplatesChannel
      | ...
  |])
```

But this results in:

```
src/Metronome/SocketIO/Types.hs:59:3: Warning:
    Defined but not used:
      type constructor or class ‘BookingsChannelSym0’

src/Metronome/SocketIO/Types.hs:59:3: Warning:
    Defined but not used:
      type constructor or class ‘ClassTemplatesChannelSym0’

...
```

I see there is http://hackage.haskell.org/package/singletons-1.0/docs/Data-Singletons-SuppressUnusedWarnings.html but I'm not entirely sure how to use - importantly the module only for its instances doesn't have any effect.

**Comment by goldfirere** [comment]
Closing as likely unsolvable by singletons. Do reopen if you feel the need.
