### ISSUE TITLE
For GHC 7.10, use Data.Void from base

### ISSUE THREAD

**Issue by goldfirere** [goldfirere/singletons#99]

**Comment by jstolarek** [comment]
I was thinking about fixing this one but this will make us clutter the source code with conditional compilation - something that we planned on isolating inside th-desugar. Of course th-desugar can't help here in any way but I wonder if we are happy with having conditional compilation all over the place (already added some with #112).

**Comment by goldfirere** [comment]
Would this really be any worse than the fix for #112? Couldn't we just re-export `base`'s `Void` from our `Void` module in 7.10?

**Comment by jstolarek** [comment]
> Would this really be any worse than the fix for #112?

In terms of quality - no. It's just quantity that worries me.

> Couldn't we just re-export base's Void from our Void module in 7.10?

But that does not avoid the need for conditional compilation, right?

**Comment by goldfirere** [comment]
I'm confused here -- you would need conditional compilation in our `Void` module, but I don't think you'd need it elsewhere...

**Comment by jstolarek** [comment]
Yes, that's exactly what I meant. I understand we're OK with having conditional compilation in our Void module?

**Comment by int-index** [comment]
Now that only `GHC 7.10` supported, it makes sense to simply import `Void` from `base` without conditional compilation.
